select jsonb_build_object(
 'columns',(select jsonb_agg(jsonb_build_array(table_schema,table_name,column_name,udt_name,is_nullable,column_default) order by table_schema,table_name,ordinal_position) from information_schema.columns where table_schema in ('aevic','aevic_private') and table_name not like 'legacy_import_%'),
 'constraints',(select jsonb_agg(jsonb_build_array(n.nspname,c.relname,k.conname,pg_get_constraintdef(k.oid)) order by n.nspname,c.relname,k.conname) from pg_constraint k join pg_class c on c.oid=k.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('aevic','aevic_private') and c.relname not like 'legacy_import_%'),
 'functions',(select jsonb_agg(jsonb_build_array(n.nspname,p.proname,pg_get_function_identity_arguments(p.oid),p.prosecdef,p.proconfig,md5(p.prosrc)) order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('aevic','aevic_private')),
 'indexes',(select jsonb_agg(jsonb_build_array(schemaname,tablename,indexname,indexdef) order by schemaname,tablename,indexname) from pg_indexes where schemaname in ('aevic','aevic_private') and tablename not like 'legacy_import_%'),
 'functionAccess',(select jsonb_agg(jsonb_build_array(n.nspname,p.proname,pg_get_function_identity_arguments(p.oid),has_function_privilege('anon',p.oid,'execute'),has_function_privilege('authenticated',p.oid,'execute'),has_function_privilege('service_role',p.oid,'execute')) order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('aevic','aevic_private')),
 'tableAccess',(select jsonb_agg(jsonb_build_array(table_schema,table_name,grantee,privilege_type) order by table_schema,table_name,grantee,privilege_type) from information_schema.table_privileges where table_schema in ('aevic','aevic_private') and table_name not like 'legacy_import_%' and grantee in ('anon','authenticated','service_role','PUBLIC')),
 'policies',(select jsonb_agg(jsonb_build_array(schemaname,tablename,policyname,roles,cmd,qual,with_check) order by schemaname,tablename,policyname) from pg_policies where schemaname in ('aevic','aevic_private') and tablename not like 'legacy_import_%'),
 'rls',(select jsonb_agg(jsonb_build_array(n.nspname,c.relname,c.relrowsecurity,c.relforcerowsecurity) order by n.nspname,c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('aevic','aevic_private') and c.relkind='r' and c.relname not like 'legacy_import_%'),
 'triggers',(select jsonb_agg(jsonb_build_array(n.nspname,c.relname,t.tgname,t.tgenabled,pg_get_triggerdef(t.oid)) order by n.nspname,c.relname,t.tgname) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal and (n.nspname='aevic' or (n.nspname='auth' and t.tgname='aevic_signup')))
);
