import { useEffect,useState } from 'react';
import { Button,EmptyState,Input,LoadingSkeleton,PageHeader,Select } from '../../components/common/primitives';
import { services } from '../../services';
import type { LegacyClaimReview,LegacyHolding } from '../../types/legacyClaims';

export function AdminLegacyClaimsPage(){
 const [claims,setClaims]=useState<LegacyClaimReview[]>(),[holdings,setHoldings]=useState<LegacyHolding[]>([]),[error,setError]=useState(''),[selected,setSelected]=useState(''),[evidence,setEvidence]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[issued,setIssued]=useState<{code?:string;expiresAt?:string}>();
 async function load(){setError('');try{const [queue,teams]=await Promise.all([services.legacyClaims.queue(),services.legacyClaims.holdings()]);setClaims(queue);setHoldings(teams);}catch{setError('Sahiblik sorğuları yüklənmədi və ya moderator icazəsi yoxdur.');}}
 useEffect(()=>{void load();},[]);const active=claims?.find(c=>c.id===selected);
 async function review(decision:'approve'|'reject'){if(!active)return;setBusy(true);setIssued(undefined);setError('');try{setIssued(await services.legacyClaims.review(active.id,decision,evidence,active.version));await load();setConfirmed(false);}catch{setError('Qərar saxlanılmadı. Sorğunu yeniləyib yenidən yoxlayın.');}finally{setBusy(false);}}
 return <><PageHeader title="Əvvəlki komandaların sahibliyi" description="Yalnız müstəqil sahiblik sübutu ilə qərar verin. Eyni email və ya kapitan adı kifayət deyil. Öz sorğunuzu təsdiqləyə bilməzsiniz."/>{error&&<div role="alert"><p>{error}</p><Button onClick={()=>void load()}>Yenidən yüklə</Button></div>}{!claims&&!error&&<LoadingSkeleton variant="table" rows={3}/>}
 <section><h2>Əvvəlki komandalar · {holdings.length}</h2>{holdings.map(h=><p key={h.teamId}>{h.sourceKey} · {h.name} · {h.status} · {h.legacyStatus}</p>)}{claims?.length===0&&<EmptyState title="Yoxlama sorğusu yoxdur" body="Əvvəlki hesablar və komanda məlumatları qorunur. Yeni sahiblik yalnız yoxlamadan sonra verilir."/>}</section>
 {Boolean(claims?.length)&&<form className="account-form" onSubmit={e=>{e.preventDefault();void review('approve');}}><Select label="Sahiblik sorğusu" value={selected} onChange={e=>{setSelected(e.target.value);setConfirmed(false);setEvidence('');setIssued(undefined);}} required><option value="">Sorğunu seçin</option>{claims!.map(c=><option key={c.id} value={c.id} disabled={c.status==='consumed'}>{c.sourceKey} · {c.teamName??'Uyğun idxal yoxdur'} · {c.status}</option>)}</Select>{active&&<><p>Müraciət edən: {active.applicantEmail}</p><p>Əvvəlki təsdiqlənmiş əlaqə: {active.legacyContact?.name} · {active.legacyContact?.email} · {active.legacyContact?.contact}</p><small>Əlaqəni müraciət edənin verdiyi yeni məlumatla əvəz etməyin. Sübut qeydində məxfi məlumat və kod saxlamayın.</small></>}<Input label="Müraciət edənin sübutu olan dəstək sorğusunun UUID-si" value={evidence} onChange={e=>setEvidence(e.target.value)} pattern="[0-9a-fA-F-]{36}" required/><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Sahiblik müstəqil mənbədən yoxlanılıb; kod yalnız həmin təsdiqlənmiş əvvəlki kanal vasitəsilə çatdırılacaq.</label><Button type="submit" loading={busy} disabled={!active?.teamName||active.claimed||!confirmed}>Təsdiqlə və kod yarat</Button><Button type="button" variant="secondary" loading={busy} disabled={!active||!evidence.match(/^[0-9a-fA-F-]{36}$/)} onClick={()=>void review('reject')}>Rədd et / kodu ləğv et</Button></form>}
 {issued?.code&&<section role="status"><h2>Birdəfəlik kod — yalnız bu dəfə göstərilir</h2><p>Kodu təsdiqlənmiş əvvəlki əlaqə kanalından çatdırın. Müraciət forması və ümumi bildirişlə göndərməyin.</p><code style={{overflowWrap:'anywhere'}}>{issued.code}</code><p>Bitmə vaxtı: {issued.expiresAt}</p><Button variant="secondary" onClick={()=>setIssued(undefined)}>Kodu ekrandan sil</Button></section>}</>;
}
