import { ArrowLeft,CheckCircle2 } from 'lucide-react';
import { useEffect,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { Button,EmptyState,LoadingSkeleton,PageHeader,SectionHeading,StatusBadge,Textarea,Toast } from '../../components/common/primitives';
import { services } from '../../services';
import type { ResultDispute } from '../../types/domain';
import { disputeStatus } from './TeamOperationsPagesShared';
export function DisputeDetailPage({ admin = false }: { admin?: boolean }) {
  const { disputeId = '' } = useParams(); const [item, setItem] = useState<ResultDispute>(); const [loading, setLoading] = useState(true); const [note, setNote] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { services.disputes.get(disputeId).then((value) => { setItem(value); setNote(value?.adminNote ?? ''); }).catch(() => setNotice('Məlumat yüklənmədi. Səhifəni yeniləyib cəhd edin.')).finally(() => setLoading(false)); }, [disputeId]);
  const review = async (status: 'resolved' | 'rejected') => { if (!item) return; try {const next = await services.disputes.review(item.id, status, note); setItem(next); setNotice(status === 'resolved' ? 'Etiraz həll edildi.' : 'Etiraz rədd edildi.');}catch{setNotice('Qərar saxlanmadı. Yenidən cəhd edin.');} };
  const [evidenceLinks,setEvidenceLinks]=useState<Record<string,string>>({});const accessEvidence=async(id:string)=>{try{const {url}=await services.media.evidenceAccess(id);setEvidenceLinks(current=>({...current,[id]:url}));}catch{setNotice('Sübut faylı əlçatan deyil.');}};
  if (loading) return <LoadingSkeleton variant="list" rows={6} />;
  if (!item) return <EmptyState title="Etiraz tapılmadı" body={notice || "Bu etiraz mövcud deyil və ya sizə aid deyil."} />;
  return <><Link className="text-link" to={admin ? '/admin/disputes' : '/team/disputes'}><ArrowLeft size={16} />Etirazlar</Link><PageHeader eyebrow={item.id} title={item.tournamentName} description={item.roundLabel} actions={<StatusBadge status={disputeStatus(item.status)}>{item.status}</StatusBadge>} />{notice && <Toast title={notice} onClose={() => setNotice('')} />}<div className="request-detail-grid"><section><SectionHeading title="Etiraz məlumatı" /><dl className="detail-ledger"><div><dt>Komanda</dt><dd>{item.teamName}</dd></div><div><dt>Problem</dt><dd>{item.issueType}</dd></div><div><dt>Təsvir</dt><dd>{item.description}</dd></div><div><dt>Sübut</dt><dd>{item.evidenceNames.length ? item.evidenceNames.map((name,index)=>{const id=item.evidenceIds?.[index];return <div key={id??name}>{id ? evidenceLinks[id]?<a href={evidenceLinks[id]} target="_blank" rel="noopener noreferrer">{name} — yüklə (60 san.)</a>:<Button variant="ghost" onClick={()=>void accessEvidence(id)}>{name} — giriş al</Button>:name}</div>;}) : 'Əlavə edilməyib'}</dd></div><div><dt>Son müddət</dt><dd>{new Date(item.deadlineAt).toLocaleString('az-AZ')}</dd></div></dl></section><aside><SectionHeading title="Qərar" />{admin ? <><Textarea label="Admin qeydi" value={note} onChange={(event) => setNote(event.target.value)} required /><div className="decision-actions"><Button onClick={() => void review('resolved')} icon={<CheckCircle2 size={17} />}>Həll et</Button><Button variant="danger" onClick={() => void review('rejected')}>Rədd et</Button></div></> : <p>{item.adminNote ?? 'Etiraz admin yoxlamasındadır.'}</p>}</aside></div></>;
}
