import { useEffect,useState } from 'react';
import { Link,useNavigate } from 'react-router-dom';
import { Button,EmptyState,Input,LoadingSkeleton,PageHeader,Select } from '../../components/common/primitives';
import { services } from '../../services';
import type { LegacyClaim,LegacyRoster,LegacyRosterPlayer } from '../../types/legacyClaims';

export function LegacyClaimPage(){
 const [claims,setClaims]=useState<LegacyClaim[]>(),[roster,setRoster]=useState<LegacyRoster|null>(null),[sourceKey,setSourceKey]=useState(''),[code,setCode]=useState(''),[selected,setSelected]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [players,setPlayers]=useState<LegacyRosterPlayer[]>([]);const navigate=useNavigate();
 async function load(){setError('');try{const [list,info]=await Promise.all([services.legacyClaims.list(),services.legacyClaims.roster()]);setClaims(list);setRoster(info);if(info&&!info.completed)setPlayers(info.rosterNames.map(ign=>({ign,uid:'',role:'' as LegacyRosterPlayer['role']})));}catch{setError('Məlumat yüklənmədi. Email təsdiqini və sessiyanızı yoxlayın.');}}
 useEffect(()=>{void load();},[]);
 async function run(action:()=>Promise<void>,message:string){setBusy(true);setError('');setNotice('');try{await action();setNotice(message);}catch{setError('Əməliyyat tamamlanmadı. Kod etibarsız, vaxtı bitmiş və ya artıq istifadə edilmiş ola bilər. Sahibliyi və sessiyanı yoxlayıb yenidən cəhd edin.');}finally{setBusy(false);}}
 return <><PageHeader title="Köhnə komanda sahibliyi" description="Email uyğunluğu sahibliyə sübut deyil. Moderator müstəqil yoxlama aparır və birdəfəlik kodu təsdiqlənmiş əvvəlki əlaqə kanalından çatdırır."/>{error&&<div role="alert"><p>{error}</p><Button variant="secondary" onClick={()=>void load()}>Yenidən yüklə</Button></div>}{notice&&<p role="status">{notice}</p>}{!claims&&!error?<LoadingSkeleton variant="table" rows={3}/>:null}
 <form className="account-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await services.legacyClaims.request(sourceKey);await load();},'Sorğu qeydə alındı. Bu bildiriş komandanın mövcudluğunu və ya sahibliyini təsdiqləmir.');}}><Input label="Əvvəlki komanda nömrəsi" inputMode="numeric" pattern="[0-9]{1,19}" maxLength={19} value={sourceKey} onChange={e=>setSourceKey(e.target.value)} required/><Button type="submit" loading={busy}>Sahiblik yoxlaması istə</Button></form>
 <p>Moderatorun yoxlaması üçün əvvəlki komanda nömrəsini və sahiblik sübutunu <Link to="/account/support/tickets/new">dəstək sorğusunda</Link> təqdim edin.</p>
 {claims?.length? <form className="account-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await services.legacyClaims.consume(selected,code);setCode('');await services.auth.getSession();await load();},'Komanda hesabınıza bağlandı. Turnir qeydiyyatından əvvəl real oyunçu ID-lərini və rollarını tamamlayın.');}}><Select label="Təsdiqlənən sorğu" value={selected} onChange={e=>setSelected(e.target.value)} required><option value="">Sorğunu seçin</option>{claims.map(c=><option key={c.id} value={c.id} disabled={c.status!=='approved'}>{c.sourceKey} · {c.status}</option>)}</Select><Input label="Birdəfəlik sahiblik kodu" value={code} onChange={e=>setCode(e.target.value.trim())} autoComplete="off" minLength={43} maxLength={43} required/><Button type="submit" loading={busy} disabled={!selected}>Komandanı bağla</Button></form>:claims?<EmptyState title="Hələ sahiblik sorğusu yoxdur" body="Əvvəlki qeydiyyat nömrənizlə yoxlama istəyə bilərsiniz."/>:null}
 {roster&&!roster.completed&&<form className="account-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await services.legacyClaims.completeRoster(players);await load();},'Heyət saxlanıldı.');}}><h2>Əvvəlki heyəti tamamla</h2><p>Adlar əvvəlki qeydiyyatdan qorunub. Real PUBG ID-ləri və rolları daxil edin: 1 kapitan, 3 əsas və varsa 1 ehtiyat. ID-lər uydurulmamalıdır.</p>{players.map((p,i)=><fieldset key={i}><legend>{p.ign}</legend><Input label={`${p.ign} — PUBG ID`} value={p.uid} inputMode="numeric" pattern="[0-9]{5,20}" maxLength={20} required onChange={e=>setPlayers(v=>v.map((p,n)=>n===i?{...p,uid:e.target.value}:p))}/><Select label={`${p.ign} — rol`} value={p.role} required onChange={e=>setPlayers(v=>v.map((p,n)=>n===i?{...p,role:e.target.value as LegacyRosterPlayer['role']}:p))}><option value="">Rolu seçin</option><option value="captain">Kapitan</option><option value="starter">Əsas</option><option value="substitute">Ehtiyat</option></Select></fieldset>)}<Button type="submit" loading={busy}>Heyəti saxla</Button></form>}
 {roster&&<><p role="status">Əvvəlki qeydlər qorunur. Statistikalar yalnız sistemdə qeydə alınmış rəsmi nəticələri əhatə edir.</p><Button onClick={()=>navigate('/team')}>Komanda panelinə keç</Button></>}</>;
}
