import { ArrowLeft,RefreshCcw } from 'lucide-react';
import { useEffect,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { Button,EmptyState,LoadingSkeleton,PageHeader,SectionHeading,StatusBadge,TeamLogo,Textarea,Toast } from '../../components/common/primitives';
import { services } from '../../services';
import type { RosterChangeRequest } from '../../types/domain';
import { requestStatus } from './TeamOperationsPagesShared';
export function RosterRequestDetailPage({ admin = false }: { admin?: boolean }) {
  const { requestId = '' } = useParams(); const [item, setItem] = useState<RosterChangeRequest>(); const [loading, setLoading] = useState(true); const [note, setNote] = useState(''); const [notice, setNotice] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { services.rosterRequests.get(requestId).then((value) => { setItem(value); setNote(value?.adminNote ?? ''); }).catch(() => setNotice('Məlumat yüklənmədi. Səhifəni yeniləyib cəhd edin.')).finally(() => setLoading(false)); }, [requestId]);
  const review = async (status: 'approved' | 'rejected') => { if (!item || saving || !['pending', 'under-review'].includes(item.status)) return; setSaving(true); try {const next = await services.rosterRequests.review(item.id, status, note); setItem(next); setNotice(status === 'approved' ? 'Roster sorğusu təsdiqləndi.' : 'Roster sorğusu rədd edildi.');}catch{setNotice('Qərar saxlanmadı. Yenidən cəhd edin.');} finally { setSaving(false); } };
  if (loading) return <LoadingSkeleton variant="list" rows={6} />;
  if (!item) return <EmptyState title="Sorğu tapılmadı" body={notice || "Bu heyət sorğusu mövcud deyil və ya sizə aid deyil."} />;
  return <><Link className="text-link" to={admin ? '/admin/roster-requests' : '/team/roster-requests'}><ArrowLeft size={16} />Sorğular</Link><PageHeader eyebrow={item.id} title="Heyət dəyişikliyi" description={`${item.teamName} · ${item.tournamentName ?? 'Ümumi roster'}`} actions={<StatusBadge status={requestStatus(item.status)}>{item.status}</StatusBadge>} />{notice && <Toast title={notice} onClose={() => setNotice('')} />}<div className="request-detail-grid"><section><SectionHeading title="Dəyişiklik" /><div className="replacement-pair"><div><span>ÇIXAN OYUNÇU</span><TeamLogo name={item.outgoing.ign} /><strong>{item.outgoing.ign}</strong><small>{item.outgoing.role}</small></div><RefreshCcw size={21} /><div><span>YENİ OYUNÇU</span><TeamLogo name={item.incoming.ign} /><strong>{item.incoming.ign}</strong><small>{item.incoming.role} · UID {item.incoming.uid ?? '—'}</small></div></div><dl className="detail-ledger"><div><dt>Səbəb</dt><dd>{item.reason}</dd></div><div><dt>Göndərilib</dt><dd>{new Date(item.submittedAt).toLocaleString('az-AZ')}</dd></div><div><dt>Son yenilənmə</dt><dd>{new Date(item.updatedAt).toLocaleString('az-AZ')}</dd></div></dl></section><aside><SectionHeading title="Admin qeydi" />{admin && ['pending', 'under-review'].includes(item.status) ? <><Textarea label="Qərar qeydi" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Qərarın faktiki səbəbi" /><div className="decision-actions"><Button disabled={saving} onClick={() => void review('approved')}>Təsdiqlə</Button><Button variant="danger" disabled={saving} onClick={() => void review('rejected')}>Rədd et</Button></div></> : <p>{item.adminNote ?? 'Admin qeydi hələ yoxdur.'}</p>}</aside></div></>;
}
