import {
ArrowRight
} from 'lucide-react';
import { Link } from 'react-router-dom';
import {
EmptyState,
PageHeader,
StatusBadge
} from '../../components/common/primitives';
import { useTeamCompetitionContexts } from '../../services/PlatformDataContext';

export function TeamTournamentsPage() {
  const { current, all } = useTeamCompetitionContexts();
  if (!all.length) return <><PageHeader eyebrow="Yarış qeydiyyatları" title="Turnirlərim" description="Komandanın aktiv və tamamlanmış turnirləri." /><EmptyState title="Turnir qeydiyyatı yoxdur" body="Komanda bir turnirə qoşulduqda əməliyyat xətti burada görünəcək." action={<Link className="button button--secondary" to="/tournaments"><span>Turnirləri kəşf et</span></Link>} /></>;
  const completed = all.filter((context) => context.lifecycle === 'completed');
  return <><PageHeader eyebrow="Yarış iştirakları" title="Turnirlərim" description="Cari qeydiyyat, slot, check-in və arxiv bir yarış xəttində." /><div className="team-tournament-list">{current && <article className="team-tournament-active"><div><StatusBadge status={current.participation.status === 'confirmed' ? 'approved' : 'warning'}>{current.participation.status === 'confirmed' ? 'İştirak təsdiqlənib' : 'İştirak yoxlanılır'}</StatusBadge><span>Cari yarış</span></div><h2>{current.tournament.name}</h2><div className="entry-facts"><span>Slot<strong>{current.participation.slotNumber ? `#${String(current.participation.slotNumber).padStart(2, '0')}` : 'Məlumat yoxdur'}</strong></span><span>Check-in<strong>{current.checkIn ? new Date(current.checkIn.opensAt).toLocaleString('az-AZ', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }) : 'Məlumat yoxdur'}</strong></span><span>Növbəti matç<strong>{current.firstMatch ? `${current.firstMatch.map} · ${new Date(current.firstMatch.startsAt).toLocaleTimeString('az-AZ', { hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Baku' })}` : 'Plan yoxdur'}</strong></span><span>Otaq<strong>{current.room?.status === 'released' ? 'Hazırdır' : current.room?.status === 'locked' ? 'Bağlıdır' : 'Məlumat yoxdur'}</strong></span></div><Link className="button button--primary" to={`/team/tournaments/${current.tournament.id}`}><span>Turnir əməliyyatlarını aç</span><ArrowRight size={17} /></Link></article>}{all.filter(entry => entry !== current && entry.lifecycle !== 'completed').map(entry => <article className="team-tournament-history" key={entry.tournament.id}><span>{entry.participation.status}</span><h2>{entry.tournament.name}</h2><p>{entry.participation.groupLabel ?? 'Qrup gözlənilir'} · {entry.nextMatch?.map ?? 'Matç gözlənilir'}</p><Link to={`/team/tournaments/${entry.tournament.id}`}>Əməliyyatlar <ArrowRight size={16} /></Link></article>)}{completed.map((context) => { const points = context.history.reduce((total, match) => total + match.points, 0); const wwcd = context.history.filter((match) => match.wwcd).length; return <article className="team-tournament-history" key={context.tournament.id}><span>Tamamlanıb · {new Date(context.tournament.endsAt).getFullYear()}</span><h2>{context.tournament.name}</h2><div><strong>{context.participation.resultPlacement ? `#${String(context.participation.resultPlacement).padStart(2, '0')}` : '—'}</strong><span>Yekun yer</span><strong>{context.history.length ? points : '—'}</strong><span>Dərc edilmiş xal · {context.history.length} matç</span><strong>{context.history.length ? wwcd : '—'}</strong><span>WWCD</span></div><Link to={`/team/tournaments/${context.tournament.id}`}>Yarış tarixçəsi <ArrowRight size={16} /></Link></article>; })}</div></>;
}
