import {beforeAll,beforeEach,describe,expect,it,vi,afterEach} from 'vitest';
import sharp from 'sharp';
import {createApp} from '../../server/app';
import {CaptainService} from '../../server/captain/service';
import {hashPassword,verifyPassword,makeSession,checkSession} from '../../server/captain/crypto';
import type {CaptainRow,CaptainStore,TeamPatch} from '../../server/captain/store';
import {ServiceError} from '../../server/errors';
import {validateImage,SupabaseCaptainMedia} from '../../server/captain/media';

// In-memory fixtures only. No SQL, SMTP, Resend, Supabase or production writes.
class MemoryStore implements CaptainStore {
 rows=new Map<string,CaptainRow>();
 async ready(){}
 async byEmail(email:string){return [...this.rows.values()].find(r=>r.email===email);}
 async byId(id:string){const r=this.rows.get(id);return r?{...r}:undefined;}
 async issueReset(row:CaptainRow,value:string){const r=this.rows.get(row.id);if(!r||r.password_hash!==row.password_hash||r.reset_token!==row.reset_token)return false;this.rows.set(row.id,{...r,reset_token:value});return true;}
 async consumeReset(id:string,expected:string,hash:string,expires:number){const r=this.rows.get(id);if(!r||r.reset_token!==expected||clock>=expires*1000)return false;this.rows.set(id,{...r,password_hash:hash,reset_token:null});return true;}
 async changeHash(id:string,expected:string,hash:string){const r=this.rows.get(id);if(!r||r.password_hash!==expected)return false;this.rows.set(id,{...r,password_hash:hash,reset_token:null});return true;}
 async update(id:string,hash:string,patch:TeamPatch){const r=this.rows.get(id);if(!r||r.password_hash!==hash)throw new ServiceError(401,'UNAUTHORIZED');const result={...r,...patch} as CaptainRow;this.rows.set(id,result);return result;}
 async register(values:TeamPatch){if([...this.rows.values()].some(r=>r.email.toLowerCase()===values.email?.toLowerCase()||r.team_name.toLowerCase()===values.team_name?.toLowerCase()))throw new ServiceError(409,'REGISTRATION_CONFLICT');const row={...values,id:'19',reset_token:null} as CaptainRow;this.rows.set(row.id,row);return row;}
 async publicMedia(id:string){return id==='f7b98b59-32ca-4577-a3e5-84f7185b3e22'?{bucket:'fixture',name:'original.png'}:undefined;}
}
const secret='fixture-session-secret-32-bytes-minimum',password='ModernFixture42';
let modern:string,clock:number,store:MemoryStore,service:CaptainService,links:string[];
const config={supabaseUrl:'https://nmjjibifcuzjlsvfcaaz.supabase.co',publishableKey:'fixture-public',siteUrl:'https://fixture.test',secureCookies:true,sessionSecret:secret};
const mailer={send:async(_to:string,link:string)=>{links.push(link);}};
const row=(id:string,hash=modern):CaptainRow=>({id,team_name:`Team ${id}`,captain_name:'Captain Fixture',captain_contact:'+994500000000',email:`captain${id}@example.test`,password_hash:hash,reset_token:null,player1_ign:'First',player2_ign:'Second',player3_ign:'Third',player4_ign:'Fourth',player5_ign:'Reserve',logo_url:'/api/media/f7b98b59-32ca-4577-a3e5-84f7185b3e22',status:'pending',tier:'entry',match_results:[],created_at:'2020-01-01T00:00:00Z'});
const token=()=>new URLSearchParams(new URL(links.at(-1)!).hash.slice(1)).get('token')!;
const cookie=()=>`__Host-aevic-captain=${service.sessionCookie(store.rows.get('2')!)}`;
const app=()=>createApp(config,{}, {store,mailer,now:()=>clock});
const request=(path:string,body:unknown={},method='POST',auth=true)=>app().request(`/api${path}`,{method,headers:{origin:config.siteUrl,'content-type':'application/json',...(auth?{cookie:cookie()}:{})},...(method==='GET'?{}:{body:JSON.stringify(body)})});
beforeAll(async()=>{modern=await hashPassword(password);});
beforeEach(()=>{clock=Date.parse('2026-09-24T00:00:00Z');links=[];store=new MemoryStore();store.rows.set('2',row('2'));store.rows.set('7',row('7'));service=new CaptainService(store,secret,config.siteUrl,mailer,()=>clock,0);vi.stubGlobal('fetch',vi.fn(()=>{throw Error('Unexpected network request');}));});
afterEach(()=>vi.unstubAllGlobals());
describe('captain auth against existing team fixtures',()=>{
 it('uses modern scrypt, random salts and no legacy verifier',async()=>{expect(modern).not.toContain(password);expect(await verifyPassword(password,modern)).toBe(true);expect(await verifyPassword('Wrong42',modern)).toBe(false);expect(await verifyPassword(password,'legacy-unknown')).toBe(false);expect(await hashPassword(password)).not.toBe(modern);});
 it('resets same legacy team, preserves every other field, consumes digest and permits login',async()=>{
  store.rows.set('2',row('2','legacy-unknown'));const before={...store.rows.get('2')!};await service.requestReset(before.email);const raw=token();expect(store.rows.get('2')!.reset_token).not.toContain(raw);expect(await service.inspectReset(raw)).toBe('valid');
  await service.resetPassword(raw,password);expect(await service.inspectReset(raw)).toBe('invalid');await expect(service.resetPassword(raw,password)).rejects.toMatchObject({code:'INVALID_RECOVERY_TOKEN'});
  const after=store.rows.get('2')!;expect({...after,password_hash:before.password_hash,reset_token:before.reset_token}).toEqual(before);expect((await service.login(before.email,password,false)).row.id).toBe('2');
 });
 it('expires tokens and rejects association tampering',async()=>{await service.requestReset('captain2@example.test');const raw=token();expect(await service.inspectReset(raw.replace(/^2\./,'7.'))).toBe('invalid');clock+=1800000;expect(await service.inspectReset(raw)).toBe('expired');await expect(service.resetPassword(raw,password)).rejects.toMatchObject({code:'INVALID_RECOVERY_TOKEN'});});
 it('only one concurrent reset succeeds and revokes preexisting sessions',async()=>{const old=service.sessionCookie(store.rows.get('2')!);await service.requestReset('captain2@example.test');const results=await Promise.allSettled([service.resetPassword(token(),password),service.resetPassword(token(),password)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);await expect(service.authenticate(old)).rejects.toMatchObject({status:401});});
 it('persists signed sessions, checks expiry, and logout revokes every previous session',async()=>{const login=await service.login('captain2@example.test',password,true);expect((await service.authenticate(login.cookie)).id).toBe('2');expect(checkSession(login.cookie,'7',modern,secret,clock)).toBe(false);await service.logout(login.cookie);await expect(service.authenticate(login.cookie)).rejects.toMatchObject({status:401});expect(await verifyPassword(password,store.rows.get('2')!.password_hash)).toBe(true);const next=service.sessionCookie(store.rows.get('2')!);clock+=8*3600000;await expect(service.authenticate(next)).rejects.toMatchObject({status:401});});
 it('reads session cookies after refresh, revokes others and clears cookies on logout',async()=>{const old=service.sessionCookie(store.rows.get('2')!);const refreshed=await app().request('/api/me/session',{headers:{cookie:`__Host-aevic-captain=${old}`}});expect((await refreshed.json()).user.teamId).toBe('2');const current=await service.revokeOthers(old);await expect(service.authenticate(old)).rejects.toMatchObject({status:401});expect((await service.authenticate(current)).id).toBe('2');const logout=await app().request('/api/auth/logout',{method:'POST',headers:{origin:config.siteUrl,cookie:`__Host-aevic-captain=${current}`}});expect(logout.status).toBe(204);expect(logout.headers.get('set-cookie')).toContain('Max-Age=0');await expect(service.authenticate(current)).rejects.toMatchObject({status:401});});
 it('gives identical reset receipts for known and unknown email; enforces secure cookies',async()=>{for(const email of ['captain2@example.test','missing@example.test']){const res=await request('/auth/password-reset',{email},'POST',false);expect(res.status).toBe(204);expect(await res.text()).toBe('');}const res=await request('/auth/login',{email:'captain2@example.test',password,remember:true},'POST',false);expect(res.status).toBe(200);expect(res.headers.get('set-cookie')).toMatch(/__Host-aevic-captain=.*HttpOnly.*Secure.*SameSite=Strict/);expect(await res.text()).not.toMatch(/password_hash|reset_token|aevic-scrypt/);});
 it('registers with generated original IDs and rejects duplicate and privileged fields',async()=>{const draft={teamName:'New fixture',firstName:'New',lastName:'Captain',phone:'+994500000001',email:'new@example.test',players:[1,2,3,4,5].map(i=>({ign:`Player ${i}`}))};const body={draft,password,idempotencyKey:'fixture-request-001'};const result=await request('/registrations',body,'POST',false);expect(result.status).toBe(201);expect((await result.json()).registrationId).toBe('19');expect(store.rows.get('19')).toMatchObject({status:'pending',tier:'entry',player5_ign:'Player 5'});expect(await verifyPassword(password,store.rows.get('19')!.password_hash)).toBe(true);expect((await request('/registrations',body,'POST',false)).status).toBe(409);expect((await request('/registrations',{...body,status:'approved'},'POST',false)).status).toBe(422);expect(store.rows.size).toBe(3);});
 it('changes only owned fields and rejects cross-team, forged sessions and CSRF',async()=>{expect((await request('/teams/2',{name:'Updated fixture'},'PATCH')).status).toBe(200);expect((await request('/teams/7',{name:'Stolen'},'PATCH')).status).toBe(403);expect((await request('/teams/2',{name:'Test',status:'approved'},'PATCH')).status).toBe(422);expect((await request('/teams/2/roster/5',{ign:'New reserve'},'PUT')).status).toBe(200);expect(store.rows.get('2')!.player5_ign).toBe('New reserve');expect(store.rows.get('7')!.team_name).toBe('Team 7');expect((await request('/me/account',{firstName:'Updated',lastName:'Captain',phone:'+994500000002'},'PATCH')).status).toBe(200);const res=await app().request('/api/teams/2',{method:'PATCH',headers:{origin:'https://evil.test',cookie:cookie(),'content-type':'application/json'},body:'{"name":"Attack"}'});expect(res.status).toBe(403);expect((await app().request('/api/me/team',{headers:{cookie:`__Host-aevic-captain=${makeSession('2',modern,'wrong-secret',100,clock)}`}})).status).toBe(401);});
 it('rejects login bursts before lookup and fails closed on unsafe DB permissions',async()=>{const application=app();for(let i=0;i<10;i++)await application.request('/api/auth/login',{method:'POST',headers:{origin:config.siteUrl,'content-type':'application/json'},body:'{}'});expect((await application.request('/api/auth/login',{method:'POST',headers:{origin:config.siteUrl,'content-type':'application/json'},body:'{}'})).status).toBe(429);store.ready=async()=>{throw new ServiceError(503,'AUTH_DATABASE_PERMISSIONS_UNSAFE');};expect((await request('/me/team',{},'GET')).status).toBe(503);});
});
describe('existing media and authorized uploads',()=>{
 it('decodes PNG and preserves original aspect ratio/bytes; rejects mislabeled and oversized input',async()=>{const bytes=await sharp({create:{width:37,height:19,channels:4,background:'#ff000080'}}).png().toBuffer();expect(await validateImage(bytes,'image/png')).toEqual({type:'image/png',extension:'png'});await expect(validateImage(bytes,'image/jpeg')).rejects.toMatchObject({code:'INVALID_IMAGE'});await expect(validateImage(new Uint8Array(4000001))).rejects.toMatchObject({status:413});await expect(validateImage(new TextEncoder().encode('<svg/>'),'image/png')).rejects.toMatchObject({code:'INVALID_IMAGE'});vi.stubGlobal('fetch',vi.fn(async()=>new Response(bytes)));const media=new SupabaseCaptainMedia(config);const read=await media.read('fixture','original.png');expect(Buffer.from(read.bytes)).toEqual(bytes);expect(read.type).toBe('image/png');expect(await sharp(read.bytes).metadata()).toMatchObject({width:37,height:19});});
 it('uploads unchanged PNG bytes to fresh objects and refuses private buckets',async()=>{const bytes=await sharp({create:{width:23,height:11,channels:4,background:'blue'}}).png().toBuffer();let publicBucket=true;const writes:string[]=[];vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);if(url.includes('/storage/v1/bucket/'))return new Response(JSON.stringify({id:'existing',public:publicBucket}),{headers:{'content-type':'application/json'}});writes.push(url);expect(new Headers(init?.headers).get('x-upsert')).toBe('false');expect(Buffer.from(init?.body as Uint8Array)).toEqual(bytes);return new Response(JSON.stringify({Id:'new-id',Key:'existing/image.png'}),{headers:{'content-type':'application/json'}});}));const media=new SupabaseCaptainMedia({...config,storageKey:'sb_secret_fixture_only',mediaBucket:'existing'});const file=new File([bytes],'original.png',{type:'image/png'});const first=await media.upload('2',file),second=await media.upload('2',file);expect(first.url).not.toBe(second.url);expect(first.url).toContain('/teams/2/');expect(writes).toHaveLength(2);publicBucket=false;await expect(media.upload('2',file)).rejects.toMatchObject({code:'PUBLIC_MEDIA_BUCKET_UNAVAILABLE'});expect(writes).toHaveLength(2);});
 it('serves resolved images and verifies ownership before touching storage',async()=>{const bytes=await sharp({create:{width:10,height:7,channels:4,background:'red'}}).png().toBuffer();const upload=vi.fn(async()=>({id:'fixture-image',url:`${config.supabaseUrl}/storage/v1/object/public/fixture/new.png`}));const application=createApp(config,{}, {store,mailer,now:()=>clock,media:{upload,read:async()=>({bytes,type:'image/png'})}});const res=await application.request('/api/media/f7b98b59-32ca-4577-a3e5-84f7185b3e22');expect(res.headers.get('content-type')).toBe('image/png');expect(Buffer.from(await res.arrayBuffer())).toEqual(bytes);expect((await application.request('/api/media/aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa')).status).toBe(404);
  const send=async(id:string,kind:string,slot='')=>{const body=new FormData();body.set('ownerId',id);body.set('assetType',kind);body.set('slot',slot);body.set('file',new File([bytes],'photo.png',{type:'image/png'}));return application.request('/api/media/uploads',{method:'POST',headers:{origin:config.siteUrl,cookie:cookie()},body});};expect((await send('7','logo')).status).toBe(403);expect(upload).not.toHaveBeenCalled();expect((await send('2','logo')).status).toBe(201);expect((await send('2','player-photo','3')).status).toBe(201);expect(store.rows.get('2')!.player3_photo_url).toContain('new.png');expect(store.rows.get('7')!.logo_url).toContain('/api/media/');});
});
