import {createApiServices} from '../../src/services/apiAdapter';
import {afterEach,expect,it,vi} from 'vitest';
import {createApp} from '../../server/app';
const uid='00000000-0000-4000-8000-000000000001',claimId='60000000-0000-4000-8000-000000000001';
const config={supabaseUrl:'http://127.0.0.1:54321',publishableKey:'test',serviceKey:'test-service',siteUrl:'http://localhost:8888',secureCookies:false};
const app=createApp(config),json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}});
afterEach(()=>vi.unstubAllGlobals());
function transport(options:{signupExists?:boolean;signupFailure?:boolean;role?:string;rate?:boolean;claim?:unknown}={}){
 const calls:Array<{path:string;body:Record<string,unknown>}> = [];
 vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const path=new URL(String(input)).pathname;const body=init?.body?JSON.parse(String(init.body)):{};calls.push({path,body});
 if(path.endsWith('/rate_limit'))return json(options.rate??true);
 if(path==='/auth/v1/signup')return options.signupFailure?json({msg:'Synthetic infrastructure failure'},500):options.signupExists?json({msg:'User already registered',code:'user_already_exists'},422):json({user:{id:uid,email:'synthetic@example.test',aud:'authenticated',user_metadata:{},app_metadata:{}},session:null});
 if(path==='/auth/v1/user')return json({id:uid,email:'synthetic@example.test',aud:'authenticated',email_confirmed_at:'2020-01-01',user_metadata:{},app_metadata:{}});
 if(path==='/auth/v1/verify')return json({access_token:'test-access',refresh_token:'test-refresh',expires_in:3600,token_type:'bearer',user:{id:uid,email:'synthetic@example.test',aud:'authenticated',email_confirmed_at:'2020-01-01',user_metadata:{},app_metadata:{}}});
 if(path.endsWith('/admin_roles'))return json(options.role?{role:options.role}:null);
 if(path.endsWith('/legacy_claim'))return json(options.claim??{ok:true,expiresAt:'2030-01-01T00:30:00Z'});
 if(path==='/auth/v1/recover')return json({});
 return json(null);
 }));return calls;
}
const post=(path:string,data:unknown)=>app.request('/api'+path,{method:'POST',headers:{origin:config.siteUrl,'content-type':'application/json',cookie:'aevic-access=fixture'},body:JSON.stringify(data)});
it('activation uses real Auth signup without team draft, legacy password or identity assignment',async()=>{const calls=transport();const response=await post('/auth/legacy-activation',{email:'synthetic@example.test',password:'Secure1234'});expect(response.status).toBe(202);expect(response.headers.get('set-cookie')).toBeNull();const signup=calls.find(c=>c.path==='/auth/v1/signup')!;expect(signup.body.password).toBe('Secure1234');expect(signup.body.data??{}).toEqual({});expect(calls.some(c=>c.path.includes('legacy_claim')||c.path.includes('teams'))).toBe(false);});
it('activation is neutral for an existing Auth address',async()=>{transport({signupExists:true});const r=await post('/auth/legacy-activation',{email:'synthetic@example.test',password:'Secure1234'});expect(r.status).toBe(202);expect(await r.json()).toEqual({accepted:true});});
it('activation reports infrastructure failure without exposing upstream details',async()=>{transport({signupFailure:true});const r=await post('/auth/legacy-activation',{email:'synthetic@example.test',password:'Secure1234'});expect(r.status).toBe(503);expect(await r.json()).toMatchObject({code:'DATA_UNAVAILABLE'});});
it('activation rate limit stops signup before any mail call',async()=>{const calls=transport({rate:false});expect((await post('/auth/legacy-activation',{email:'synthetic@example.test',password:'Secure1234'})).status).toBe(429);expect(calls.some(c=>c.path==='/auth/v1/signup')).toBe(false);});
it('email confirmation reuses Auth token exchange and secure cookie architecture',async()=>{const calls=transport();const r=await post('/auth/email-verification/confirm',{token:'a'.repeat(43)});expect(r.status).toBe(204);expect(r.headers.get('set-cookie')).toContain('HttpOnly');expect(calls.find(c=>c.path==='/auth/v1/verify')?.body).toMatchObject({type:'signup',token_hash:'a'.repeat(43)});});
it('legacy claim request returns no record or account information',async()=>{transport();const r=await post('/me/legacy-claims',{sourceKey:'999'});expect(r.status).toBe(202);expect(await r.json()).toEqual({accepted:true});});
it('review issues a random challenge but sends only its digest to the caller-JWT RPC',async()=>{const calls=transport({role:'support-moderator'});const r=await post(`/admin/legacy-claims/${claimId}/review`,{decision:'approve',evidenceRef:uid,expectedVersion:1});expect(r.status).toBe(200);const data=await r.json();expect(data.code).toMatch(/^[A-Za-z0-9_-]{43}$/);const rpc=calls.find(c=>c.path.endsWith('/legacy_claim'))!;expect((rpc.body.payload as Record<string,unknown>).tokenHash).toMatch(/^[a-f0-9]{64}$/);expect(JSON.stringify(rpc.body)).not.toContain(data.code);});
it('result operator cannot review claims',async()=>{const calls=transport({role:'result-operator'});expect((await post(`/admin/legacy-claims/${claimId}/review`,{decision:'approve',evidenceRef:uid,expectedVersion:1})).status).toBe(403);expect(calls.some(c=>c.path.endsWith('/legacy_claim'))).toBe(false);});
it('redemption failures remain generic and never expose the submitted code',async()=>{const calls=transport({claim:{ok:false,code:'CLAIM_INVALID'}});const code='x'.repeat(43);const r=await post(`/me/legacy-claims/${claimId}/consume`,{code});expect(r.status).toBe(422);expect(await r.text()).not.toContain(code);expect(JSON.stringify(calls)).not.toContain(code);});
it('password recovery remains neutral and uses Auth rather than legacy hashes',async()=>{const calls=transport();expect((await post('/auth/password-reset',{email:'unknown@example.test'})).status).toBe(204);expect(calls.some(c=>c.path==='/auth/v1/recover')).toBe(true);expect(calls.some(c=>c.path.includes('teams'))).toBe(false);});
it('activation mutation rejects a cross-origin request before contacting Auth',async()=>{const calls=transport();const r=await app.request('/api/auth/legacy-activation',{method:'POST',headers:{origin:'https://attacker.example','content-type':'application/json'},body:JSON.stringify({email:'synthetic@example.test',password:'Secure1234'})});expect(r.status).toBe(403);expect(calls).toHaveLength(0);});

it('API adapter accepts the actual Hono activation and claim receipt contracts',async()=>{transport();const upstream=globalThis.fetch;vi.stubGlobal('fetch',vi.fn((input:RequestInfo|URL,init?:RequestInit)=>String(input).startsWith('/api/')?app.request(String(input),{...init,headers:{...init?.headers,origin:config.siteUrl,cookie:'aevic-access=fixture'}}):upstream(input,init)));const api=createApiServices('/api');await expect(api.legacyClaims.activate('synthetic@example.test','Secure1234')).resolves.toEqual({accepted:true});await expect(api.legacyClaims.request('1')).resolves.toEqual({accepted:true});});

it('public projections and Wrapped retain incomplete legacy history without exposing holding data',async()=>{
 vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>{const url=new URL(String(input));if(url.pathname.endsWith('/teams')){expect(url.searchParams.get('select')).toContain('legacy_history_incomplete');return json([{id:uid,name:'Synthetic legacy',slug:'synthetic-legacy',approval_status:'approved',legacy_history_incomplete:true}]);}return json([]);}));
 const response=await app.request('/api/public/context');expect(response.status).toBe(200);const data=await response.json();expect(data.teams[0].legacyHistoryIncomplete).toBe(true);expect(data.teamComparisonRecords[0].legacyHistoryIncomplete).toBe(true);expect(JSON.stringify(data)).not.toMatch(/captain_contact|password_hash/);const wrapped=await app.request('/api/teams/synthetic-legacy/wrapped?year=2026');expect(wrapped.status).toBe(200);expect(await wrapped.json()).toMatchObject({historyIncomplete:true,available:false});
});
