import {VerifyEmailPage} from '../src/pages/AuthLifecyclePages';
import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {expect,it,vi} from 'vitest';
import {services} from '../src/services';
import {AdminLegacyClaimsPage,LegacyActivationPage,LegacyClaimPage} from '../src/pages/LegacyClaimPages';
const uid='00000000-0000-4000-8000-000000000001';
it('activation sends a real service request and describes delivery truthfully',async()=>{const submit=vi.spyOn(services.legacyClaims,'activate').mockResolvedValue();render(<MemoryRouter><LegacyActivationPage/></MemoryRouter>);fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Yeni şifrə'),{target:{value:'Secure1234'}});fireEvent.click(screen.getByRole('button',{name:'Hesab üçün müraciət et'}));await waitFor(()=>expect(submit).toHaveBeenCalledWith('synthetic@example.test','Secure1234'));expect(await screen.findByRole('status')).toHaveTextContent('çatdırılmasını');expect(screen.getByLabelText('Yeni şifrə')).toHaveValue('');});
it('failed activation preserves input without claiming success',async()=>{vi.spyOn(services.legacyClaims,'activate').mockRejectedValue(new Error());render(<MemoryRouter><LegacyActivationPage/></MemoryRouter>);fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Yeni şifrə'),{target:{value:'Secure1234'}});fireEvent.click(screen.getByRole('button',{name:'Hesab üçün müraciət et'}));expect(await screen.findByRole('alert')).toHaveTextContent('tamamlanmadı');expect(screen.getByLabelText('Email')).toHaveValue('synthetic@example.test');expect(screen.queryByRole('status')).not.toBeInTheDocument();});
it('claim view does not invent player IDs or infer legacy captain role',async()=>{vi.spyOn(services.legacyClaims,'list').mockResolvedValue([]);vi.spyOn(services.legacyClaims,'roster').mockResolvedValue({teamId:uid,rosterNames:['First','Second','Third','Fourth','Fifth'],completed:false,historyIncomplete:true});render(<MemoryRouter><LegacyClaimPage/></MemoryRouter>);expect(await screen.findByLabelText('First — PUBG ID')).toHaveValue('');expect(screen.getByLabelText('First — rol')).toHaveValue('');expect(screen.getByText(/Statistikalar yalnız sistemdə qeydə alınmış/)).toBeInTheDocument();});
it('moderator approval requires explicit independent verification and uses the selected version',async()=>{vi.spyOn(services.legacyClaims,'holdings').mockResolvedValue([]);vi.spyOn(services.legacyClaims,'queue').mockResolvedValue([{id:uid,userId:uid,sourceKey:'1',status:'pending',version:2,createdAt:'2020-01-01',teamName:'Synthetic',claimed:false,applicantEmail:'synthetic@example.test'}]);const approve=vi.spyOn(services.legacyClaims,'review').mockResolvedValue({code:'x'.repeat(43),expiresAt:'2030-01-01'});render(<MemoryRouter><AdminLegacyClaimsPage/></MemoryRouter>);fireEvent.change(await screen.findByLabelText('Sahiblik sorğusu'),{target:{value:uid}});expect(screen.getByRole('button',{name:'Təsdiqlə və kod yarat'})).toBeDisabled();fireEvent.change(screen.getByLabelText('Müraciət edənin sübutu olan dəstək sorğusunun UUID-si'),{target:{value:uid}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Təsdiqlə və kod yarat'}));await waitFor(()=>expect(approve).toHaveBeenCalledWith(uid,'approve',uid,2));expect(await screen.findByText('x'.repeat(43))).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Kodu ekrandan sil'}));expect(screen.queryByText('x'.repeat(43))).not.toBeInTheDocument();});

it.each(['visitor','captain'] as const)('email activation offers the authorized next step for %s',async role=>{vi.spyOn(services.auth,'inspectEmailVerification').mockResolvedValue({state:'valid'});vi.spyOn(services.auth,'verifyEmail').mockResolvedValue();vi.spyOn(services.auth,'getSession').mockResolvedValue({role,user:{id:uid,firstName:'',lastName:'',email:'synthetic@example.test',role}});render(<MemoryRouter initialEntries={['/verify-email?token_hash=synthetic']}><VerifyEmailPage/></MemoryRouter>);expect(await screen.findByRole('link',{name:role==='visitor'?'Əvvəlki komandanı bağla':'Komanda panelini aç'})).toHaveAttribute('href',role==='visitor'?'/account/legacy-claim':'/team');});
