import { render, screen, within, fireEvent, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, expect, it, vi } from 'vitest';
import { PublicTeamFeatures } from '../src/components/profile/PublicTeamFeatures';
import { currentTeam } from './fixtures/platform-data';
import { services } from '../src/services';
import { clearQueryCache } from '../src/services/queryCache';
import { deriveWrappedSummary, yearPeriod } from '../src/utils/wrapped';
import { drawPublicTeamIdentityCard, teamIdentityCardBlob, loadCardImage } from '../src/utils/teamIdentityCard';
vi.mock('../src/utils/teamIdentityCard', () => ({ loadCardImage: vi.fn().mockResolvedValue(undefined), drawPublicTeamIdentityCard: vi.fn(), teamIdentityCardBlob: vi.fn().mockResolvedValue(new Blob(['png'], { type: 'image/png' })) }));
beforeEach(() => { clearQueryCache('all'); vi.mocked(loadCardImage).mockResolvedValue(undefined); vi.mocked(teamIdentityCardBlob).mockResolvedValue(new Blob(['png'], { type: 'image/png' })); });
it('uses seasonal facts, supplied phone, current identity and clipboard fallback', async () => {
 const summary = { ...deriveWrappedSummary({ team: currentTeam, period: yearPeriod(2026), matches: [] }), matches: 17, wwcd: 4, kills: 123 };
 vi.spyOn(services.wrapped, 'forTeam').mockResolvedValue(summary);
 const copy = vi.fn().mockResolvedValue(undefined);
 Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: copy } });
 Object.defineProperty(navigator, 'share', { configurable: true, value: undefined });
 const view = render(<MemoryRouter><PublicTeamFeatures team={currentTeam} /></MemoryRouter>);
 const wrapped = screen.getByRole('region', { name: /mövsümünün rəsmi nəticələri/ });
 expect(await within(wrapped).findByText('123')).toBeInTheDocument();
 expect(within(wrapped).getByText('17')).toBeInTheDocument();
 expect(within(wrapped).getByText('4')).toBeInTheDocument();
 expect(within(wrapped).getByRole('link', { name: 'İcmala bax' })).toHaveAttribute('href', expect.stringMatching(/\/teams\/caspian-wolves\/wrapped\/\d{4}$/));
 expect(view.container.querySelector('.public-team-wrapped img')).toHaveAttribute('src', expect.stringContaining('team-wrapped-phone-1024.webp'));
 await waitFor(() => expect(drawPublicTeamIdentityCard).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ teamName: currentTeam.name, teamTag: currentTeam.tag }), expect.anything()));
 fireEvent.click(screen.getByRole('button', { name: 'Paylaş', exact: true }));
 expect(await screen.findByRole('status')).toHaveTextContent('Profil keçidi kopyalandı');
 expect(copy).toHaveBeenCalledWith(expect.stringContaining('/teams/caspian-wolves'));
 expect(teamIdentityCardBlob).toHaveBeenCalled();
});
