import { Hono } from 'hono';
import { z } from 'zod';
import type { Env,ApiContext } from '../types';
import { authenticate,requireAdmin,requireTeam } from '../auth/session';
import { body,id,paramId,text,socialLinks,pagination } from '../validation/input';
import { dbError,ServiceError } from '../errors';
import { Repository } from '../services/data';
import { organizations,achievements } from '../services/identity';
const app=new Hono<Env>();
const r=(c:ApiContext)=>new Repository(c.get('db'));
async function run(c:ApiContext,action:string,payload:unknown){await authenticate(c);const{data,error}=await c.get('db').rpc('identity_command',{action,payload,idempotency_key:c.req.header('Idempotency-Key')??null});dbError(error);return data as Record<string,unknown>;}
const notFound=()=>{throw new ServiceError(404,'NOT_FOUND');};
async function getOrg(c:ApiContext,key:string){return(await organizations(r(c))).find(o=>o.id===key||o.slug===key)??notFound();}
app.get('/organizations',async c=>c.json(await organizations(r(c))));
app.get('/organizations/:slug',async c=>c.json(await getOrg(c,text(1,110).parse(c.req.param('slug')))));
app.post('/organizations',async c=>{const out=await run(c,'org.create',await body(c,z.object({name:text(2,100),shortName:text(1,20),country:text(0,80),description:text(0,3000).default('')})));return c.json(await getOrg(c,String(out.id)),201);});
app.put('/organizations/:id/social-links',async c=>{const organizationId=paramId(c);await run(c,'org.social',{organizationId,socialLinks:await body(c,socialLinks)});return c.json(await getOrg(c,organizationId));});
app.post('/organizations/:id/teams',async c=>{const organizationId=paramId(c);await run(c,'org.link',{organizationId,...await body(c,z.object({teamId:id,gameKey:z.literal('pubg-mobile')}))});return c.json(await getOrg(c,organizationId));});
app.delete('/organizations/:id/teams/:teamId',async c=>{const organizationId=paramId(c);await authenticate(c);const own=(await r(c).rows('organization_members')).some(m=>m.organization_id===organizationId&&m.user_id===c.get('user')!.id&&['OWNER','MANAGER'].includes(String(m.role)));await run(c,own?'org.remove-team':'org.unlink',{organizationId,teamId:paramId(c,'teamId')});return c.json(await getOrg(c,organizationId));});
app.get('/organizations/:id/members',async c=>{await authenticate(c);return c.json((await r(c).rows('organization_members')).filter(m=>m.organization_id===paramId(c)).map(m=>({id:m.id,userId:m.user_id,displayName:m.user_id===c.get('user')!.id?'Siz':m.role,role:m.role,joinedAt:m.created_at,status:m.status})));});
async function orgInvites(c:ApiContext){const repo=r(c),[rows,orgs]=await Promise.all([repo.rows('organization_invitations'),organizations(repo)]);return rows.map(i=>({id:String(i.id),type:i.team_id?'ORGANIZATION_TEAM':'ORGANIZATION_MEMBER',entityId:i.organization_id,entityName:orgs.find(o=>o.id===i.organization_id)?.name??'',recipientLabel:i.recipient_email??i.team_id,role:i.role,status:i.status==='PENDING'&&Date.parse(String(i.expires_at))<=Date.now()?'EXPIRED':i.status,createdAt:i.created_at,expiresAt:i.expires_at,respondedAt:i.responded_at}));}
app.get('/organizations/:id/invitations',async c=>{await authenticate(c);const items=(await orgInvites(c)).filter(i=>i.entityId===paramId(c));const{offset,limit}=pagination(c);return c.json({items:items.slice(offset,offset+limit),hasMore:items.length>offset+limit,nextCursor:items.length>offset+limit?String(offset+limit):undefined});});
app.post('/organizations/:id/member-invitations',async c=>{const out=await run(c,'org.invite-member',{organizationId:paramId(c),...await body(c,z.object({recipient:z.email(),role:z.enum(['MANAGER','MEMBER'])}))});return c.json((await orgInvites(c)).find(i=>i.id===out.id)??notFound(),201);});
app.post('/organizations/:id/team-invitations',async c=>{const out=await run(c,'org.invite-team',{organizationId:paramId(c),...await body(c,z.object({teamId:id}))});return c.json((await orgInvites(c)).find(i=>i.id===out.id)??notFound(),201);});
app.post('/organization-invitations/:id/response',async c=>{const invitationId=paramId(c);await run(c,'org.respond',{id:invitationId,...await body(c,z.object({response:z.enum(['ACCEPTED','REJECTED'])}))});return c.json((await orgInvites(c)).find(i=>i.id===invitationId)??notFound());});
app.post('/organizations/:id/ownership',async c=>{const organizationId=paramId(c);await run(c,'org.transfer',{organizationId,...await body(c,z.object({memberId:id,confirmation:text(2,100)}))});return c.json((await r(c).rows('organization_members')).filter(m=>m.organization_id===organizationId).map(m=>({id:m.id,userId:m.user_id,displayName:m.role,role:m.role,joinedAt:m.created_at,status:m.status})));});
app.get('/teams/:id/achievements',async c=>{await authenticate(c,false);return c.json(await achievements(r(c),paramId(c)));});
app.get('/teams/:id/legacy',async c=>c.json((await r(c).profile(paramId(c))).legacy));
app.get('/teams/:id/achievements/featured',async c=>c.json((await achievements(r(c),paramId(c))).filter(a=>a.featured).sort((a,b)=>a.displayOrder-b.displayOrder)));
app.put('/teams/:id/achievements/featured',async c=>{const teamId=paramId(c);await run(c,'badges.featured',{teamId,ids:(await body(c,z.object({achievementIds:z.array(text(1,100)).max(3)}))).achievementIds});return c.json((await achievements(r(c),teamId)).filter(a=>a.featured).sort((a,b)=>a.displayOrder-b.displayOrder));});
async function verifications(c:ApiContext){const repo=r(c),[rows,teams,orgs]=await Promise.all([repo.rows('verification_requests'),repo.teams(),organizations(repo)]);return rows.map(v=>({id:String(v.id),entityId:v.team_id??v.organization_id,entityType:v.team_id?'TEAM':'ORGANIZATION',entityName:teams.find(t=>t.id===v.team_id)?.name??orgs.find(o=>o.id===v.organization_id)?.name??'',representativeName:v.representative_name,officialSocials:v.official_socials,evidenceNames:[],notes:v.notes,status:v.status,safeReason:v.safe_reason,submittedAt:v.created_at,reviewedAt:v.reviewed_at,reviewedBy:v.reviewed_by}));}
app.get('/verifications/entity',async c=>{await authenticate(c);const entityId=id.parse(c.req.query('entityId'));return c.json((await verifications(c)).filter(v=>v.entityId===entityId).sort((a,b)=>String(b.submittedAt).localeCompare(String(a.submittedAt)))[0]??notFound());});
app.post('/verifications',async c=>{const input=await body(c,z.object({entityId:id,entityType:z.enum(['TEAM','ORGANIZATION']),representativeName:text(2,100),officialSocials:socialLinks,notes:text(20,4000)}));const out=await run(c,'verification.apply',{...input,[input.entityType==='TEAM'?'teamId':'organizationId']:input.entityId});return c.json((await verifications(c)).find(v=>v.id===out.id)??notFound(),201);});
app.get('/admin/verifications',async c=>{await requireAdmin(c,['support-moderator']);const status=c.req.query('status');const items=(await verifications(c)).filter(v=>!status||v.status===status),{offset,limit}=pagination(c);return c.json({items:items.slice(offset,offset+limit),hasMore:items.length>offset+limit,nextCursor:items.length>offset+limit?String(offset+limit):undefined});});
app.get('/admin/verifications/:id',async c=>{await requireAdmin(c,['support-moderator']);return c.json((await verifications(c)).find(v=>v.id===paramId(c))??notFound());});
app.patch('/admin/verifications/:id',async c=>{const verificationId=paramId(c);await run(c,'verification.review',{id:verificationId,...await body(c,z.object({status:z.enum(['APPROVED','REJECTED','REVOKED']),reason:text(10,4000),expectedStatus:z.enum(['PENDING','APPROVED','REJECTED','REVOKED'])}))});return c.json((await verifications(c)).find(v=>v.id===verificationId)??notFound());});
app.post('/players/:id/claims',async c=>{const playerId=paramId(c);const input=await body(c,z.object({verificationMethod:z.enum(['ACCOUNT_MATCH','PUBG_IDENTITY','ADMIN_REVIEW'])}));const out=await run(c,'player.claim',{playerId,method:input.verificationMethod});const claim=(await r(c).rows('player_claims')).find(p=>p.id===out.id)??notFound();return c.json({id:claim.id,playerId,claimantUserId:claim.user_id,status:claim.status,verificationMethod:claim.method,createdAt:claim.created_at});});
app.post('/me/deletion',async c=>c.json(await run(c,'account.deletion',{})));
export default app;
