import { Hono } from 'hono';
import { z } from 'zod';
import type { Env,ApiContext } from '../types';
import { authenticate,requireAdmin,requireTeam } from '../auth/session';
import { command,client } from '../db';
import { Repository,summary,roundResult } from '../services/data';
import { body,paramId,id,text,profileInput,socialLinks,resultInput,memberRole,pagination } from '../validation/input';
import { dbError,ServiceError } from '../errors';
import { sessionView } from './auth';
const app=new Hono<Env>();
const repo=(c:ApiContext)=>new Repository(c.get('db'));
const idem=(c:ApiContext)=>c.req.header('Idempotency-Key');
async function run(c:ApiContext,action:string,payload:unknown){await authenticate(c);return command(c.get('db'),action,payload,idem(c));}
const getItem=<T extends {id:string}>(items:T[],id:string)=>{const item=items.find(i=>i.id===id);if(!item)throw new ServiceError(404,'NOT_FOUND');return item;};
function page<T>(c:ApiContext,items:T[]){const{offset,limit}=pagination(c);return{items:items.slice(offset,offset+limit),hasMore:items.length>offset+limit,nextCursor:items.length>offset+limit?String(offset+limit):undefined,total:items.length};}
app.get('/me/context',async c=>{const tid=await requireTeam(c);const snapshot=await repo(c).teamSnapshot(tid);const member=(await repo(c).rows('team_members')).find(m=>m.team_id===tid&&m.role==='OWNER');if(member?.user_id===c.get('user')!.id)snapshot.currentTeam.captain=(await sessionView(c)).user as typeof snapshot.currentTeam.captain;return c.json(snapshot);});
app.get('/me/team',async c=>c.json(await repoAfterTeam(c)));
async function repoAfterTeam(c:ApiContext){const tid=await requireTeam(c);return repo(c).team(tid,true);}
app.get('/teams',async c=>{await requireAdmin(c);return c.json(await repo(c).teams(true));});
app.patch('/teams/:id',async c=>{const teamId=paramId(c);await run(c,'team.update',{teamId,...await body(c,profileInput)});return c.json(await repo(c).team(teamId,true));});
app.put('/teams/:id/social-links',async c=>{const teamId=paramId(c);await run(c,'team.social',{teamId,links:await body(c,socialLinks)});return c.json(await repo(c).team(teamId,true));});
app.post('/tournaments/:id/entries',async c=>{const tournamentId=paramId(c);const input=await body(c,z.object({teamId:id}));return c.json(await run(c,'tournament.join',{...input,tournamentId}),201);});
app.post('/tournaments/:id/check-in',async c=>c.json(await run(c,'checkin',{tournamentId:paramId(c)})));
app.post('/tournaments/:id/withdraw',async c=>{await run(c,'withdraw',{tournamentId:paramId(c),...await body(c,z.object({reason:text(0,1000).optional()}))});return c.body(null,204);});
app.get('/team/tournaments/:tournamentId/rounds/:roundId/room',async c=>c.json(await run(c,'room',{tournamentId:paramId(c,'tournamentId'),id:paramId(c,'roundId')})));
app.get('/me/notifications',async c=>{await authenticate(c);const items=await repo(c).notifications();return c.json(c.req.query('page')==='true'?page(c,items):items);});
app.get('/me/messages',async c=>{await requireTeam(c);return c.json(await repo(c).messages());});
app.put('/me/notifications/read-all',async c=>{await run(c,'notification.read-all',{});return c.body(null,204);});
app.put('/me/notifications/:id/read',async c=>{await run(c,'notification.read',{id:paramId(c)});return c.body(null,204);});
app.get('/me/notification-preferences',async c=>{await authenticate(c);const rows=await repo(c).rows('notification_preferences');const p=rows.find(r=>r.user_id===c.get('user')!.id);return c.json(p?{channels:p.channels,events:p.events}:{channels:{'in-app':true,email:false,push:false},events:{}});});
app.put('/me/notification-preferences',async c=>{const p=await body(c,z.object({channels:z.object({'in-app':z.boolean(),email:z.boolean(),push:z.boolean()}),events:z.record(z.string().max(80),z.boolean())}));await run(c,'notification.preferences',p);return c.json(p);});
const disputeInput=z.object({teamId:id,tournamentId:id,matchId:id,issueType:z.enum(['placement','kills','penalty','missing-result','other']),description:text(20,6000),evidenceIds:z.array(id).max(5).default([])});
app.get('/disputes',async c=>{await authenticate(c);const teamId=c.req.query('teamId');if(teamId)id.parse(teamId);return c.json((await repo(c).disputes()).filter(r=>!teamId||r.teamId===teamId));});
app.get('/disputes/:id',async c=>{await authenticate(c);return c.json(getItem(await repo(c).disputes(),paramId(c)));});
app.post('/disputes',async c=>{const result=await run(c,'dispute.submit',await body(c,disputeInput));return c.json(getItem(await repo(c).disputes(),String(result.id)),201);});
app.get('/roster-requests',async c=>{await authenticate(c);const teamId=c.req.query('teamId');if(teamId)id.parse(teamId);return c.json((await repo(c).rosterRequests()).filter(r=>!teamId||r.teamId===teamId));});
app.get('/roster-requests/:id',async c=>{await authenticate(c);return c.json(getItem(await repo(c).rosterRequests(),paramId(c)));});
app.post('/roster-requests',async c=>{const input=await body(c,z.object({teamId:id,tournamentId:id.optional(),outgoing:z.object({id}),incoming:z.object({ign:text(2,40),uid:z.string().regex(/^\d{5,20}$/),role:z.enum(['captain','starter','substitute'])}),reason:text(10,3000)}));const result=await run(c,'roster.submit',input);return c.json(getItem(await repo(c).rosterRequests(),String(result.id)),201);});
app.get('/teams/:id/authority',async c=>{await requireTeam(c,paramId(c));return c.json(await authority(c,paramId(c)));});
async function authority(c:ApiContext,tid:string){const rows=await repo(c).rows('team_members');return rows.filter(m=>m.team_id===tid).map(m=>({id:m.id,userId:m.user_id,displayName:m.user_id===c.get('user')?.id?'Siz':String(m.role),role:m.role,joinedAt:m.created_at,status:m.status,permissions:m.role==='OWNER'?['team.manage','team.invite','team.transfer','team.archive']:['OWNER','CAPTAIN'].includes(String(m.role))?['team.invite']:[]}));}
async function invitations(c:ApiContext){const r=repo(c),[rows,teams]=await Promise.all([r.rows('team_invitations'),r.teams()]);return rows.map(v=>({id:String(v.id),type:'TEAM_MEMBER',entityId:v.team_id,entityName:teams.find(t=>t.id===v.team_id)?.name??'',recipientLabel:v.recipient_email,role:v.role,status:v.status==='PENDING'&&Date.parse(String(v.expires_at))<=Date.now()?'EXPIRED':v.status,createdAt:v.created_at,expiresAt:v.expires_at,respondedAt:v.responded_at}));}
app.get('/team-invitations',async c=>{await authenticate(c);const teamId=c.req.query('teamId');if(teamId)id.parse(teamId);return c.json(page(c,(await invitations(c)).filter(i=>!teamId||i.entityId===teamId)));});
app.post('/teams/:id/invitations',async c=>{const result=await run(c,'invitation.create',{teamId:paramId(c),...await body(c,z.object({recipient:z.email(),role:memberRole}))});return c.json(getItem(await invitations(c),String(result.id)),201);});
app.post('/teams/:teamId/invitations/:id/cancellation',async c=>{const invitationId=paramId(c);await run(c,'invitation.cancel',{teamId:paramId(c,'teamId'),id:invitationId});return c.json(getItem(await invitations(c),invitationId));});
app.post('/team-invitations/:id/response',async c=>{const invitationId=paramId(c);await run(c,'invitation.respond',{id:invitationId,...await body(c,z.object({response:z.enum(['ACCEPTED','REJECTED'])}))});return c.json(getItem(await invitations(c),invitationId));});
app.post('/teams/:id/ownership',async c=>{const teamId=paramId(c);await run(c,'team.transfer',{teamId,...await body(c,z.object({memberId:id,confirmation:text(2,60)}))});return c.json(await authority(c,teamId));});
app.delete('/teams/:teamId/authority/:id',async c=>{await run(c,'team.member-remove',{teamId:paramId(c,'teamId'),id:paramId(c),...await body(c,z.object({reason:text(10,1000)}))});return c.body(null,204);});
app.post('/teams/:id/leave',async c=>{await run(c,'team.leave',{teamId:paramId(c)});return c.body(null,204);});
app.post('/teams/:id/archive',async c=>{const tid=paramId(c);await requireTeam(c,tid);const team=await repo(c).team(tid,true);await run(c,'team.archive',{teamId:tid,...await body(c,z.object({reason:text(10,1000),confirmation:text(2,60)}))});return c.json(team);});
app.get('/me/follows',async c=>{await authenticate(c);return c.json((await repo(c).rows('follows')).map(r=>({entityType:'TEAM',entityId:r.team_id,following:true,source:'backend'})));});
app.get('/me/follows/status',async c=>{await authenticate(c);const entityId=id.parse(c.req.query('entityId'));return c.json({entityType:'TEAM',entityId,following:(await repo(c).rows('follows')).some(r=>r.team_id===entityId),source:'backend'});});
app.put('/me/follows',async c=>{const input=await body(c,z.object({entityType:z.literal('TEAM'),entityId:id,following:z.boolean()}));await run(c,'follow',{...input,id:input.entityId});return c.json({...input,source:'backend'});});
async function tickets(c:ApiContext){const r=repo(c),[rows,replies]=await Promise.all([r.rows('support_tickets'),r.rows('support_replies')]);return rows.map(t=>({id:String(t.id),category:t.category,subject:t.subject,description:t.description,status:t.status,createdAt:t.created_at,updatedAt:t.updated_at,messages:replies.filter(r=>r.ticket_id===t.id).sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))).map(r=>({id:r.id,author:r.author,body:r.body,createdAt:r.created_at}))})).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));}
app.get('/me/support/tickets',async c=>{await authenticate(c);const items=await tickets(c);return c.json(c.req.query('page')==='true'?page(c,items):items);});
app.get('/me/support/tickets/:id',async c=>{await authenticate(c);return c.json(getItem(await tickets(c),paramId(c)));});
app.post('/me/support/tickets',async c=>{const result=await run(c,'support.create',await body(c,z.object({category:z.enum(['account','registration','roster','tournament','results','technical','other']),subject:text(3,200),description:text(10,6000)})));return c.json(getItem(await tickets(c),String(result.id)),201);});
app.post('/me/support/tickets/:id/messages',async c=>{const ticketId=paramId(c);await run(c,'support.reply',{id:ticketId,...await body(c,z.object({body:text(1,6000)}))});return c.json(getItem(await tickets(c),ticketId));});
app.get('/admin/support/tickets',async c=>{await requireAdmin(c,['support-moderator']);const status=c.req.query('status');return c.json(page(c,(await tickets(c)).filter(t=>!status||t.status===status)));});
app.patch('/admin/support/tickets/:id/status',async c=>{await requireAdmin(c,['support-moderator']);const ticketId=paramId(c);await run(c,'support.status',{id:ticketId,...await body(c,z.object({status:z.enum(['open','waiting-for-user','under-review','resolved','closed']),reason:text(0,1000).optional()}))});return c.json(getItem(await tickets(c),ticketId));});
app.get('/admin/context',async c=>{
 await requireAdmin(c);const r=repo(c);const [teams,tournaments,entries,messages,schedule,checks]=await Promise.all([r.teams(true),r.tournaments(),r.rows('tournament_registrations'),r.messages(),r.schedule(),r.rows('check_ins')]);
 // The legacy admin contract carries currentTeam even though administrators need not own a team.
 return c.json({currentTeam:teams[0]??null,teams,tournaments,slots:entries.filter(e=>e.slot_number).map(e=>({number:e.slot_number,tournamentId:e.tournament_id,teamId:e.team_id,state:'occupied'})),adminMessages:messages,blacklist:[],organizations:[],teamAchievements:[],matchSchedule:schedule,checkIns:checks.map(e=>{const t=tournaments.find(t=>t.id===e.tournament_id);return{teamId:e.team_id,tournamentId:e.tournament_id,status:'checked-in',opensAt:t?.checkInOpensAt,closesAt:t?.checkInClosesAt,checkedInAt:e.checked_in_at};})});
});
app.patch('/admin/teams/:id/approval',async c=>{const teamId=paramId(c);await run(c,'team.approval',{teamId,...await body(c,z.object({status:z.enum(['pending','approved','rejected','banned']),reason:text(0,1000).optional()}))});return c.json(await repo(c).team(teamId,true));});
app.patch('/admin/tournaments/:id/entries/:teamId',async c=>{await run(c,'registration.review',{tournamentId:paramId(c),teamId:paramId(c,'teamId'),...await body(c,z.object({status:z.enum(['confirmed','rejected']),reason:text(0,1000).optional()}))});return c.body(null,204);});
app.patch('/admin/disputes/:id',async c=>{const disputeId=paramId(c);await run(c,'dispute.review',{id:disputeId,...await body(c,z.object({status:z.enum(['resolved','rejected']),note:text(0,4000).optional()}))});return c.json(getItem(await repo(c).disputes(),disputeId));});
app.patch('/admin/roster-requests/:id',async c=>{const requestId=paramId(c);await run(c,'roster.review',{id:requestId,...await body(c,z.object({status:z.enum(['approved','rejected']),note:text(0,4000).optional()}))});return c.json(getItem(await repo(c).rosterRequests(),requestId));});
app.post('/admin/messages',async c=>{const input=await body(c,z.object({title:text(1,200),body:text(1,10000),severity:z.enum(['info','success','warning','critical']),audience:z.literal('all')}));await run(c,'message.send',input);return c.body(null,204);});
app.get('/admin/results',async c=>{await requireAdmin(c,['result-operator']);const roundId=id.parse(c.req.query('roundId'));return c.json((await repo(c).rows('team_match_results')).filter(r=>r.match_id===roundId).map(roundResult));});
app.post('/admin/results',async c=>{const input=await body(c,resultInput);return c.json(roundResult(await run(c,'result.save',input)),201);});
app.get('/admin/results/:id/versions',async c=>{await requireAdmin(c,['result-operator']);const resultId=paramId(c);return c.json((await repo(c).rows('result_versions')).filter(v=>v.result_id===resultId).map(v=>({id:v.id,resultId:v.result_id,version:v.version,createdAt:v.created_at,createdBy:v.created_by,reason:v.reason,dataSnapshot:roundResult(v.data_snapshot as Record<string,unknown>)})));});
app.post('/admin/results/:id/corrections',async c=>{const resultId=paramId(c),input=await body(c,z.object({result:resultInput,reason:text(10,3000),expectedVersion:z.number().int().min(1)}));const row=await run(c,'result.correct',{...input.result,id:resultId,reason:input.reason,expectedVersion:input.expectedVersion});return c.json({id:row.id,resultId,version:row.version,createdAt:row.updated_at,createdBy:c.get('user')!.id,reason:input.reason,dataSnapshot:roundResult(row)});});
app.put('/admin/matches/:id/room',async c=>{await run(c,'room.save',{id:paramId(c),...await body(c,z.object({roomId:text(1,100),password:text(1,200)}))});return c.body(null,204);});
for(const action of ['cancellation','archive'] as const)app.post(`/admin/tournaments/:id/${action}`,async c=>{const tournamentId=paramId(c);await run(c,action==='archive'?'tournament.archive':'tournament.cancel',{tournamentId,...(action==='cancellation'?await body(c,z.object({reason:text(10,1000)})):{})});return c.json(await repo(c).tournament(tournamentId));});
app.get('/admin/audit',async c=>{await requireAdmin(c);return c.json((await repo(c).rows('audit_events')).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(r=>({id:r.id,action:r.action,entityType:r.entity_type,entityId:r.entity_id,actorName:r.actor_id,actorRole:r.metadata && typeof r.metadata==='object' && 'actorRole' in r.metadata?r.metadata.actorRole:'admin',createdAt:r.created_at,metadata:r.metadata})));});
app.get('/admin/users',async c=>{await requireAdmin(c,['super-admin']);const rows=await repo(c).rows('admin_roles');const admin=client(c.get('config'),undefined,true);return c.json(await Promise.all(rows.map(async r=>{const {data,error}=await admin.auth.admin.getUserById(String(r.user_id));dbError(error);return{id:r.user_id,name:data.user?.user_metadata?.firstName??r.user_id,email:data.user?.email??'',role:r.role,twoFactorEnabled:data.user?.factors?.some(f=>f.status==='verified')??false,status:'active'};})));});
app.get('/admin/check-ins/missed',async c=>{await requireAdmin(c,['tournament-manager']);const tournamentId=c.req.query('tournamentId');if(tournamentId)id.parse(tournamentId);const r=repo(c),[entries,checks,tournaments,teams]=await Promise.all([r.rows('tournament_registrations'),r.rows('check_ins'),r.tournaments(),r.teams()]);return c.json(page(c,entries.flatMap(e=>{const t=tournaments.find(t=>t.id===e.tournament_id);if(!t||(tournamentId&&t.id!==tournamentId)||Date.parse(t.checkInClosesAt)>Date.now()||e.status!=='confirmed'||checks.some(k=>k.team_id===e.team_id&&k.tournament_id===e.tournament_id))return[];return[{id:e.id,tournamentId:t.id,tournamentName:t.name,teamId:e.team_id,teamName:teams.find(t=>t.id===e.team_id)?.name??'',missedAt:t.checkInClosesAt,consequence:'Check-in tamamlanmayıb',appealAllowed:false}];})));});
const tournamentInput=z.object({name:text(2,120),shortName:text(2,50),description:text(0,3000),startsAt:z.iso.datetime(),endsAt:z.iso.datetime(),registrationOpensAt:z.iso.datetime(),registrationDeadline:z.iso.datetime(),checkInOpensAt:z.iso.datetime(),checkInClosesAt:z.iso.datetime(),maxSlots:z.number().int().min(1).max(100),rules:z.array(text(1,500)).max(50),rounds:z.array(z.object({map:z.enum(['Erangel','Miramar','Rondo']),startsAt:z.iso.datetime()})).min(1).max(20)});
app.post('/admin/tournaments',async c=>{const input=await body(c,tournamentInput);const result=await run(c,'tournament.create',input);return c.json(await repo(c).tournament(String(result.id)),201);});
app.post('/admin/matches/:id/publication',async c=>{await run(c,'match.publish',{id:paramId(c)});return c.body(null,204);});
app.get('/admin/tournaments/:id/entries',async c=>{await requireAdmin(c,['tournament-manager','result-operator']);return c.json((await repo(c).rows('tournament_registrations')).filter(r=>r.tournament_id===paramId(c)).map(r=>({id:r.id,teamId:r.team_id,status:r.status,slotNumber:r.slot_number})));});
export default app;
