import { competitionNow } from '../../services';
import { tournamentAcceptsRegistration } from '../../utils/tournamentTime';
import type { CheckIn, MatchScheduleItem, NextAction, RoomCredentials, Team, TeamAnnouncement, Tournament } from '../../types/domain';

export function deriveNextAction(input: { now?: Date; team: Team; tournament?: Tournament; nextMatch?: MatchScheduleItem; announcement?: TeamAnnouncement; checkIn?: CheckIn; room?: Pick<RoomCredentials, 'roundId' | 'status' | 'releaseAt'> }): NextAction {
  const now = (input.now ?? competitionNow()).getTime();
  const { team, tournament, nextMatch, announcement, checkIn, room } = input;
  if (!team.profileComplete) return { kind: 'blocking', eyebrow: 'NÖVBƏTİ ADDIM', title: 'Komanda profilini tamamlayın', body: 'Turnir qeydiyyatından əvvəl tələb olunan komanda məlumatlarını tamamlayın.', href: '/team/settings', actionLabel: 'Profili tamamla' };
  if (team.approvalStatus === 'pending') return { kind: 'registration', eyebrow: 'QEYDİYYAT', title: 'Yoxlama mərhələsindədir', body: 'Komanda təqdim edilib. Təsdiq qərarı gəldikdə status burada yenilənəcək.' };
  if (team.approvalStatus === 'rejected' || team.approvalStatus === 'banned') return { kind: 'blocking', eyebrow: 'DİQQƏT TƏLƏB EDİR', title: team.approvalStatus === 'banned' ? 'Komanda yarışlara buraxılmır' : 'Qeydiyyata düzəliş lazımdır', body: team.rejectionReason ?? 'Ətraflı məlumat üçün komanda mesajlarını yoxlayın.', href: '/team/messages', actionLabel: 'Mesajları aç' };
  if (team.roster.filter((player) => player.role !== 'substitute').length < 4) return { kind: 'roster', eyebrow: 'HEYƏT', title: 'Əsas heyəti tamamlayın', body: 'Turnir əməliyyatları üçün kapitan daxil olmaqla ən azı dörd aktiv oyunçu tələb olunur.', href: '/team/roster', actionLabel: 'Heyəti idarə et' };
  if (nextMatch && checkIn?.tournamentId === nextMatch.tournamentId && checkIn.status === 'open' && now >= Date.parse(checkIn.opensAt) && now <= Date.parse(checkIn.closesAt)) return { kind: 'check-in', eyebrow: 'İNDİ ETMƏLİSİNİZ', title: 'Check-in edin', body: `Pəncərə ${new Date(checkIn.closesAt).toLocaleTimeString('az-AZ', { hour: '2-digit', minute: '2-digit' })}-dək açıqdır. Sonra ${nextMatch.map} · Raund ${nextMatch.round} başlayır.`, href: `/team/tournaments/${nextMatch.tournamentId}`, actionLabel: 'Check-in et', startsAt: nextMatch.startsAt };
  if (nextMatch && room?.status === 'released' && room.roundId === nextMatch.id && now >= Date.parse(room.releaseAt)) return { kind: 'room', eyebrow: 'OTAQ HAZIRDIR', title: `${nextMatch.map} · Raund ${nextMatch.round}`, body: 'Otaq ID-si və şifrə uyğun komanda hesabı üçün yayımlanıb.', href: `/team/tournaments/${nextMatch.tournamentId}#room`, actionLabel: 'Otaq məlumatlarını aç', startsAt: nextMatch.startsAt };
  if (nextMatch) return { kind: 'match', eyebrow: 'NÖVBƏTİ MATÇ', title: `${nextMatch.map} · Raund ${nextMatch.round}`, body: `${nextMatch.lobby} · ${new Date(nextMatch.startsAt).toLocaleString('az-AZ', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}`, href: `/team/tournaments/${nextMatch.tournamentId}`, actionLabel: 'Matç detalı', startsAt: nextMatch.startsAt };
  if (tournament && tournamentAcceptsRegistration(tournament, now)) return { kind: 'registration', eyebrow: 'AÇIQ TURNİR', title: tournament.name, body: `${Math.max(0, tournament.maxSlots - tournament.usedSlots)} public slot qalır. Uyğunluq server tərəfindən təsdiqlənməlidir.`, href: `/team/tournaments/${tournament.id}`, actionLabel: 'Uyğunluğu yoxla' };
  if (announcement) return { kind: 'announcement', eyebrow: 'VACİB ELAN', title: announcement.title, body: announcement.body, href: announcement.actionHref, actionLabel: announcement.actionLabel };
  return { kind: 'ready', eyebrow: 'HAZIRSINIZ', title: 'Hazırda əməliyyat tələb olunmur', body: 'Yeni turnir, check-in və ya roster vəziyyəti yarandıqda burada görünəcək.' };
}
