import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
for(const path of ['/regulations','/contact','/privacy','/terms','/support'])test(`public information acceptance ${path}`,async({page})=>{
 await page.goto(path);const heading=page.locator('main h1');await expect(heading).toBeVisible();const title=await heading.textContent();expect(title).not.toMatch(/tapılmadı|tamamlaya bilmədi/);expect((await page.locator('main').innerText()).length).toBeGreaterThan(150);
 for(const width of [320,375,390,768,1024,1440,1920]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),`${path} ${width}`).toBeLessThanOrEqual(1);}
 await page.setViewportSize({width:390,height:844});await page.evaluate(async()=>{document.documentElement.style.fontSize='200%';await document.fonts.ready;});expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);await page.reload();await expect(heading).toHaveText(title!);
 if(path==='/support'){await page.evaluate(readFileSync(process.env.AEVIC_AXE_SOURCE||'/tmp/aevic-quality-tools/node_modules/axe-core/axe.min.js','utf8'));const scan=await page.evaluate(async()=>await(window as any).axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','best-practice']}}));expect(scan.violations).toEqual([]);const search=page.getByRole('textbox',{name:'Dəstək mövzularında axtar'});await search.fill('zzzz-not-found');await expect(page.getByText('Uyğun cavab tapılmadı')).toBeVisible();await search.fill('');const first=page.locator('summary').first();await first.focus();await first.press('Enter');await expect(page.locator('details').first()).toHaveAttribute('open','');await first.press('Enter');await expect(page.locator('details').first()).not.toHaveAttribute('open','');await page.getByRole('link',{name:'Ticket yarat',exact:true}).focus();await page.keyboard.press('Enter');await expect(page).toHaveURL(/\/login$/);await page.goBack();await expect(heading).toHaveText(title!);}
 const home=page.getByRole('link',{name:'AEVIC Esports ana səhifə'}).first();await home.focus();await home.press('Enter');await expect(page).toHaveURL(/\/$/);await page.goBack();await expect(heading).toHaveText(title!);
});
