import { Bell, Database, KeyRound, Laptop, LockKeyhole, LogOut, ShieldCheck, Trash2, UserRound } from 'lucide-react';
import { type FormEvent, useEffect, useState } from 'react';
import { NavLink } from 'react-router-dom';
import { BrandMark } from '../components/brand/BrandMark';
import { RouteSeo } from '../components/common/Seo';
import { RouteTransitionOutlet } from '../components/common/Motion';
import { Button, Checkbox, ConfirmDialog, EmptyState, Input, LoadingSkeleton, PageHeader, PhoneInput, SectionHeading, Toast } from '../components/common/primitives';
import { services } from '../services';
import type { AccountExportJob, AccountProfile, AccountSession, NotificationPreferences, TwoFactorRecoveryCodes, TwoFactorSetup, TwoFactorStatus } from '../types/domain';

const accountLinks = [
  { to: '/account/profile', label: 'Profil', icon: UserRound },
  { to: '/account/security', label: 'Təhlükəsizlik', icon: LockKeyhole },
  { to: '/account/notifications', label: 'Bildirişlər', icon: Bell },
  { to: '/account/sessions', label: 'Sessiyalar', icon: Laptop },
];

export function AccountLayout() {
  return <div className="account-shell"><RouteSeo /><a className="skip-link" href="#account-content">Əsas məzmuna keç</a><aside><BrandMark /><div><span>Hesab</span><strong>Şəxsi giriş və təhlükəsizlik</strong></div><nav aria-label="Hesab bölmələri">{accountLinks.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to}><Icon size={18} />{label}</NavLink>)}</nav><NavLink className="account-shell__team-link" to="/team">Komanda panelinə qayıt</NavLink></aside><main id="account-content"><RouteTransitionOutlet family="account" /></main></div>;
}

function useAccountProfile() {
  const [profile, setProfile] = useState<AccountProfile>(); const [failed, setFailed] = useState(false);
  useEffect(() => { services.account.profile().then(setProfile).catch(() => setFailed(true)); }, []);
  return { profile, setProfile, failed };
}

export function AccountProfilePage() {
  const { profile, setProfile, failed } = useAccountProfile(); const [saved, setSaved] = useState(false); const [deletionOpen, setDeletionOpen] = useState(false); const [notice, setNotice] = useState('');
  const [exportJob, setExportJob] = useState<AccountExportJob>(); const [exporting, setExporting] = useState(false);
  const [firstName, setFirstName] = useState(''); const [lastName, setLastName] = useState(''); const [phone, setPhone] = useState('');
  useEffect(() => { if (profile) { setFirstName(profile.user.firstName); setLastName(profile.user.lastName); setPhone(profile.user.phone ?? ''); } }, [profile]);
  if (failed) return <EmptyState title="Hesab yüklənmədi" body="Hesab servisi cavab vermir. Bir az sonra yenidən cəhd edin." />;
  if (!profile) return <LoadingSkeleton rows={6} />;
  const submit = async (event: FormEvent) => { event.preventDefault(); const next = await services.account.updateProfile({ firstName, lastName, phone }); setProfile(next); setSaved(true); };
  const requestDeletion = async () => { const result = await services.account.requestDeletion(); setDeletionOpen(false); setNotice(result.blocked ? result.reason ?? 'Hesab silinə bilmir.' : 'Hesab silinməsi üçün təsdiq göndərildi.'); };
  const requestExport = async () => { setExporting(true); try { const job = await services.account.requestDataExport(); setExportJob(job); setNotice("Yükləmə sorğusu yaradıldı. Hazır olduqda təhlükəsiz keçid görünəcək."); } catch { setNotice("Məlumatları hazırlayan server xidməti hələ qoşulmayıb."); } finally { setExporting(false); } };
  return <><PageHeader eyebrow="Hesab profili" title="Şəxsi məlumatlar" description="Hesab məlumatları komandanın ictimai kimliyi və yarış nəticələrindən ayrıdır." />{saved && <Toast title="Hesab məlumatları saxlanıldı" onClose={() => setSaved(false)} />}{notice && <Toast tone="info" title="Hesab əməliyyatı" body={notice} onClose={() => setNotice('')} />}<form className="account-form" onSubmit={submit}><section><SectionHeading title="Profil" /><div className="form-grid"><Input label="Ad" value={firstName} onChange={(event) => setFirstName(event.target.value)} autoComplete="given-name" required /><Input label="Soyad" value={lastName} onChange={(event) => setLastName(event.target.value)} autoComplete="family-name" required /></div><Input label="E-poçt" type="email" value={profile.user.email} disabled hint={profile.emailVerified ? "E-poçt təsdiqlənib" : "E-poçt təsdiqi tələb olunur"} /><PhoneInput label="Telefon" value={phone} onValueChange={setPhone} autoComplete="tel" /><Button type="submit">Dəyişiklikləri saxla</Button></section><section className="account-boundary"><SectionHeading title="Məxfilik və hesab" /><div><Database size={20} /><span><strong>Məlumatlarımı yüklə</strong><small>{exportJob ? `Export ${exportJob.status.toLocaleLowerCase('az')}` : "Yüklənəcək fayl yalnız server xidməti hazır olduqda yaradılır."}</small></span>{exportJob?.status === 'READY' && exportJob.downloadUrl ? <a className="button button--secondary" href={exportJob.downloadUrl}><span>Yüklə</span></a> : <Button variant="secondary" loading={exporting} disabled={profile.dataExportStatus === 'backend-required'} onClick={() => void requestExport()}>Yükləmə tələb et</Button>}</div><div><Trash2 size={20} /><span><strong>Hesabı deaktiv et</strong><small>Komanda sahibsiz qala bilməz.</small></span><Button variant="danger" onClick={() => setDeletionOpen(true)}>Deaktiv et</Button></div></section></form><ConfirmDialog open={deletionOpen} title="Hesabı deaktiv etmək istəyirsiniz?" body="Komanda sahibisinizsə, əvvəlcə sahibliyi ötürməlisiniz. Bu əməliyyat server təsdiqi olmadan icra edilmir." confirmLabel="Yoxla və davam et" onClose={() => setDeletionOpen(false)} onConfirm={requestDeletion} /></>;
}

export function AccountSecurityPage() {
  const [status, setStatus] = useState<TwoFactorStatus>(); const [currentPassword, setCurrentPassword] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false);
  const [setup, setSetup] = useState<TwoFactorSetup>(); const [otp, setOtp] = useState(''); const [recovery, setRecovery] = useState<TwoFactorRecoveryCodes>(); const [twoFactorLoading, setTwoFactorLoading] = useState(false);
  useEffect(() => { services.account.twoFactorStatus().then(setStatus); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (password !== confirmation || password.length < 8) { setNotice('Yeni şifrə minimum 8 simvol olmalı və təsdiqlə uyğun gəlməlidir.'); return; } setLoading(true); try { await services.account.changePassword(currentPassword, password); setNotice('Şifrə yeniləndi.'); setCurrentPassword(''); setPassword(''); setConfirmation(''); } catch { setNotice('Şifrə yenilənmədi. Cari şifrəni yoxlayın.'); } finally { setLoading(false); } };
  const beginTwoFactor = async () => { setTwoFactorLoading(true); try { setSetup(await services.account.beginTwoFactorSetup()); } catch { setNotice("2FA aktivləşdirmə xidməti hələ qoşulmayıb."); } finally { setTwoFactorLoading(false); } };
  const verifyTwoFactor = async () => { if (!setup || !/^\d{6}$/.test(otp)) { setNotice("Doğrulama tətbiqindən 6 rəqəmli kod daxil edin."); return; } setTwoFactorLoading(true); try { setRecovery(await services.account.verifyTwoFactorSetup(setup.setupId, otp)); setStatus(await services.account.twoFactorStatus()); setSetup(undefined); setOtp(''); setNotice("2FA aktiv edildi. Bərpa kodlarını təhlükəsiz saxlayın."); } catch { setNotice("Birdəfəlik kod təsdiqlənmədi və ya aktivləşdirmə müddəti bitib."); } finally { setTwoFactorLoading(false); } };
  return <><PageHeader eyebrow="Hesab təhlükəsizliyi" title="Təhlükəsizlik" description="Şifrə dəyişikliyi, TOTP aktivləşdirilməsi və hesabın bərpası." />{notice && <Toast tone={notice.includes('yeniləndi.') || notice.includes('aktiv edildi') ? 'success' : 'error'} title="Təhlükəsizlik statusu" body={notice} onClose={() => setNotice('')} />}<div className="account-security-grid"><form className="account-form" onSubmit={submit}><SectionHeading title="Şifrəni dəyiş" description="Unudulmuş şifrənin bərpasından fərqli olaraq cari şifrə tələb olunur." /><Input label="Cari şifrə" type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} autoComplete="current-password" required /><Input label="Yeni şifrə" type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" required /><Input label="Yeni şifrəni təsdiqlə" type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="new-password" required /><Button type="submit" loading={loading} icon={<KeyRound size={17} />}>Şifrəni yenilə</Button></form><section className="two-factor-panel"><ShieldCheck size={26} /><span>İki mərhələli doğrulama</span><h2>{status?.enabled ? 'Aktivdir' : status?.setupAvailable ? 'Aktivləşdirməyə hazırdır' : "Server xidməti tələb olunur"}</h2><p>Məxfi açar və bərpa kodları serverdə yaradılır, birdəfəlik kod orada yoxlanılır. Kodlar audit jurnalına daxil edilmir.</p>{setup ? <div className="two-factor-setup"><img src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(setup.qrSvg)}`} alt="Doğrulama tətbiqi üçün TOTP QR kodu" /><Input label="6 rəqəmli OTP" inputMode="numeric" autoComplete="one-time-code" maxLength={6} pattern="[0-9]{6}" value={otp} onChange={(event) => setOtp(event.target.value.replace(/\D/g, ''))} /><Button loading={twoFactorLoading} onClick={() => void verifyTwoFactor()}>Kodu təsdiqlə</Button></div> : <Button loading={twoFactorLoading} disabled={!status?.setupAvailable || status?.enabled} onClick={() => void beginTwoFactor()}>{status?.enabled ? '2FA aktivdir' : '2FA-nı aktiv et'}</Button>}{recovery && <div className="recovery-codes" role="status"><strong>Birdəfəlik bərpa kodları</strong><code>{recovery.codes.join('\n')}</code><small>Bu siyahı yalnız bir dəfə göstərilir.</small></div>}{!status?.setupAvailable && <small>Canlı sistemdə admin hesabları üçün server tərəfindən məcburi edilməlidir.</small>}</section></div></>;
}

export function AccountSessionsPage() {
  const [sessions, setSessions] = useState<AccountSession[]>(); const [notice, setNotice] = useState(''); const [confirmOpen, setConfirmOpen] = useState(false);
  const load = () => services.account.sessions().then(setSessions); useEffect(() => { void load(); }, []);
  const revoke = async (id: string) => { await services.account.revokeSession(id); await load(); setNotice('Sessiya ləğv edildi.'); };
  const revokeOthers = async () => { await services.account.revokeOtherSessions(); await load(); setConfirmOpen(false); setNotice('Digər sessiyalar ləğv edildi.'); };
  return <><PageHeader eyebrow="Cihazlar və sessiyalar" title="Aktiv sessiyalar" description="Hesabınıza daxil olan cihazları yoxlayın və tanımadığınız sessiyanı bağlayın." actions={<Button variant="danger" onClick={() => setConfirmOpen(true)}>Digər hamısından çıx</Button>} />{notice && <Toast title={notice} onClose={() => setNotice('')} />}{!sessions ? <LoadingSkeleton rows={5} /> : <div className="session-list">{sessions.map((session) => <article key={session.id}><Laptop size={22} /><div><strong>{session.device}</strong><span>{session.browser} · {session.location ?? 'Məkan yoxdur'}</span><small>Son aktivlik: {new Date(session.lastActiveAt).toLocaleString('az-AZ')}</small></div><b>{session.status === 'current' ? 'Cari sessiya' : 'Aktiv'}</b><Button variant="ghost" disabled={session.status === 'current'} onClick={() => void revoke(session.id)} icon={<LogOut size={16} />}>Çıxış et</Button></article>)}</div>}<ConfirmDialog open={confirmOpen} title="Digər sessiyaları bağla" body="Cari cihaz istisna olmaqla bütün sessiyalar ləğv ediləcək." confirmLabel="Hamısından çıx" onClose={() => setConfirmOpen(false)} onConfirm={revokeOthers} /></>;
}

export function AccountNotificationsPage() {
  const [preferences, setPreferences] = useState<NotificationPreferences>(); const [saved, setSaved] = useState(false);
  useEffect(() => { services.notifications.preferences().then(setPreferences); }, []);
  if (!preferences) return <LoadingSkeleton rows={6} />;
  const toggleEvent = (key: string) => setPreferences({ ...preferences, events: { ...preferences.events, [key]: !preferences.events[key] } });
  const save = async () => { setPreferences(await services.notifications.updatePreferences(preferences)); setSaved(true); };
  return <><PageHeader eyebrow="Bildiriş seçimləri" title="Bildiriş seçimləri" description="Sistem hadisələri admin mesajlarından ayrıdır. E-poçt və push bildirişləri üçün çatdırılma xidməti tələb olunur." />{saved && <Toast title="Bildiriş seçimləri saxlanıldı" onClose={() => setSaved(false)} />}<section className="notification-settings"><SectionHeading title="Kanallar" /><Checkbox label="Tətbiqdaxili bildirişlər" checked={preferences.channels['in-app']} onChange={() => setPreferences({ ...preferences, channels: { ...preferences.channels, 'in-app': !preferences.channels['in-app'] } })} /><Checkbox label="E-poçt bildirişləri (xidmət tələb olunur)" checked={preferences.channels.email} onChange={() => setPreferences({ ...preferences, channels: { ...preferences.channels, email: !preferences.channels.email } })} /><Checkbox label="Push bildirişləri (xidmət tələb olunur)" checked={preferences.channels.push} onChange={() => setPreferences({ ...preferences, channels: { ...preferences.channels, push: !preferences.channels.push } })} /><hr /><SectionHeading title="Hadisələr" />{[['checkIn', 'Check-in açıldıqda'], ['roomRelease', "Otaq məlumatı yayımlandıqda"], ['results', 'Nəticə dərc edildikdə'], ['roster', "Heyət sorğusu dəyişdikdə"], ['achievements', "Nişan qazanıldıqda"]].map(([key, label]) => <Checkbox key={key} label={label} checked={Boolean(preferences.events[key])} onChange={() => toggleEvent(key)} />)}<Button onClick={() => void save()}>Seçimləri saxla</Button></section></>;
}
