import '../styles/lifecycle.css';
import { useEffect,useState,type FormEvent } from 'react';
import { Link,useNavigate } from 'react-router-dom';
import { Button,Input,Select,Textarea,PageHeader,EmptyState } from '../components/common/primitives';
import { services,serviceCapabilities } from '../services';
import { useAdminPlatformData } from '../services/PlatformDataContext';
import { invalidateQuery } from '../services/queryCache';
import type { TournamentCreation,RoundResult } from '../types/domain';

export function TournamentCreateForm(){
 const navigate=useNavigate();const [busy,setBusy]=useState(false),[error,setError]=useState('');const[key]=useState(()=>crypto.randomUUID());
 const[rounds,setRounds]=useState<Array<{map:'Erangel'|'Miramar'|'Rondo';startsAt:string}>>([{map:'Erangel',startsAt:''},{map:'Miramar',startsAt:''},{map:'Rondo',startsAt:''},{map:'Erangel',startsAt:''}]);
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(busy)return;setBusy(true);setError('');const data=new FormData(event.currentTarget);const value=(key:string)=>String(data.get(key)??'');
  try{const input:TournamentCreation={name:value('name'),shortName:value('shortName'),description:value('description'),startsAt:new Date(value('startsAt')).toISOString(),endsAt:new Date(value('endsAt')).toISOString(),registrationOpensAt:new Date(value('registrationOpensAt')).toISOString(),registrationDeadline:new Date(value('registrationDeadline')).toISOString(),checkInOpensAt:new Date(value('checkInOpensAt')).toISOString(),checkInClosesAt:new Date(value('checkInClosesAt')).toISOString(),maxSlots:Number(value('maxSlots')),rules:value('rules').split('\n').map(v=>v.trim()).filter(Boolean),rounds:rounds.map(r=>({...r,startsAt:new Date(r.startsAt).toISOString()}))};const t=await services.tournaments.create(input,key);invalidateQuery('snapshot:admin');invalidateQuery('snapshot:public');navigate(`/admin/tournaments/${t.id}`);}catch{setError('Turnir yaradılmadı. Tarix ardıcıllığını və tələb olunan sahələri yoxlayın.');}finally{setBusy(false);}};
 return <><PageHeader eyebrow="Turnir konfiqurasiyası" title="Yeni turnir" description="Vaxtlar cihazınızın saat qurşağında daxil edilir. Hər raundun dəqiq başlanğıcını yoxlayın."/><form className="operation-form" onSubmit={submit}>{error&&<p role="alert" className="field__error">{error}</p>}<div className="form-grid"><Input label="Turnir adı" name="name" minLength={2} maxLength={120} required/><Input label="Qısa ad" name="shortName" minLength={2} maxLength={50} required/></div><Textarea label="Təsvir" name="description" maxLength={3000}/><div className="form-grid">{([['startsAt','Turnirin başlanğıcı'],['endsAt','Turnirin bitməsi'],['registrationOpensAt','Qeydiyyat açılır'],['registrationDeadline','Qeydiyyat bağlanır'],['checkInOpensAt','Check-in açılır'],['checkInClosesAt','Check-in bağlanır']] as const).map(([name,label])=><Input key={name} name={name} label={label} type="datetime-local" required/>)}</div><Input label="Maksimum komanda sayı" name="maxSlots" type="number" min={1} max={100} defaultValue={20} required/><h2>Raund cədvəli</h2>{rounds.map((round,i)=><div className="form-grid" key={i}><Select label={`${i+1}. raund xəritəsi`} value={round.map} onChange={e=>setRounds(items=>items.map((r,k)=>k===i?{...r,map:e.target.value as typeof r.map}:r))}>{['Erangel','Miramar','Rondo'].map(map=><option key={map}>{map}</option>)}</Select><Input label={`${i+1}. raund başlayır`} type="datetime-local" value={round.startsAt} onChange={e=>setRounds(items=>items.map((r,k)=>k===i?{...r,startsAt:e.target.value}:r))} required/></div>)}<p>Otaq məlumatı hər raunddan 10 dəqiqə əvvəl uyğun komandalara açılır. Yerləşmə xalları: 10, 6, 5, 4, 3, 2, 1, 1. Hər kill: 1 xal. WWCD üçün əlavə bonus yoxdur.</p><Textarea label="Qaydalar — hər sətirdə bir qayda" name="rules" required/><Button type="submit" loading={busy} disabled={!serviceCapabilities.tournamentCreation}>Turniri yarat və qeydiyyatı aç</Button></form></>;
}
export function ResultEntryForm(){
 const snapshot=useAdminPlatformData();const[tour,setTour]=useState(''),[round,setRound]=useState(''),[team,setTeam]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const[saved,setSaved]=useState<RoundResult[]>([]);const[revision,setRevision]=useState(0);useEffect(()=>{let active=true;setSaved([]);if(round)void services.results.roundEntries(round).then(rows=>{if(active)setSaved(rows)}).catch(()=>{if(active)setNotice('Saxlanmış nəticələr yüklənmədi.');});return()=>{active=false;};},[round,revision]);
 const[entries,setEntries]=useState<Array<{teamId:string;status:string}>>([]);const rounds=(snapshot.matchSchedule??[]).filter(m=>m.tournamentId===tour);
 useEffect(()=>{let active=true;setEntries([]);if(tour)void services.tournaments.entries(tour).then(items=>{if(active)setEntries(items)}).catch(()=>{if(active)setNotice('Qeydiyyatlar yüklənmədi.')});return()=>{active=false}},[tour]);
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy)return;setBusy(true);setNotice('');const form=new FormData(e.currentTarget);try{await services.results.saveRound({id:crypto.randomUUID(),tournamentId:tour,roundId:round,teamId:team,placement:Number(form.get('placement')),finishes:Number(form.get('kills')),penalties:Number(form.get('penalties')),placementPoints:0,finishPoints:0,totalPoints:0,published:false});setRevision(v=>v+1);setNotice('Komanda nəticəsi saxlanıldı. Bütün komandalar tamamlandıqdan sonra raundu dərc edin.');}catch{setNotice('Nəticə saxlanılmadı. Təkrar komanda, yerləşmə və ya səlahiyyəti yoxlayın.')}finally{setBusy(false)}};
 const publish=async()=>{if(busy||!round)return;setBusy(true);try{await services.tournaments.publishMatch(round);invalidateQuery('snapshot:admin');invalidateQuery('snapshot:public');setRevision(v=>v+1);setNotice('Raundun bütün nəticələri dərc edildi.');}catch{setNotice('Dərc tamamlanmadı. Hər təsdiqlənmiş komandanın nəticəsi tələb olunur.')}finally{setBusy(false)}};
 return <><PageHeader eyebrow="Rəsmi nəticələr" title="Nəticə girişi" description="Xallar serverdə turnirin düsturundan hesablanır. Komanda istifadəçiləri nəticələri dəyişə bilməz."/>{notice&&<p role="status">{notice}</p>}<form className="operation-form" onSubmit={save}><Select label="Turnir" value={tour} onChange={e=>{setTour(e.target.value);setRound('');setTeam('')}} required><option value="">Turnir seçin</option>{snapshot.tournaments.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</Select><Select label="Raund" value={round} onChange={e=>setRound(e.target.value)} required><option value="">Raund seçin</option>{rounds.map(m=><option key={m.id} value={m.id}>{m.round}. raund · {m.map}</option>)}</Select><Select label="Komanda" value={team} onChange={e=>setTeam(e.target.value)} required><option value="">Komanda seçin</option>{entries.filter(e=>e.status==='confirmed').map(e=><option key={e.teamId} value={e.teamId}>{snapshot.teams.find(t=>t.id===e.teamId)?.name??e.teamId}</option>)}</Select><div className="form-grid"><Input label="Yerləşmə" name="placement" type="number" min={1} max={100} required/><Input label="Kill sayı" name="kills" type="number" min={0} max={400} required/><Input label="Cərimə xalı" name="penalties" type="number" min={0} max={1000} defaultValue={0} required/></div><Button type="submit" loading={busy} disabled={!serviceCapabilities.resultPublishing}>Komanda nəticəsini saxla</Button><Button type="button" variant="secondary" disabled={busy||!round||!serviceCapabilities.resultPublishing} onClick={()=>void publish()}>Bütün raund nəticələrini dərc et</Button></form>{saved.length>0&&<section className="operation-form"><h2>Saxlanmış nəticələr</h2>{saved.map(r=><div key={r.id}><strong>{snapshot.teams.find(t=>t.id===r.teamId)?.name??r.teamId}</strong> · #{r.placement} · {r.finishes} kill · {r.totalPoints} xal · {r.published?'Dərc edilib':'Qaralama'} <Link to={`/admin/results/${r.id}/correct`}>Düzəliş et</Link></div>)}</section>}</>;
}
export function TournamentOperations({tournamentId}:{tournamentId:string}){
 const{teams,matchSchedule}=useAdminPlatformData();const[entries,setEntries]=useState<Array<{id:string;teamId:string;status:string}>>(),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=()=>services.tournaments.entries(tournamentId).then(setEntries);useEffect(()=>{void load().catch(()=>setNotice('Turnir qeydiyyatları yüklənmədi.'));},[tournamentId]);
 const review=async(teamId:string,status:'confirmed'|'rejected')=>{if(busy)return;setBusy(true);try{await services.tournaments.reviewEntry(tournamentId,teamId,status);await load();invalidateQuery('snapshot:admin');invalidateQuery('snapshot:public');setNotice('Qeydiyyat yeniləndi.')}catch{setNotice('Qərar saxlanılmadı. Tutum və qeydiyyat statusunu yoxlayın.')}finally{setBusy(false)}};
 const saveRoom=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy)return;setBusy(true);const form=e.currentTarget;const data=new FormData(form);try{await services.tournaments.saveRoom(String(data.get('match')),String(data.get('room')),String(data.get('password')));form.reset();setNotice('Otaq məlumatları təhlükəsiz saxlanıldı.')}catch{setNotice('Otaq məlumatları saxlanılmadı.')}finally{setBusy(false)}};
 if(!serviceCapabilities.tournamentCreation)return null;
 return <section className="operation-form"><h2>Turnir qeydiyyatları</h2>{notice&&<p role="status">{notice}</p>}{entries?.length?entries.map(e=><div className="settings-savebar" key={e.id}><span>{teams.find(t=>t.id===e.teamId)?.name??e.teamId} · {e.status}</span>{e.status==='pending'&&<div className="decision-actions"><Button disabled={busy} onClick={()=>void review(e.teamId,'confirmed')}>Təsdiqlə</Button><Button disabled={busy} variant="danger" onClick={()=>void review(e.teamId,'rejected')}>Rədd et</Button></div>}</div>):<p>Qeydiyyat yoxdur.</p>}<form onSubmit={saveRoom}><h2>Otaq məlumatları</h2><Select label="Raund" name="match" required><option value="">Raund seçin</option>{matchSchedule?.filter(m=>m.tournamentId===tournamentId).map(m=><option key={m.id} value={m.id}>{m.round}. raund · {m.map}</option>)}</Select><div className="form-grid"><Input name="room" label="Otaq ID" maxLength={100} autoComplete="off" required/><Input name="password" label="Otaq şifrəsi" maxLength={200} type="password" autoComplete="new-password" required/></div><Button type="submit" loading={busy}>Otaq məlumatlarını saxla</Button></form></section>;
}
