export { AdminDashboardPage } from './routes/AdminDashboardPage';
export { AdminTournamentsPage } from './routes/AdminTournamentsPage';
export { AdminTournamentNewPage } from './routes/AdminTournamentNewPage';
export { AdminTournamentDetailPage } from './routes/AdminTournamentDetailPage';
export { AdminTeamsPage } from './routes/AdminTeamsPage';
export { AdminResultsPage } from './routes/AdminResultsPage';
export { AdminMessagesPage } from './routes/AdminMessagesPage';
export { AdminBlacklistPage } from './routes/AdminBlacklistPage';
export { AdminSettingsPage } from './routes/AdminSettingsPage';
