import { AlertTriangle, ArrowRight, BadgeCheck, Building2, FileClock, History, ShieldCheck, UserPlus, Users } from 'lucide-react';
import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { Button, EmptyState, Input, LoadingSkeleton, PageHeader, SectionHeading, Select, TeamLogo, Textarea, Toast } from '../components/common/primitives';
import { serviceCapabilities, services } from '../services';
import { useAdminPlatformData, useTeamPlatformData } from '../services/PlatformDataContext';
import type { DurableInvitation, ResultVersion, SupportTicket, TeamAuthorityMember, TeamAuthorityRole, VerificationRequest, VerificationStatus } from '../types/domain';
import { safeInternalPath } from '../utils/routes';

function IntegrationBoundary({ children }: { children?: React.ReactNode }) {
  if (!serviceCapabilities.mockPreview) return children;
  return <section className="integration-boundary" role="note"><AlertTriangle size={20} /><div><strong>Production backend tələb olunur</strong><p>Bu ekran real API müqaviləsinə qoşulub, lakin cari build mock rejimindədir. Həssas dəyişikliklər lokal state ilə saxtalaşdırılmır.</p>{children}</div></section>;
}

function formatDate(value: string) {
  return new Date(value).toLocaleString('az-AZ', { dateStyle: 'medium', timeStyle: 'short' });
}

export function SearchResultsPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const query = searchParams.get('q') ?? '';
  const [result, setResult] = useState<Awaited<ReturnType<typeof services.search.public>>>();
  useEffect(() => { let active = true; services.search.public(query).then((value) => { if (active) setResult(value); }); return () => { active = false; }; }, [query]);
  const items = useMemo(() => result ? Object.entries(result.groups).filter(([group]) => group !== 'player').flatMap(([, group]) => group ?? []).map((item) => ({ ...item, href: safeInternalPath(item.href) })).filter((item): item is typeof item & { href: string } => Boolean(item.href)) : [], [result]);
  return <section className="page-section completion-page"><div className="container"><PageHeader eyebrow="Platform search" title="Axtarış nəticələri" description="Komandalar, turnirlər və rekordlar vahid public indeksdən gəlir." /><form className="directory-search" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setSearchParams({ q: String(data.get('q') ?? '').trim() }); }}><Input name="q" label="Axtarış" defaultValue={query} minLength={2} required /><Button type="submit">Axtar</Button></form>{!result ? <LoadingSkeleton rows={5} /> : items.length ? <div className="search-results-ledger">{items.map((item) => <Link key={`${item.type}-${item.id}`} to={item.href}><span>{item.type}</span><div><strong>{item.title}</strong><small>{item.subtitle}</small></div><ArrowRight size={17} /></Link>)}</div> : <EmptyState title="Nəticə tapılmadı" body={query ? `“${query}” üçün uyğun nəticə yoxdur.` : 'Axtarış üçün ən azı iki simvol yazın.'} />}</div></section>;
}

export function FollowingPage() {
  const [items, setItems] = useState<Awaited<ReturnType<NonNullable<typeof services.follows>['list']>>>();
  useEffect(() => { if (services.follows) services.follows.list().then(setItems); else setItems([]); }, []);
  return <section className="page-section completion-page"><div className="container"><PageHeader eyebrow="Competition following" title="İzlədiklərim" description="Yalnız yarış baxımından əhəmiyyətli komanda və oyunçu yenilikləri burada görünür." /><IntegrationBoundary />{!items ? <LoadingSkeleton rows={4} /> : items.length ? <div className="entity-ledger">{items.map((item) => <article key={`${item.entityType}-${item.entityId}`}><ShieldCheck size={18} /><span><strong>{item.entityType}</strong><small>{item.entityId}</small></span></article>)}</div> : <EmptyState title="İzlənən profil yoxdur" body="Account-backed follow servisi qoşulduqda izlədiyiniz komandalar və oyunçular burada görünəcək." action={<Link className="button button--secondary" to="/teams"><span>Komandaları kəşf et</span></Link>} />}</div></section>;
}

export function PlayerClaimPage() {
  const { playerId = '' } = useParams(); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setLoading(true); try { await services.players.claim(playerId, data.get('method') as 'ACCOUNT_MATCH' | 'PUBG_IDENTITY' | 'ADMIN_REVIEW', [], crypto.randomUUID()); setNotice('Claim review üçün göndərildi.'); } catch { setNotice('Claim saxlanmadı. Typed PUBG ID təkbaşına ownership sübutu deyil; production identity review tələb olunur.'); } finally { setLoading(false); } };
  return <><PageHeader eyebrow="Player identity" title="Oyunçu profilini claim et" description="Public oyunçu kimliyini hesabınıza bağlamaq üçün server təsdiqi tələb olunur. Profil avtomatik verilmir." />{notice && <Toast title="Claim statusu" body={notice} onClose={() => setNotice('')} />}<IntegrationBoundary /><form className="operation-form narrow-form" onSubmit={submit}><Select name="method" label="Verification üsulu" defaultValue="ACCOUNT_MATCH"><option value="ACCOUNT_MATCH">Mövcud account uyğunluğu</option><option value="PUBG_IDENTITY">PUBG identity verification</option><option value="ADMIN_REVIEW">Admin review</option></Select><Input label="Player ID" value={playerId} disabled /><Textarea label="Əlavə izah" minLength={20} required hint="Şifrə və ya həssas məlumat daxil etməyin." /><Button type="submit" loading={loading}>Claim review göndər</Button></form></>;
}

export function TeamGovernancePage() {
  const { currentTeam } = useTeamPlatformData();
  const [members, setMembers] = useState<TeamAuthorityMember[]>();
  const [invitations, setInvitations] = useState<DurableInvitation[]>();
  const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const load = () => Promise.all([services.teams.authority(currentTeam.id), services.teams.invitations(currentTeam.id)]).then(([authority, page]) => { setMembers(authority); setInvitations(page.items); });
  useEffect(() => { void load(); }, [currentTeam.id]);
  const invite = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setLoading(true); setError(''); const data = new FormData(event.currentTarget);
    try { await services.teams.invite(currentTeam.id, String(data.get('recipient')), data.get('role') as TeamAuthorityRole, crypto.randomUUID()); await load(); setNotice('Dəvət göndərildi.'); event.currentTarget.reset(); }
    catch { setError('Dəvət göndərilmədi. Production backend, permission və təkrar dəvət məhdudiyyətini yoxlayın.'); }
    finally { setLoading(false); }
  };
  return <><PageHeader eyebrow="Komanda səlahiyyətləri" title="Menecerlər və səlahiyyətlər" description="OWNER, CAPTAIN, MANAGER, CO_CAPTAIN, PLAYER və SUBSTITUTE rol modeli. UI icazə mənbəyi deyil." />{notice && <Toast title={notice} onClose={() => setNotice('')} />}{error && <Toast tone="error" title="Əməliyyat tamamlanmadı" body={error} onClose={() => setError('')} />}<IntegrationBoundary /><div className="completion-grid"><section><SectionHeading title="Aktiv səlahiyyətlər" />{members ? <div className="authority-ledger">{members.map((member) => <article key={member.id}><TeamLogo name={member.displayName} /><div><strong>{member.displayName}</strong><small>{member.role} · {member.permissions.join(' · ') || 'Xüsusi icazə yoxdur'}</small></div><span>{member.status}</span></article>)}</div> : <LoadingSkeleton rows={4} />}</section><section><SectionHeading title="Menecer dəvət et" description="Sahib hüququ avtomatik verilmir." /><form className="operation-form" onSubmit={invite}><Input name="recipient" label="Email və ya hesab identifikatoru" required /><Select name="role" label="Rol" defaultValue="MANAGER"><option value="MANAGER">Menecer</option><option value="CO_CAPTAIN">Kapitan köməkçisi</option></Select><Button type="submit" loading={loading} icon={<UserPlus size={17} />}>Dəvət göndər</Button></form></section></div><section><SectionHeading title="Gözləyən dəvətlər" />{invitations?.length ? <div className="invitation-ledger">{invitations.map((invite) => <article key={invite.id}><FileClock size={18} /><div><strong>{invite.recipientLabel}</strong><small>{invite.role} · bitir {formatDate(invite.expiresAt)}</small></div><span>{invite.status}</span></article>)}</div> : <EmptyState title="Gözləyən dəvət yoxdur" body="Göndərilən davamlı dəvətlər bitmə və ləğv statusu ilə burada görünəcək." />}</section><section className="danger-ledger"><div><strong>Sahibliyi ötür</strong><p>Uyğun üzv, dayandırılma statusu, aktiv turnir və paralel əməliyyatlar backend tranzaksiyasında yoxlanmalıdır.</p></div><Button variant="danger" disabled={serviceCapabilities.mockPreview}>Ötürmə axınını aç</Button><div><strong>Komandanı arxivlə</strong><p>Tarixi nəticələr və heyət snapshot-ları silinmir.</p></div><Button variant="danger" disabled={serviceCapabilities.mockPreview}>Arxiv qaydalarını yoxla</Button></section></>;
}

export function BadgeDetailPage() {
  const { badgeId = '' } = useParams(); const { teamAchievements } = useTeamPlatformData(); const badge = teamAchievements.find((item) => item.id === badgeId);
  if (!badge) return <EmptyState title="Badge tapılmadı" body="Bu badge kolleksiyada yoxdur və ya public görünür deyil." />;
  return <><Link className="text-link" to="/team/badges">← Badge Cabinet</Link><PageHeader eyebrow={badge.category} title={badge.title} description={badge.description} /><div className="completion-grid"><section className="badge-art-pending"><span>ART PENDING</span><strong>{badge.tier}</strong><p>Təsdiqlənmiş artwork olmadığı üçün final insignia fabricasiya edilmir.</p></section><section><SectionHeading title="Tier və progress" /><dl className="detail-ledger"><div><dt>Cari tier</dt><dd>{badge.tier}</dd></div><div><dt>Status</dt><dd>{badge.state}</dd></div><div><dt>Tələb</dt><dd>{badge.progress ? `${badge.progress.target} ${badge.progress.unit}` : badge.description}</dd></div><div><dt>Progress</dt><dd>{badge.progress ? `${badge.progress.current} / ${badge.progress.target}` : 'Authoritative server event tələb olunur'}</dd></div><div><dt>Unlock tarixi</dt><dd>{badge.unlockedAt ? formatDate(badge.unlockedAt) : 'Açılmayıb'}</dd></div></dl></section></div><IntegrationBoundary><p>Tier unlock history və yeni achievement notification yalnız server-calculated unlock events-dən gəlməlidir.</p></IntegrationBoundary></>;
}

export function TeamInvitationsPage() {
  const [items, setItems] = useState<DurableInvitation[]>(); const [notice, setNotice] = useState('');
  const load = () => services.teams.invitations().then((page) => setItems(page.items)); useEffect(() => { void load(); }, []);
  const respond = async (id: string, response: 'ACCEPTED' | 'REJECTED') => { try { await services.teams.respondToInvitation(id, response, crypto.randomUUID()); await load(); setNotice(response === 'ACCEPTED' ? 'Dəvət qəbul edildi.' : 'Dəvət rədd edildi.'); } catch { setNotice('Bu qərar durable backend olmadan saxlanıla bilməz.'); } };
  return <><PageHeader eyebrow="Player invitations" title="Komanda dəvətləri" description="Rol, tournament təsiri, expiration və cavab tarixçəsi olan account-backed dəvətlər." />{notice && <Toast title="Dəvət statusu" body={notice} onClose={() => setNotice('')} />}<IntegrationBoundary />{!items ? <LoadingSkeleton rows={5} /> : items.length ? <div className="invitation-ledger">{items.map((item) => <article key={item.id}><Users size={19} /><div><strong>{item.entityName}</strong><small>{item.role} · {item.tournamentImplications ?? 'Turnir təsiri yoxdur'} · {formatDate(item.expiresAt)}</small></div><span>{item.status}</span>{item.status === 'PENDING' && <div><Button onClick={() => void respond(item.id, 'ACCEPTED')}>Qəbul et</Button><Button variant="ghost" onClick={() => void respond(item.id, 'REJECTED')}>Rədd et</Button></div>}</article>)}</div> : <EmptyState title="Aktiv dəvət yoxdur" body="Kapitan tərəfindən göndərilən durable dəvətlər burada görünəcək." />}</>;
}

export function VerificationApplicationPage() {
  const { currentTeam } = useTeamPlatformData(); const [request, setRequest] = useState<VerificationRequest>(); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { services.verifications.forEntity('TEAM', currentTeam.id).then(setRequest); }, [currentTeam.id]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setLoading(true); try { const next = await services.verifications.apply({ entityType: 'TEAM', entityId: currentTeam.id, entityName: currentTeam.name, representativeName: String(data.get('representative')), officialSocials: { website: String(data.get('website')) }, evidenceNames: [], notes: String(data.get('notes')) }, crypto.randomUUID()); setRequest(next); setNotice('Verification müraciəti göndərildi.'); } catch { setNotice('Müraciət saxlanmadı. Verification backend və private evidence storage tələb olunur.'); } finally { setLoading(false); } };
  return <><PageHeader eyebrow="Authoritative verification" title="Verification müraciəti" description="Public crest yalnız APPROVED server state-dən gəlməlidir. Self-selected badge qəbul edilmir." />{notice && <Toast title="Verification statusu" body={notice} onClose={() => setNotice('')} />}<IntegrationBoundary />{request && <section className="verification-status"><BadgeCheck size={22} /><div><strong>{request.status}</strong><p>{request.safeReason ?? 'Müraciət tarixçəsi server tərəfindən saxlanılır.'}</p></div></section>}<form className="operation-form narrow-form" onSubmit={submit}><Input name="representative" label="Səlahiyyətli nümayəndə" required /><Input name="website" label="Rəsmi website/social URL" type="url" required /><Textarea name="notes" label="Müraciət qeydi" minLength={20} required /><Button type="submit" loading={loading}>Müraciəti göndər</Button></form></>;
}

export function AdminVerificationQueuePage() {
  const [filter, setFilter] = useState<VerificationStatus>('PENDING'); const [items, setItems] = useState<VerificationRequest[]>();
  useEffect(() => { services.verifications.page(filter).then((page) => setItems(page.items)); }, [filter]);
  return <><PageHeader eyebrow="Trust operations" title="Təsdiq sorğuları" description="Evidence private qalır; approve, reject və revoke reason + immutable audit tələb edir." /><div className="admin-toolbar"><Select label="Status" value={filter} onChange={(event) => setFilter(event.target.value as VerificationStatus)}><option>PENDING</option><option>APPROVED</option><option>REJECTED</option><option>REVOKED</option></Select></div><IntegrationBoundary />{!items ? <LoadingSkeleton rows={5} /> : items.length ? <div className="review-ledger">{items.map((item) => <article key={item.id}><BadgeCheck size={20} /><div><strong>{item.entityName}</strong><small>{item.entityType} · {item.representativeName}</small></div><span>{item.status}</span><Link to={`/admin/verifications/${item.id}`}>Yoxla <ArrowRight size={16} /></Link></article>)}</div> : <EmptyState title="Bu statusda müraciət yoxdur" body="Backend verification records təqdim etdikdə queue burada paginated görünəcək." />}</>;
}

export function AdminVerificationDetailPage() {
  const { verificationId = '' } = useParams(); const [item, setItem] = useState<VerificationRequest>(); const [loaded, setLoaded] = useState(false); const [reason, setReason] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { services.verifications.get(verificationId).then(setItem).finally(() => setLoaded(true)); }, [verificationId]);
  const review = async (status: 'APPROVED' | 'REJECTED' | 'REVOKED') => { if (!item || reason.trim().length < 10) { setNotice('Qərar üçün ən az 10 simvolluq faktiki səbəb yazın.'); return; } try { setItem(await services.verifications.review(item.id, status, reason, item.status)); setNotice('Verification qərarı saxlanıldı və audit üçün göndərildi.'); } catch { setNotice('Qərar saxlanmadı. Permission və expected status conflict-i yoxlayın.'); } };
  if (!loaded) return <LoadingSkeleton rows={6} />;
  if (!item) return <><Link className="text-link" to="/admin/verifications">← Verification növbəsinə qayıt</Link><PageHeader eyebrow="Verification review" title="Verification tapılmadı" description="Bu record mövcud deyil və ya admin rolunuz onu görə bilmir." /><IntegrationBoundary /></>;
  return <><PageHeader eyebrow={item.id} title={item.entityName} description={`${item.entityType} verification review`} />{notice && <Toast title="Review statusu" body={notice} onClose={() => setNotice('')} />}<div className="completion-grid"><section><SectionHeading title="Müraciət" /><dl className="detail-ledger"><div><dt>Nümayəndə</dt><dd>{item.representativeName}</dd></div><div><dt>Status</dt><dd>{item.status}</dd></div><div><dt>Evidence</dt><dd>{item.evidenceNames.length} private file</dd></div><div><dt>Notes</dt><dd>{item.notes ?? '—'}</dd></div></dl></section><form className="operation-form"><SectionHeading title="Qərar" /><Textarea label="Qərar səbəbi" value={reason} onChange={(event) => setReason(event.target.value)} minLength={10} required /><div className="decision-actions"><Button onClick={() => void review('APPROVED')}>Təsdiqlə</Button><Button variant="danger" onClick={() => void review('REJECTED')}>Rədd et</Button>{item.status === 'APPROVED' && <Button variant="danger" onClick={() => void review('REVOKED')}>Revoke</Button>}</div></form></div></>;
}

export function AdminPlayerDetailPage() {
  const { playerId = '' } = useParams(); const [detail, setDetail] = useState<Awaited<ReturnType<typeof services.operations.player>>>(); const [loaded, setLoaded] = useState(false);
  useEffect(() => { services.operations.player(playerId).then(setDetail).finally(() => setLoaded(true)); }, [playerId]);
  if (!loaded) return <LoadingSkeleton rows={7} />;
  if (!detail) return <><PageHeader eyebrow="Admin player" title="Oyunçu tapılmadı" description="Private admin detail yalnız server-authorized data ilə göstərilir." /><IntegrationBoundary /></>;
  return <><PageHeader eyebrow="Admin player detail" title={detail.ign} description="Public identity, linked account, membership history, eligibility, sanctions və verification." /><div className="completion-grid"><section><SectionHeading title="Account və komanda" /><dl className="detail-ledger"><div><dt>Linked account</dt><dd>{detail.linkedAccount?.emailHint ?? 'Bağlanmayıb'}</dd></div><div><dt>Cari komanda</dt><dd>{detail.currentTeam?.name ?? 'Yoxdur'}</dd></div><div><dt>Verification</dt><dd>{detail.verification.status}</dd></div></dl></section><section><SectionHeading title="Eligibility və sanctions" /><p>{detail.eligibilityConflicts.length} açıq conflict · {detail.sanctions.length} sanction</p></section></div><section><SectionHeading title="Membership history" />{detail.membershipHistory.length ? <div className="history-ledger">{detail.membershipHistory.map((entry) => <article key={entry.id}><History size={18} /><strong>{entry.entityName}</strong><span>{entry.role}</span><time>{formatDate(entry.joinedAt)} — {entry.leftAt ? formatDate(entry.leftAt) : 'davam edir'}</time></article>)}</div> : <EmptyState title="Tarixçə yoxdur" body="Membership snapshot-ları mövcud olduqda burada görünəcək." />}</section></>;
}

export function AdminSupportQueuePage() {
  const [items, setItems] = useState<SupportTicket[]>(); const [filter, setFilter] = useState<SupportTicket['status'] | ''>('');
  useEffect(() => { services.support.adminPage(undefined, filter || undefined).then((page) => setItems(page.items)); }, [filter]);
  return <><PageHeader eyebrow="Support operations" title="Dəstək sorğuları" description="Ticket reply, assignment və status dəyişiklikləri audit olunmalıdır." /><div className="admin-toolbar"><Select label="Status" value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)}><option value="">Hamısı</option><option value="open">Open</option><option value="waiting-for-user">Waiting for user</option><option value="under-review">Under review</option><option value="resolved">Həll edilib</option><option value="closed">Closed</option></Select></div><IntegrationBoundary />{!items ? <LoadingSkeleton rows={5} /> : items.length ? <div className="request-ledger">{items.map((ticket) => <Link key={ticket.id} to={`/account/support/tickets/${ticket.id}`}><span>{ticket.id}</span><div><strong>{ticket.subject}</strong><small>{ticket.category} · {formatDate(ticket.updatedAt)}</small></div><b>{ticket.status}</b><ArrowRight size={17} /></Link>)}</div> : <EmptyState title="Ticket yoxdur" body="Bu filtrdə support ticket tapılmadı." />}</>;
}

export function AdminResultCorrectionPage() {
  const { resultId = '' } = useParams(); const [versions, setVersions] = useState<ResultVersion[]>();
  useEffect(() => { services.results.versions(resultId).then(setVersions); }, [resultId]);
  return <><Link className="text-link" to="/admin/results">← Nəticələrə qayıt</Link><PageHeader eyebrow="Immutable result history" title="Nəticəni düzəlt" description="Correction originalı overwrite etmir; expected version, səbəb, before/after snapshot və audit event tələb edir." /><IntegrationBoundary />{!versions ? <LoadingSkeleton rows={5} /> : versions.length ? <div className="history-ledger">{versions.map((version) => <article key={version.id}><History size={18} /><strong>Version {version.version}</strong><span>{version.reason}</span><time>{formatDate(version.createdAt)}</time></article>)}</div> : <EmptyState title="Version history yoxdur" body="Result backend bağlanmadan authoritative correction başlatmaq mümkün deyil." />}<form className="operation-form narrow-form"><Textarea label="Correction səbəbi" minLength={20} required /><Button disabled={serviceCapabilities.mockPreview}>Dəyərləri yoxla və yeni version yarat</Button></form></>;
}

export function OrganizationWorkspacePage() {
  const { organizationSlug = '' } = useParams(); const [organization, setOrganization] = useState<Awaited<ReturnType<typeof services.organizations.getBySlug>>>(); const [loaded, setLoaded] = useState(false);
  useEffect(() => { services.organizations.getBySlug(organizationSlug).then(setOrganization).finally(() => setLoaded(true)); }, [organizationSlug]);
  if (!loaded) return <LoadingSkeleton rows={6} />;
  if (!organization) return <EmptyState title="Organization tapılmadı" body="Workspace yalnız üzv olduğunuz organization üçün açılır." />;
  return <><PageHeader eyebrow="Organization workspace" title={organization.name} description="Members, team invitations, ownership, verification, media və audit üçün protected workspace." /><IntegrationBoundary /><div className="completion-grid"><section><Building2 size={25} /><SectionHeading title="Komandalar" /><div className="entity-ledger">{organization.ownedTeams.map((team) => <Link key={team.id} to={`/teams/${team.slug}`}><TeamLogo name={team.displayName} /><span><strong>{team.displayName}</strong><small>{team.gameKey} · {team.status}</small></span><ArrowRight size={17} /></Link>)}</div></section><section><ShieldCheck size={25} /><SectionHeading title="Sahiblik təhlükəsizliyi" /><p>Owner hesabı silinə və ya organization-dan ayrıla bilməz; əvvəlcə atomic transfer tələb olunur.</p><Button disabled={serviceCapabilities.mockPreview}>Ownership transfer</Button></section></div></>;
}

export function TournamentLifecycleAdminPage() {
  const { tournamentId = '' } = useParams(); const { tournaments } = useAdminPlatformData(); const tournament = tournaments.find((item) => item.id === tournamentId);
  if (!tournament) return <EmptyState title="Turnir tapılmadı" body="Bu tournament admin context-də yoxdur." />;
  return <><Link className="text-link" to={`/admin/tournaments/${tournament.id}`}>← Turnir əməliyyatlarına qayıt</Link><PageHeader eyebrow="Tournament lifecycle" title={tournament.name} description="Cancellation və archive tarixçəni silmədən state machine üzərindən işləyir." /><IntegrationBoundary /><section className="lifecycle-state"><span>DRAFT</span><span>SCHEDULED</span><span>REGISTRATION_OPEN</span><span>REGISTRATION_CLOSED</span><span>LIVE</span><span>COMPLETED</span><span>CANCELLED</span><span>ARCHIVED</span></section><div className="completion-grid"><form className="operation-form"><SectionHeading title="Turniri ləğv et" /><Textarea label="Ləğv səbəbi" minLength={20} required /><Button variant="danger" disabled={serviceCapabilities.mockPreview}>Təsdiq və notification planı</Button></form><section><SectionHeading title="Arxivlə" /><p>Teams, matches, standings, champion, recap, records və roster snapshots public tarixçədə qalır.</p><Button disabled={serviceCapabilities.mockPreview}>Arxiv bütövlüyünü yoxla</Button></section></div></>;
}

export function AdminMissedCheckInsPage() {
  const [items, setItems] = useState<Awaited<ReturnType<typeof services.tournaments.missedCheckIns>>['items']>();
  useEffect(() => { services.tournaments.missedCheckIns().then((page) => setItems(page.items)); }, []);
  return <><PageHeader eyebrow="Check-in exceptions" title="Missed check-ins" description="Komanda, nəticə, appeal imkanı və deadline durable state kimi saxlanır; button-un yox olması status hesab edilmir." /><IntegrationBoundary />{!items ? <LoadingSkeleton rows={5} /> : items.length ? <div className="review-ledger">{items.map((item) => <article key={item.id}><AlertTriangle size={19} /><div><strong>{item.teamName}</strong><small>{item.tournamentName} · {item.consequence}</small></div><span>{item.appealAllowed ? 'APPEAL' : 'FINAL'}</span><time>{formatDate(item.missedAt)}</time></article>)}</div> : <EmptyState title="Missed check-in yoxdur" body="Backend missed-check-in events təqdim etdikdə burada paginated görünəcək." />}</>;
}
