import {useEffect,useState,type FormEvent} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Button,EmptyState,Input,LoadingSkeleton,PageHeader,Select} from '../components/common/primitives';
import {services} from '../services';
import type {LegacyClaim,LegacyClaimReview,LegacyHolding,LegacyRoster,LegacyRosterPlayer} from '../types/legacyClaims';

export function LegacyActivationPage(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await services.legacyClaims.activate(email,password);setPassword('');setNotice('Sorğu qəbul edildi. Uyğun olduqda email təsdiqi üçün təlimat gələcək. Bu bildiriş email çatdırılmasını və komanda sahibliyini təsdiqləmir.');}catch{setError('Sorğu tamamlanmadı. Bir qədər sonra yenidən cəhd edin.');}finally{setBusy(false);}}
 return <section className="auth-card"><PageHeader title="Əvvəlki komandanı bərpa et" description="Əvvəlcə yeni hesabınızı yaradın və emailinizi təsdiqləyin. Köhnə şifrəniz istifadə olunmur; komanda ayrıca müstəqil yoxlamadan sonra bağlanır."/><form className="account-form" onSubmit={submit}><Input label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/><Input label="Yeni şifrə" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" minLength={8} maxLength={128} pattern="(?=.*[A-Z])(?=.*[0-9]).{8,128}" required/><small>Ən az 8 simvol, bir böyük hərf və bir rəqəm.</small><Button type="submit" loading={busy}>Hesab üçün müraciət et</Button></form>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}<p><Link to="/login">Artıq hesabınız var? Daxil olun</Link></p><p><Link to="/forgot-password">Yeni hesabın şifrəsini bərpa et</Link></p><p><Link to="/account/legacy-claim">Email təsdiqindən sonra komandanı tələb et</Link></p></section>;
}
export function LegacyClaimPage(){
 const [claims,setClaims]=useState<LegacyClaim[]>(),[roster,setRoster]=useState<LegacyRoster|null>(null),[sourceKey,setSourceKey]=useState(''),[code,setCode]=useState(''),[selected,setSelected]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [players,setPlayers]=useState<LegacyRosterPlayer[]>([]);const navigate=useNavigate();
 async function load(){setError('');try{const [list,info]=await Promise.all([services.legacyClaims.list(),services.legacyClaims.roster()]);setClaims(list);setRoster(info);if(info&&!info.completed)setPlayers(info.rosterNames.map(ign=>({ign,uid:'',role:'' as LegacyRosterPlayer['role']})));}catch{setError('Məlumat yüklənmədi. Email təsdiqini və sessiyanızı yoxlayın.');}}
 useEffect(()=>{void load();},[]);
 async function run(action:()=>Promise<void>,message:string){setBusy(true);setError('');setNotice('');try{await action();setNotice(message);}catch{setError('Əməliyyat tamamlanmadı. Kod etibarsız, vaxtı bitmiş və ya artıq istifadə edilmiş ola bilər. Sahibliyi və sessiyanı yoxlayıb yenidən cəhd edin.');}finally{setBusy(false);}}
 return <><PageHeader title="Köhnə komanda sahibliyi" description="Email uyğunluğu sahibliyə sübut deyil. Moderator müstəqil yoxlama aparır və birdəfəlik kodu təsdiqlənmiş əvvəlki əlaqə kanalından çatdırır."/>{error&&<div role="alert"><p>{error}</p><Button variant="secondary" onClick={()=>void load()}>Yenidən yüklə</Button></div>}{notice&&<p role="status">{notice}</p>}{!claims&&!error?<LoadingSkeleton variant="table" rows={3}/>:null}
 <form className="account-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await services.legacyClaims.request(sourceKey);await load();},'Sorğu qeydə alındı. Bu bildiriş komandanın mövcudluğunu və ya sahibliyini təsdiqləmir.');}}><Input label="Əvvəlki komanda nömrəsi" inputMode="numeric" pattern="[0-9]{1,19}" maxLength={19} value={sourceKey} onChange={e=>setSourceKey(e.target.value)} required/><Button type="submit" loading={busy}>Sahiblik yoxlaması istə</Button></form>
 {claims?.length? <form className="account-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await services.legacyClaims.consume(selected,code);setCode('');await services.auth.getSession();await load();},'Komanda hesabınıza bağlandı. Turnir qeydiyyatından əvvəl real oyunçu ID-lərini və rollarını tamamlayın.');}}><Select label="Təsdiqlənən sorğu" value={selected} onChange={e=>setSelected(e.target.value)} required><option value="">Sorğunu seçin</option>{claims.map(c=><option key={c.id} value={c.id} disabled={c.status!=='approved'}>{c.sourceKey} · {c.status}</option>)}</Select><Input label="Birdəfəlik sahiblik kodu" value={code} onChange={e=>setCode(e.target.value.trim())} autoComplete="off" minLength={43} maxLength={43} required/><Button type="submit" loading={busy} disabled={!selected}>Komandanı bağla</Button></form>:claims?<EmptyState title="Hələ sahiblik sorğusu yoxdur" body="Əvvəlki qeydiyyat nömrənizlə yoxlama istəyə bilərsiniz."/>:null}
 {roster&&!roster.completed&&<form className="account-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await services.legacyClaims.completeRoster(players);await load();},'Heyət saxlanıldı.');}}><h2>Əvvəlki heyəti tamamla</h2><p>Adlar əvvəlki qeydiyyatdan qorunub. Real PUBG ID-ləri və rolları daxil edin: 1 kapitan, 3 əsas, 1 ehtiyat. ID-lər uydurulmamalıdır.</p>{players.map((p,i)=><fieldset key={i}><legend>{p.ign}</legend><Input label={`${p.ign} — PUBG ID`} value={p.uid} inputMode="numeric" pattern="[0-9]{5,20}" maxLength={20} required onChange={e=>setPlayers(v=>v.map((p,n)=>n===i?{...p,uid:e.target.value}:p))}/><Select label={`${p.ign} — rol`} value={p.role} required onChange={e=>setPlayers(v=>v.map((p,n)=>n===i?{...p,role:e.target.value as LegacyRosterPlayer['role']}:p))}><option value="">Rolu seçin</option><option value="captain">Kapitan</option><option value="starter">Əsas</option><option value="substitute">Ehtiyat</option></Select></fieldset>)}<Button type="submit" loading={busy}>Heyəti saxla</Button></form>}
 {roster&&<><p role="status">Əvvəlki sistemdə match_results boşdur; digər mənbələrdəki tarixçə hələ yoxlanmayıb. Yeni rəsmi nəticələr ayrıca göstərilir.</p><Button onClick={()=>navigate('/team')}>Komanda panelinə keç</Button></>}</>;
}
export function AdminLegacyClaimsPage(){
 const [claims,setClaims]=useState<LegacyClaimReview[]>(),[holdings,setHoldings]=useState<LegacyHolding[]>([]),[error,setError]=useState(''),[selected,setSelected]=useState(''),[evidence,setEvidence]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[issued,setIssued]=useState<{code?:string;expiresAt?:string}>();
 async function load(){setError('');try{const [queue,teams]=await Promise.all([services.legacyClaims.queue(),services.legacyClaims.holdings()]);setClaims(queue);setHoldings(teams);}catch{setError('Sahiblik sorğuları yüklənmədi və ya moderator icazəsi yoxdur.');}}
 useEffect(()=>{void load();},[]);const active=claims?.find(c=>c.id===selected);
 async function review(decision:'approve'|'reject'){if(!active)return;setBusy(true);setIssued(undefined);setError('');try{setIssued(await services.legacyClaims.review(active.id,decision,evidence,active.version));await load();setConfirmed(false);}catch{setError('Qərar saxlanılmadı. Sorğunu yeniləyib yenidən yoxlayın.');}finally{setBusy(false);}}
 return <><PageHeader title="Əvvəlki komandaların sahibliyi" description="Yalnız müstəqil sahiblik sübutu ilə qərar verin. Eyni email və ya kapitan adı kifayət deyil. Öz sorğunuzu təsdiqləyə bilməzsiniz."/>{error&&<div role="alert"><p>{error}</p><Button onClick={()=>void load()}>Yenidən yüklə</Button></div>}{!claims&&!error&&<LoadingSkeleton variant="table" rows={3}/>}
 <section><h2>İdxal edilmiş komandalar · {holdings.length}</h2>{holdings.map(h=><p key={h.teamId}>{h.sourceKey} · {h.name} · {h.status} · {h.legacyStatus}</p>)}{claims?.length===0&&<EmptyState title="Yoxlama sorğusu yoxdur" body="Komandalar sahiblik təsdiqinədək qorunan gözləmə sahəsində saxlanılır."/>}</section>
 {Boolean(claims?.length)&&<form className="account-form" onSubmit={e=>{e.preventDefault();void review('approve');}}><Select label="Sahiblik sorğusu" value={selected} onChange={e=>{setSelected(e.target.value);setConfirmed(false);setEvidence('');setIssued(undefined);}} required><option value="">Sorğunu seçin</option>{claims!.map(c=><option key={c.id} value={c.id} disabled={c.status==='consumed'}>{c.sourceKey} · {c.teamName??'Uyğun idxal yoxdur'} · {c.status}</option>)}</Select>{active&&<><p>Müraciət edən: {active.applicantEmail}</p><p>Əvvəlki təsdiqlənmiş əlaqə: {active.legacyContact?.name} · {active.legacyContact?.email} · {active.legacyContact?.contact}</p><small>Əlaqəni müraciət edənin verdiyi yeni məlumatla əvəz etməyin. Sübut qeydində məxfi məlumat və kod saxlamayın.</small></>}<Input label="Müstəqil yoxlama sübutunun UUID qeydi" value={evidence} onChange={e=>setEvidence(e.target.value)} pattern="[0-9a-fA-F-]{36}" required/><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Sahiblik müstəqil mənbədən yoxlanılıb; kod yalnız həmin təsdiqlənmiş əvvəlki kanal vasitəsilə çatdırılacaq.</label><Button type="submit" loading={busy} disabled={!active?.teamName||active.claimed||!confirmed}>Təsdiqlə və kod yarat</Button><Button type="button" variant="secondary" loading={busy} disabled={!active||!evidence.match(/^[0-9a-fA-F-]{36}$/)} onClick={()=>void review('reject')}>Rədd et / kodu ləğv et</Button></form>}
 {issued?.code&&<section role="status"><h2>Birdəfəlik kod — yalnız bu dəfə göstərilir</h2><p>Kodu təsdiqlənmiş əvvəlki əlaqə kanalından çatdırın. Müraciət forması və ümumi bildirişlə göndərməyin.</p><code style={{overflowWrap:'anywhere'}}>{issued.code}</code><p>Bitmə vaxtı: {issued.expiresAt}</p><Button variant="secondary" onClick={()=>setIssued(undefined)}>Kodu ekrandan sil</Button></section>}</>;
}
