import { EVIDENCE_UPLOAD_TYPES } from '../utils/fileValidation';
import { AlertTriangle, Image } from 'lucide-react';
import { type FormEvent, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button, EmptyState, FileUpload, Input, PageHeader, Select, Textarea, Toast } from '../components/common/primitives';
import { competitionNow, services } from '../services';
import { selectDisputeDeadline, selectLatestPublishedMatch } from '../utils/competitionSelectors';
import { useTeamPlatformData } from '../services/PlatformDataContext';
import type { ResultDispute } from '../types/domain';

export function NewDisputePage() {
  const { currentTeam, tournaments, matchHistory } = useTeamPlatformData(); const navigate = useNavigate(); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [evidence, setEvidence] = useState<string[]>([]);
  const [selectedMatchId, setSelectedMatchId] = useState(() => selectLatestPublishedMatch(matchHistory)?.id ?? '');
  const match = matchHistory.find(item => item.id === selectedMatchId); const tournament = tournaments.find((item) => item.id === match?.tournamentId);
  const deadline = match && tournament ? selectDisputeDeadline(match, tournament) : undefined;
  const canSubmit = Boolean(deadline && competitionNow().getTime() <= Date.parse(deadline));
  if (!match || !tournament) return <><PageHeader eyebrow="Nəticə etirazı" title="Etiraz üçün nəticə yoxdur" description="Yalnız dərc edilmiş matç nəticəsinə etiraz göndərilə bilər." /><EmptyState title="Dərc edilmiş matç tapılmadı" body="Nəticə dərc edildikdən sonra etiraz forması aktiv olacaq." action={<Link className="button button--secondary" to="/team/disputes"><span>Etirazlara qayıt</span></Link>} /></>;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (loading || !canSubmit || !deadline) return; const form = new FormData(event.currentTarget); setLoading(true); setError(''); try { const item = await services.disputes.submit({ teamId: currentTeam.id, teamName: currentTeam.name, tournamentId: tournament.id, tournamentName: tournament.name, matchId: match.id, roundLabel: match.stageLabel, issueType: form.get('issueType') as ResultDispute['issueType'], description: String(form.get('description') ?? ''), evidenceNames: evidence, deadlineAt: deadline }); navigate(`/team/disputes/${item.id}`); } catch { setError('Etiraz göndərilmədi. Məlumatlarınızı yoxlayıb yenidən cəhd edin.'); } finally { setLoading(false); } };
  return <><PageHeader eyebrow="// NƏTİCƏ ETİRAZI" title="Nəticəyə etiraz et" description="Yalnız faktiki uyğunsuzluğu və onu göstərən sübutu göndərin." />{error && <Toast tone="error" title="Etiraz tamamlanmadı" body={error} />}<form className="operation-form" onSubmit={submit}><div className="form-grid"><Input label="Turnir" value={tournament.name} disabled /><Select label="Matç / raund" value={selectedMatchId} onChange={event => { setSelectedMatchId(event.target.value); setEvidence([]); }}>{[...matchHistory].sort((a, b) => Date.parse(b.playedAt) - Date.parse(a.playedAt)).map(item => <option key={item.id} value={item.id}>{item.tournamentName} · {item.stageLabel} · {item.map}</option>)}</Select></div><Select name="issueType" label="Problem növü" defaultValue="kills"><option value="placement">Placement</option><option value="kills">Kill sayı</option><option value="penalty">Penalty</option><option value="missing-result">Nəticə yoxdur</option><option value="other">Digər</option></Select><Textarea name="description" label="Təsvir" placeholder="Nəyin səhv olduğunu və gözlənilən düzgün nəticəni faktlarla yazın." minLength={20} required /><FileUpload accept={EVIDENCE_UPLOAD_TYPES} maxBytes={4 * 1024 * 1024} label="Sübut əlavə et" hint="PNG, JPG və ya PDF · bu axında yalnız fayl adı qeyd olunur, fayl yüklənmir" onFile={(file) => setEvidence((current) => [...current, file.name])} />{evidence.length > 0 && <div className="evidence-list"><Image size={18} />{evidence.join(', ')}</div>}<div className="deadline-note"><AlertTriangle size={18} /><span>{deadline ? `Etiraz müddəti: ${new Date(deadline).toLocaleString('az-AZ', { timeZone: 'Asia/Baku' })}${canSubmit ? '' : ' · Müddət bitib'}` : 'Etiraz müddəti mənbədə göstərilməyib. Göndərmə əlçatan deyil.'}</span></div><Button type="submit" loading={loading} disabled={!canSubmit}>Etirazı göndər</Button></form></>;
}
