import { ArrowLeft, ArrowRight, Bell, CheckCircle2, FileClock, Gavel, RefreshCcw } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, EmptyState, LoadingSkeleton, NotificationItem, PageHeader, SectionHeading, StatusBadge, Tabs, TeamLogo, Textarea, Toast } from '../components/common/primitives';
import { services } from '../services';
import { useTeamPlatformData } from '../services/PlatformDataContext';
import { updateCachedQuery } from '../services/queryCache';
import type { Notification, ResultDispute, RosterChangeRequest, TeamPlatformSnapshot } from '../types/domain';

export function NotificationCenterPage() {
  const snapshot = useTeamPlatformData();
  const [items, setItems] = useState<Notification[]>(snapshot.notifications); const [filter, setFilter] = useState('all'); const [notice, setNotice] = useState(''); const [nextCursor, setNextCursor] = useState<string>(); const [loadingMore, setLoadingMore] = useState(false);
  const [historyLoaded, setHistoryLoaded] = useState(false);

  const visible = filter === 'unread' ? items.filter((item) => !item.read) : items;
  const markRead = async (id: string) => { try { await services.notifications.markRead(id); updateCachedQuery<TeamPlatformSnapshot>('snapshot:team', value => ({ ...value, notifications: value.notifications.map(item => item.id === id ? { ...item, read: true } : item) })); setItems((current) => current.map((item) => item.id === id ? { ...item, read: true } : item)); } catch { setNotice('Bildiriş yenilənmədi. Yenidən cəhd edin.'); } };
  const markAll = async () => { try { await services.notifications.markAllRead(); updateCachedQuery<TeamPlatformSnapshot>('snapshot:team', value => ({ ...value, notifications: value.notifications.map(item => ({ ...item, read: true })) })); setItems((current) => current.map((item) => ({ ...item, read: true }))); setNotice('Bütün bildirişlər oxunmuş kimi işarələndi.'); } catch { setNotice('Bildirişlər yenilənmədi. Yenidən cəhd edin.'); } };
  const loadMore = async () => { if (historyLoaded && !nextCursor) return; setLoadingMore(true); try { const page = await services.notifications.page(nextCursor); setItems((current) => [...current, ...page.items.filter((item) => !current.some((existing) => existing.id === item.id))]); setNextCursor(page.nextCursor); setHistoryLoaded(true); } catch { setNotice('Əlavə bildirişlər yüklənmədi.'); } finally { setLoadingMore(false); } };
  return <><PageHeader eyebrow="// SİSTEM HADİSƏLƏRİ" title="Bildiriş mərkəzi" description="Qeydiyyat, check-in, room, nəticə və roster hadisələri. Admin mesajları ayrıca inbox-dadır." actions={<Button variant="secondary" onClick={() => void markAll()} disabled={!items.some((item) => !item.read)}>Hamısını oxunmuş et</Button>} />{notice && <Toast title={notice} onClose={() => setNotice('')} />}<Tabs active={filter} onChange={setFilter} items={[{ id: 'all', label: 'Hamısı', count: items.length }, { id: 'unread', label: 'Oxunmamış', count: items.filter((item) => !item.read).length }]} />{visible.length ? <><div className="notification-center-list">{visible.map((item) => <div key={item.id} ><NotificationItem item={item} />{!item.read && <Button variant="ghost" onClick={() => void markRead(item.id)}>Oxunmuş et</Button>}</div>)}</div>{(!historyLoaded || nextCursor) && <Button variant="secondary" loading={loadingMore} onClick={() => void loadMore()}>Daha çox göstər</Button>}</> : <EmptyState icon={<Bell size={26} />} title="Yeni bildiriş yoxdur" body={filter === 'unread' ? 'Bütün bildirişlər oxunub.' : 'Sistem hadisələri yarandıqda burada görünəcək.'} />}</>;
}

function requestStatus(status: RosterChangeRequest['status']) {
  return status === 'approved' ? 'approved' : status === 'rejected' ? 'rejected' : status === 'under-review' ? 'warning' : 'pending';
}

export function RosterRequestsPage() {
  const { currentTeam } = useTeamPlatformData(); const [items, setItems] = useState<RosterChangeRequest[]>(); const [loadError, setLoadError] = useState(false);
  useEffect(() => { services.rosterRequests.list(currentTeam.id).then(setItems).catch(() => setLoadError(true)); }, [currentTeam.id]);
  return <><PageHeader eyebrow="// HEYƏT NƏZARƏTİ" title="Heyət dəyişiklik sorğuları" description="Kilidli dövrdə heyət səssizcə dəyişmir. Hər sorğu səbəb, status və admin qeydi saxlayır." actions={<Link className="button button--primary" to="/team/roster"><span>Yeni sorğu</span></Link>} />{loadError ? <EmptyState title="Məlumat yüklənmədi" body="Sorğu xidməti cavab vermir. Səhifəni yeniləyib cəhd edin." /> : !items ? <LoadingSkeleton rows={5} /> : items.length ? <div className="request-ledger">{items.map((item) => <Link to={`/team/roster-requests/${item.id}`} key={item.id}><span><FileClock size={19} />{item.id}</span><div><strong>{item.outgoing.ign} → {item.incoming.ign}</strong><small>{item.tournamentName ?? 'Ümumi roster'} · {new Date(item.submittedAt).toLocaleDateString('az-AZ')}</small></div><StatusBadge status={requestStatus(item.status)}>{item.status}</StatusBadge><ArrowRight size={17} /></Link>)}</div> : <EmptyState title="Roster sorğusu yoxdur" body="Kilidli roster üçün dəyişiklik başladıqda sorğu burada görünəcək." />}</>;
}

export function RosterRequestDetailPage({ admin = false }: { admin?: boolean }) {
  const { requestId = '' } = useParams(); const [item, setItem] = useState<RosterChangeRequest>(); const [loading, setLoading] = useState(true); const [note, setNote] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { services.rosterRequests.get(requestId).then((value) => { setItem(value); setNote(value?.adminNote ?? ''); }).catch(() => setNotice('Məlumat yüklənmədi. Səhifəni yeniləyib cəhd edin.')).finally(() => setLoading(false)); }, [requestId]);
  const review = async (status: 'approved' | 'rejected') => { if (!item) return; const next = await services.rosterRequests.review(item.id, status, note); setItem(next); setNotice(status === 'approved' ? 'Roster sorğusu təsdiqləndi.' : 'Roster sorğusu rədd edildi.'); };
  if (loading) return <LoadingSkeleton rows={6} />;
  if (!item) return <EmptyState title="Sorğu tapılmadı" body={notice || "Bu heyət sorğusu mövcud deyil və ya sizə aid deyil."} />;
  return <><Link className="text-link" to={admin ? '/admin/roster-requests' : '/team/roster-requests'}><ArrowLeft size={16} />Sorğular</Link><PageHeader eyebrow={item.id} title="Heyət dəyişikliyi" description={`${item.teamName} · ${item.tournamentName ?? 'Ümumi roster'}`} actions={<StatusBadge status={requestStatus(item.status)}>{item.status}</StatusBadge>} />{notice && <Toast title={notice} onClose={() => setNotice('')} />}<div className="request-detail-grid"><section><SectionHeading title="Dəyişiklik" /><div className="replacement-pair"><div><span>ÇIXAN OYUNÇU</span><TeamLogo name={item.outgoing.ign} /><strong>{item.outgoing.ign}</strong><small>{item.outgoing.role}</small></div><RefreshCcw size={21} /><div><span>YENİ OYUNÇU</span><TeamLogo name={item.incoming.ign} /><strong>{item.incoming.ign}</strong><small>{item.incoming.role} · UID {item.incoming.uid ?? '—'}</small></div></div><dl className="detail-ledger"><div><dt>Səbəb</dt><dd>{item.reason}</dd></div><div><dt>Göndərilib</dt><dd>{new Date(item.submittedAt).toLocaleString('az-AZ')}</dd></div><div><dt>Son yenilənmə</dt><dd>{new Date(item.updatedAt).toLocaleString('az-AZ')}</dd></div></dl></section><aside><SectionHeading title="Admin qeydi" />{admin ? <><Textarea label="Qərar qeydi" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Qərarın faktiki səbəbi" /><div className="decision-actions"><Button onClick={() => void review('approved')}>Təsdiqlə</Button><Button variant="danger" onClick={() => void review('rejected')}>Rədd et</Button></div></> : <p>{item.adminNote ?? 'Admin qeydi hələ yoxdur.'}</p>}</aside></div></>;
}

function disputeStatus(status: ResultDispute['status']) { return status === 'resolved' ? 'approved' : status === 'rejected' ? 'rejected' : 'warning'; }

export function DisputesPage() {
  const { currentTeam } = useTeamPlatformData(); const [items, setItems] = useState<ResultDispute[]>(); const [loadError, setLoadError] = useState(false);
  useEffect(() => { services.disputes.list(currentTeam.id).then(setItems).catch(() => setLoadError(true)); }, [currentTeam.id]);
  return <><PageHeader eyebrow="// RƏSMİ NƏTİCƏ YOXLAMASI" title="Nəticə etirazları" description="Etiraz müddətində göndərilən etirazlar sübut və qərar tarixçəsi ilə izlənir." actions={<Link className="button button--primary" to="/team/disputes/new"><span>Nəticəyə etiraz et</span></Link>} />{loadError ? <EmptyState title="Məlumat yüklənmədi" body="Sorğu xidməti cavab vermir. Səhifəni yeniləyib cəhd edin." /> : !items ? <LoadingSkeleton rows={5} /> : items.length ? <div className="request-ledger">{items.map((item) => <Link to={`/team/disputes/${item.id}`} key={item.id}><span><Gavel size={19} />{item.id}</span><div><strong>{item.tournamentName} · {item.roundLabel}</strong><small>{item.issueType} · {new Date(item.submittedAt).toLocaleDateString('az-AZ')}</small></div><StatusBadge status={disputeStatus(item.status)}>{item.status}</StatusBadge><ArrowRight size={17} /></Link>)}</div> : <EmptyState icon={<Gavel size={26} />} title="Etiraz yoxdur" body="Dərc edilmiş nəticə ilə bağlı etiraz göndərdikdə burada görünəcək." />}</>;
}

export function DisputeDetailPage({ admin = false }: { admin?: boolean }) {
  const { disputeId = '' } = useParams(); const [item, setItem] = useState<ResultDispute>(); const [loading, setLoading] = useState(true); const [note, setNote] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { services.disputes.get(disputeId).then((value) => { setItem(value); setNote(value?.adminNote ?? ''); }).catch(() => setNotice('Məlumat yüklənmədi. Səhifəni yeniləyib cəhd edin.')).finally(() => setLoading(false)); }, [disputeId]);
  const review = async (status: 'resolved' | 'rejected') => { if (!item) return; const next = await services.disputes.review(item.id, status, note); setItem(next); setNotice(status === 'resolved' ? 'Etiraz həll edildi.' : 'Etiraz rədd edildi.'); };
  if (loading) return <LoadingSkeleton rows={6} />;
  if (!item) return <EmptyState title="Etiraz tapılmadı" body={notice || "Bu etiraz mövcud deyil və ya sizə aid deyil."} />;
  return <><Link className="text-link" to={admin ? '/admin/disputes' : '/team/disputes'}><ArrowLeft size={16} />Etirazlar</Link><PageHeader eyebrow={item.id} title={item.tournamentName} description={item.roundLabel} actions={<StatusBadge status={disputeStatus(item.status)}>{item.status}</StatusBadge>} />{notice && <Toast title={notice} onClose={() => setNotice('')} />}<div className="request-detail-grid"><section><SectionHeading title="Etiraz məlumatı" /><dl className="detail-ledger"><div><dt>Komanda</dt><dd>{item.teamName}</dd></div><div><dt>Problem</dt><dd>{item.issueType}</dd></div><div><dt>Təsvir</dt><dd>{item.description}</dd></div><div><dt>Sübut</dt><dd>{item.evidenceNames.length ? item.evidenceNames.join(', ') : 'Əlavə edilməyib'}</dd></div><div><dt>Son müddət</dt><dd>{new Date(item.deadlineAt).toLocaleString('az-AZ')}</dd></div></dl></section><aside><SectionHeading title="Qərar" />{admin ? <><Textarea label="Admin qeydi" value={note} onChange={(event) => setNote(event.target.value)} required /><div className="decision-actions"><Button onClick={() => void review('resolved')} icon={<CheckCircle2 size={17} />}>Həll et</Button><Button variant="danger" onClick={() => void review('rejected')}>Rədd et</Button></div></> : <p>{item.adminNote ?? 'Etiraz admin yoxlamasındadır.'}</p>}</aside></div></>;
}
