import { EVIDENCE_UPLOAD_TYPES } from '../utils/fileValidation';
import { AlertTriangle, ArrowLeft, ArrowRight, Bell, CheckCircle2, FileClock, Gavel, Image, RefreshCcw, Swords } from 'lucide-react';
import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, EmptyState, FileUpload, Input, LoadingSkeleton, NotificationItem, PageHeader, SectionHeading, Select, StatusBadge, Tabs, TeamLogo, Textarea, Toast } from '../components/common/primitives';
import { competitionNow, services } from '../services';
import { selectDisputeDeadline, selectLatestPublishedMatch } from '../utils/competitionSelectors';
import { useTeamPlatformData } from '../services/PlatformDataContext';
import type { Notification, ResultDispute, RosterChangeRequest } from '../types/domain';

export function NotificationCenterPage() {
  const snapshot = useTeamPlatformData();
  const [items, setItems] = useState<Notification[]>(snapshot.notifications); const [filter, setFilter] = useState('all'); const [notice, setNotice] = useState(''); const [nextCursor, setNextCursor] = useState<string>(); const [loadingMore, setLoadingMore] = useState(false);
  useEffect(() => { services.notifications.page().then((page) => { setItems(page.items); setNextCursor(page.nextCursor); }).catch(() => setNotice('Bildiriş servisi yenilənmədi; son snapshot göstərilir.')); }, []);
  const visible = filter === 'unread' ? items.filter((item) => !item.read) : items;
  const markRead = async (id: string) => { await services.notifications.markRead(id); setItems((current) => current.map((item) => item.id === id ? { ...item, read: true } : item)); };
  const markAll = async () => { await services.notifications.markAllRead(); setItems((current) => current.map((item) => ({ ...item, read: true }))); setNotice('Bütün bildirişlər oxunmuş kimi işarələndi.'); };
  const loadMore = async () => { if (!nextCursor) return; setLoadingMore(true); try { const page = await services.notifications.page(nextCursor); setItems((current) => [...current, ...page.items.filter((item) => !current.some((existing) => existing.id === item.id))]); setNextCursor(page.nextCursor); } finally { setLoadingMore(false); } };
  return <><PageHeader eyebrow="System events" title="Bildiriş mərkəzi" description="Qeydiyyat, check-in, room, nəticə və roster hadisələri. Admin mesajları ayrıca inbox-dadır." actions={<Button variant="secondary" onClick={() => void markAll()} disabled={!items.some((item) => !item.read)}>Hamısını oxunmuş et</Button>} />{notice && <Toast title={notice} onClose={() => setNotice('')} />}<Tabs active={filter} onChange={setFilter} items={[{ id: 'all', label: 'Hamısı', count: items.length }, { id: 'unread', label: 'Oxunmamış', count: items.filter((item) => !item.read).length }]} />{visible.length ? <><div className="notification-center-list">{visible.map((item) => <div key={item.id} onClick={() => { if (!item.read) void markRead(item.id); }}><NotificationItem item={item} />{!item.read && <Button variant="ghost" onClick={() => void markRead(item.id)}>Oxunmuş et</Button>}</div>)}</div>{nextCursor && <Button variant="secondary" loading={loadingMore} onClick={() => void loadMore()}>Daha çox göstər</Button>}</> : <EmptyState icon={<Bell size={26} />} title="Yeni bildiriş yoxdur" body={filter === 'unread' ? 'Bütün bildirişlər oxunub.' : 'Sistem hadisələri yarandıqda burada görünəcək.'} />}</>;
}

function requestStatus(status: RosterChangeRequest['status']) {
  return status === 'approved' ? 'approved' : status === 'rejected' ? 'rejected' : status === 'under-review' ? 'warning' : 'pending';
}

export function RosterRequestsPage() {
  const { currentTeam } = useTeamPlatformData(); const [items, setItems] = useState<RosterChangeRequest[]>();
  useEffect(() => { services.rosterRequests.list(currentTeam.id).then(setItems); }, [currentTeam.id]);
  return <><PageHeader eyebrow="Roster control" title="Roster dəyişiklik sorğuları" description="Kilidli dövrdə heyət səssizcə dəyişmir. Hər sorğu səbəb, status və admin qeydi saxlayır." actions={<Link className="button button--primary" to="/team/roster"><span>Yeni sorğu</span></Link>} />{!items ? <LoadingSkeleton rows={5} /> : items.length ? <div className="request-ledger">{items.map((item) => <Link to={`/team/roster-requests/${item.id}`} key={item.id}><span><FileClock size={19} />{item.id}</span><div><strong>{item.outgoing.ign} → {item.incoming.ign}</strong><small>{item.tournamentName ?? 'Ümumi roster'} · {new Date(item.submittedAt).toLocaleDateString('az-AZ')}</small></div><StatusBadge status={requestStatus(item.status)}>{item.status}</StatusBadge><ArrowRight size={17} /></Link>)}</div> : <EmptyState title="Roster sorğusu yoxdur" body="Kilidli roster üçün dəyişiklik başladıqda sorğu burada görünəcək." />}</>;
}

export function RosterRequestDetailPage({ admin = false }: { admin?: boolean }) {
  const { requestId = '' } = useParams(); const [item, setItem] = useState<RosterChangeRequest>(); const [loading, setLoading] = useState(true); const [note, setNote] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { services.rosterRequests.get(requestId).then((value) => { setItem(value); setNote(value?.adminNote ?? ''); }).finally(() => setLoading(false)); }, [requestId]);
  const review = async (status: 'approved' | 'rejected') => { if (!item) return; const next = await services.rosterRequests.review(item.id, status, note); setItem(next); setNotice(status === 'approved' ? 'Roster sorğusu təsdiqləndi.' : 'Roster sorğusu rədd edildi.'); };
  if (loading) return <LoadingSkeleton rows={6} />;
  if (!item) return <EmptyState title="Sorğu tapılmadı" body="Bu roster sorğusu mövcud deyil və ya sizə aid deyil." />;
  return <><Link className="text-link" to={admin ? '/admin/roster-requests' : '/team/roster-requests'}><ArrowLeft size={16} />Sorğular</Link><PageHeader eyebrow={item.id} title="Roster dəyişikliyi" description={`${item.teamName} · ${item.tournamentName ?? 'Ümumi roster'}`} actions={<StatusBadge status={requestStatus(item.status)}>{item.status}</StatusBadge>} />{notice && <Toast title={notice} onClose={() => setNotice('')} />}<div className="request-detail-grid"><section><SectionHeading title="Dəyişiklik" /><div className="replacement-pair"><div><span>Outgoing</span><TeamLogo name={item.outgoing.ign} /><strong>{item.outgoing.ign}</strong><small>{item.outgoing.role}</small></div><RefreshCcw size={21} /><div><span>Incoming</span><TeamLogo name={item.incoming.ign} /><strong>{item.incoming.ign}</strong><small>{item.incoming.role} · UID {item.incoming.uid ?? '—'}</small></div></div><dl className="detail-ledger"><div><dt>Səbəb</dt><dd>{item.reason}</dd></div><div><dt>Göndərilib</dt><dd>{new Date(item.submittedAt).toLocaleString('az-AZ')}</dd></div><div><dt>Son yenilənmə</dt><dd>{new Date(item.updatedAt).toLocaleString('az-AZ')}</dd></div></dl></section><aside><SectionHeading title="Admin qeydi" />{admin ? <><Textarea label="Qərar qeydi" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Qərarın faktiki səbəbi" /><div className="decision-actions"><Button onClick={() => void review('approved')}>Təsdiqlə</Button><Button variant="danger" onClick={() => void review('rejected')}>Rədd et</Button></div></> : <p>{item.adminNote ?? 'Admin qeydi hələ yoxdur.'}</p>}</aside></div></>;
}

function disputeStatus(status: ResultDispute['status']) { return status === 'resolved' ? 'approved' : status === 'rejected' ? 'rejected' : 'warning'; }

export function DisputesPage() {
  const { currentTeam } = useTeamPlatformData(); const [items, setItems] = useState<ResultDispute[]>();
  useEffect(() => { services.disputes.list(currentTeam.id).then(setItems); }, [currentTeam.id]);
  return <><PageHeader eyebrow="Result review" title="Nəticə etirazları" description="Deadline daxilində göndərilən etirazlar sübut və qərar tarixçəsi ilə izlənir." actions={<Link className="button button--primary" to="/team/disputes/new"><span>Nəticəyə etiraz et</span></Link>} />{!items ? <LoadingSkeleton rows={5} /> : items.length ? <div className="request-ledger">{items.map((item) => <Link to={`/team/disputes/${item.id}`} key={item.id}><span><Gavel size={19} />{item.id}</span><div><strong>{item.tournamentName} · {item.roundLabel}</strong><small>{item.issueType} · {new Date(item.submittedAt).toLocaleDateString('az-AZ')}</small></div><StatusBadge status={disputeStatus(item.status)}>{item.status}</StatusBadge><ArrowRight size={17} /></Link>)}</div> : <EmptyState icon={<Gavel size={26} />} title="Etiraz yoxdur" body="Dərc edilmiş nəticə ilə bağlı etiraz göndərdikdə burada görünəcək." />}</>;
}

export function NewDisputePage() {
  const { currentTeam, tournaments, matchHistory } = useTeamPlatformData(); const navigate = useNavigate(); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [evidence, setEvidence] = useState<string[]>([]);
  const match = selectLatestPublishedMatch(matchHistory); const tournament = tournaments.find((item) => item.id === match?.tournamentId);
  const deadline = match && tournament ? selectDisputeDeadline(match, tournament) : undefined;
  const canSubmit = Boolean(deadline && competitionNow().getTime() <= Date.parse(deadline));
  if (!match || !tournament) return <><PageHeader eyebrow="Nəticə etirazı" title="Etiraz üçün nəticə yoxdur" description="Yalnız dərc edilmiş matç nəticəsinə etiraz göndərilə bilər." /><EmptyState title="Dərc edilmiş matç tapılmadı" body="Nəticə dərc edildikdən sonra etiraz forması aktiv olacaq." action={<Link className="button button--secondary" to="/team/disputes"><span>Etirazlara qayıt</span></Link>} /></>;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (loading || !canSubmit || !deadline) return; const form = new FormData(event.currentTarget); setLoading(true); setError(''); try { const item = await services.disputes.submit({ teamId: currentTeam.id, teamName: currentTeam.name, tournamentId: tournament.id, tournamentName: tournament.name, matchId: match.id, roundLabel: match.stageLabel, issueType: form.get('issueType') as ResultDispute['issueType'], description: String(form.get('description') ?? ''), evidenceNames: evidence, deadlineAt: deadline }); navigate(`/team/disputes/${item.id}`); } catch { setError('Etiraz göndərilmədi. Məlumatlarınızı yoxlayıb yenidən cəhd edin.'); } finally { setLoading(false); } };
  return <><PageHeader eyebrow="Result dispute" title="Nəticəyə etiraz et" description="Yalnız faktiki uyğunsuzluğu və onu göstərən sübutu göndərin." />{error && <Toast tone="error" title="Etiraz tamamlanmadı" body={error} />}<form className="operation-form" onSubmit={submit}><div className="form-grid"><Input label="Turnir" value={tournament.name} disabled /><Input label="Raund" value={match.stageLabel} disabled /></div><Select name="issueType" label="Problem növü" defaultValue="kills"><option value="placement">Placement</option><option value="kills">Kill sayı</option><option value="penalty">Penalty</option><option value="missing-result">Nəticə yoxdur</option><option value="other">Digər</option></Select><Textarea name="description" label="Təsvir" placeholder="Nəyin səhv olduğunu və gözlənilən düzgün nəticəni faktlarla yazın." minLength={20} required /><FileUpload accept={EVIDENCE_UPLOAD_TYPES} maxBytes={4 * 1024 * 1024} label="Sübut əlavə et" hint="PNG, JPG və ya PDF · frontend yalnız fayl adını göstərir; backend scan tələb olunur" onFile={(file) => setEvidence((current) => [...current, file.name])} />{evidence.length > 0 && <div className="evidence-list"><Image size={18} />{evidence.join(', ')}</div>}<div className="deadline-note"><AlertTriangle size={18} /><span>{deadline ? `Etiraz müddəti: ${new Date(deadline).toLocaleString('az-AZ', { timeZone: 'Asia/Baku' })}${canSubmit ? '' : ' · Müddət bitib'}` : 'Etiraz müddəti mənbədə göstərilməyib. Göndərmə əlçatan deyil.'}</span></div><Button type="submit" loading={loading} disabled={!canSubmit}>Etirazı göndər</Button></form></>;
}

export function DisputeDetailPage({ admin = false }: { admin?: boolean }) {
  const { disputeId = '' } = useParams(); const [item, setItem] = useState<ResultDispute>(); const [loading, setLoading] = useState(true); const [note, setNote] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { services.disputes.get(disputeId).then((value) => { setItem(value); setNote(value?.adminNote ?? ''); }).finally(() => setLoading(false)); }, [disputeId]);
  const review = async (status: 'resolved' | 'rejected') => { if (!item) return; const next = await services.disputes.review(item.id, status, note); setItem(next); setNotice(status === 'resolved' ? 'Etiraz həll edildi.' : 'Etiraz rədd edildi.'); };
  if (loading) return <LoadingSkeleton rows={6} />;
  if (!item) return <EmptyState title="Etiraz tapılmadı" body="Bu etiraz mövcud deyil və ya sizə aid deyil." />;
  return <><Link className="text-link" to={admin ? '/admin/disputes' : '/team/disputes'}><ArrowLeft size={16} />Etirazlar</Link><PageHeader eyebrow={item.id} title={item.tournamentName} description={item.roundLabel} actions={<StatusBadge status={disputeStatus(item.status)}>{item.status}</StatusBadge>} />{notice && <Toast title={notice} onClose={() => setNotice('')} />}<div className="request-detail-grid"><section><SectionHeading title="Etiraz məlumatı" /><dl className="detail-ledger"><div><dt>Komanda</dt><dd>{item.teamName}</dd></div><div><dt>Problem</dt><dd>{item.issueType}</dd></div><div><dt>Təsvir</dt><dd>{item.description}</dd></div><div><dt>Sübut</dt><dd>{item.evidenceNames.length ? item.evidenceNames.join(', ') : 'Əlavə edilməyib'}</dd></div><div><dt>Deadline</dt><dd>{new Date(item.deadlineAt).toLocaleString('az-AZ')}</dd></div></dl></section><aside><SectionHeading title="Qərar" />{admin ? <><Textarea label="Admin qeydi" value={note} onChange={(event) => setNote(event.target.value)} required /><div className="decision-actions"><Button onClick={() => void review('resolved')} icon={<CheckCircle2 size={17} />}>Həll et</Button><Button variant="danger" onClick={() => void review('rejected')}>Rədd et</Button></div></> : <p>{item.adminNote ?? 'Etiraz admin yoxlamasındadır.'}</p>}</aside></div></>;
}
