import type { Repository } from './data';
import type { Organization,TeamAchievement } from '../../src/types/domain';
import { dbError } from '../errors';
export async function organizations(repo:Repository):Promise<Organization[]>{const [orgs,links,teams]=await Promise.all([repo.rows('organizations'),repo.rows('organization_teams'),repo.teams()]);return orgs.map(o=>({id:String(o.id),slug:String(o.slug),name:String(o.name),shortName:String(o.short_name),description:String(o.description),country:String(o.country),foundedAt:o.founded_at?String(o.founded_at):undefined,createdAt:String(o.created_at),updatedAt:String(o.updated_at),verificationLevel:o.verification_level as Organization['verificationLevel'],socialLinks:o.social_links as Organization['socialLinks'],featuredAchievements:[],ownedTeams:links.filter(l=>l.organization_id===o.id).flatMap(l=>{const t=teams.find(t=>t.id===l.team_id);return t?[{id:t.id,teamId:t.id,slug:t.slug!,displayName:t.name,organizationId:String(o.id),gameKey:'pubg-mobile',status:'active' as const,joinedAt:String(l.created_at)}]:[]})}));}
export async function achievements(repo:Repository,teamId:string):Promise<TeamAchievement[]>{await repo.team(teamId);const{data,error}=await repo.db.rpc('achievement_progress',{team:teamId});dbError(error);const featured=await repo.rows('featured_achievements');const definitions:Record<string,Pick<TeamAchievement,'title'|'description'|'category'|'icon'|'tier'>>={
 'first-wwcd':{title:'İlk WWCD',description:'Bir rəsmi matçda birinci yeri tutun.',category:'competition',icon:'trophy',tier:'bronze'},
 'hundred-kills':{title:'100 kill',description:'Rəsmi matçlarda 100 kill toplayın.',category:'combat',icon:'crosshair',tier:'silver'},
 'ten-matches':{title:'10 rəsmi matç',description:'On rəsmi matçda iştirak edin.',category:'participation',icon:'medal',tier:'bronze'},
};return(data as Array<{id:string;current_value:number;target:number;unlocked_at?:string}>).map(a=>({...definitions[a.id],id:a.id,rarity:'standard',state:a.current_value>=a.target?'unlocked':a.current_value?'progress':'locked',unlockedAt:a.unlocked_at??undefined,featured:featured.some(f=>f.team_id===teamId&&f.achievement_id===a.id),displayOrder:Number(featured.find(f=>f.team_id===teamId&&f.achievement_id===a.id)?.position??99),progress:{current:Number(a.current_value),target:Number(a.target),unit:a.id==='hundred-kills'?'kill':a.id==='first-wwcd'?'WWCD':'matç'}}));}
