-- Synthetic legacy shape only; no production identities or data.
create table public.teams (
 id bigint generated by default as identity primary key, team_name text not null,
 captain_name text not null,captain_contact text not null,email text not null,password_hash text not null,
 player1_ign text not null,player2_ign text not null,player3_ign text not null,player4_ign text not null,player5_ign text,
 logo_url text,tier text not null default 'entry',status text not null default 'pending',room_id text,room_password text,
 match_results jsonb not null default '[]',created_at timestamptz not null default now(),reset_token text,rejection_reason text,
 player1_photo_url text,player2_photo_url text,player3_photo_url text,player4_photo_url text,player5_photo_url text
);
