import {test} from 'node:test';
import assert from 'node:assert/strict';
import {planImport,validateTarget,stableId,productionRef} from '../../scripts/legacy-migration/core.mjs';
import {fixture,rebind} from './fixtures.mjs';
test('preserves reviewed Auth UUID and creates stable team/player mappings',()=>{const {source,review}=fixture();const a=planImport(source,review),b=planImport(source,review);assert.deepEqual(a,b);assert.equal(a.ready[0].ownerId,review.teams[0].ownerUserId);assert.equal(a.ready[0].players.length,5);assert.equal(a.ready[0].teamId,stableId(source.source.projectRef,'team','legacy-1'));});
test('report contains only hashes, counts and reason codes',()=>{const {source,review}=fixture();const report=JSON.stringify(planImport(source,review).report);for(const privateValue of ['Migrated test team','Test player','100001',review.teams[0].ownerUserId,'legacy-1'])assert.equal(report.includes(privateValue),false);});
test('missing ownership holds records instead of inventing users',()=>{const {source,review}=fixture();review.teams=[];const p=planImport(source,review);assert.equal(p.ready.length,0);assert.equal(p.report.counts.held,1);});
test('missing player name holds the whole team',()=>{const {source,review}=fixture();source.rows[0].player2_ign=null;rebind(source,review);assert.equal(planImport(source,review).report.counts.held,1);});
test('duplicate team names hold all involved teams',()=>{const {source,review}=fixture();source.rows.push({...source.rows[0],id:'legacy-2'});rebind(source,review);const p=planImport(source,review);assert.equal(p.ready.length,0);assert.equal(p.report.counts.held,2);});
test('conflicting owner and player identities hold all involved teams',()=>{const {source,review}=fixture();source.rows.push({...source.rows[0],id:'legacy-2',team_name:'Distinct test name'});review.teams.push({...review.teams[0],sourceId:'legacy-2'});rebind(source,review);const p=planImport(source,review);assert.equal(p.ready.length,0);assert.ok(p.report.records.every(r=>r.reasons.includes('CONFLICTING_OWNER')&&r.reasons.includes('CONFLICTING_PLAYER_IDENTITY')));});
test('unexpected source schema and unsupported historical tables stop import',()=>{const {source,review}=fixture();assert.throws(()=>planImport({...source,tournaments:[]},review),/UNEXPECTED_SOURCE/);source.columns=[...source.columns,'captain_id'];rebind(source,review);assert.throws(()=>planImport(source,review),/SOURCE_SCHEMA_DIFFERENCE/);});
test('changed source requires a new reviewed binding',()=>{const {source,review}=fixture();source.rows[0].status='pending';assert.throws(()=>planImport(source,review),/REVIEW_SOURCE_MISMATCH/);});
test('duplicate source IDs and invalid roles cannot be imported',()=>{const {source,review}=fixture();source.rows.push({...source.rows[0]});rebind(source,review);assert.throws(()=>planImport(source,review),/DUPLICATE_SOURCE_ID/);const next=fixture();next.review.teams[0].players[1].role='captain';assert.equal(planImport(next.source,next.review).ready.length,0);});
test('production, remote and malformed targets are rejected',()=>{const target={environment:'local',database:'aevic_migration_test',port:55432,instanceId:'00000000-0000-4000-8000-000000000010'};assert.deepEqual(validateTarget(target),target);for(const invalid of [{...target,environment:'production'},{...target,database:productionRef},{...target,database:'aevic_migration_'+productionRef},{...target,host:'127.0.0.1'},{...target,database:'postgres'},{...target,url:'postgres://invalid'}])assert.throws(()=>validateTarget(invalid),/INVALID_LOCAL_TARGET/);});
test('logos are deferred, never copied or silently rehosted',()=>{const {source,review}=fixture();source.rows[0].logo_url='https://example.test/private/logo.png';rebind(source,review);const p=planImport(source,review);assert.equal(p.report.counts.deferredMedia,1);assert.equal(JSON.stringify(p.ready).includes('example.test'),false);});

test('unknown legacy history holds the team instead of presenting false zero history',()=>{const {source,review}=fixture();review.teams[0].historyDisposition='defer';const plan=planImport(source,review);assert.equal(plan.ready.length,0);assert.ok(plan.report.records[0].reasons.includes('HISTORY_REVIEW_REQUIRED'));});
