-- Additive compatibility layer for the original bigint public.teams identities.
-- Reuses existing tournament, match and organization entities; does not copy teams,
-- replace credentials, alter legacy tables, or change any existing RLS policy.
create schema aevic_platform;
revoke all on schema aevic_platform from public, anon, authenticated;
alter default privileges in schema aevic_platform revoke all on tables from public, anon, authenticated;
alter default privileges in schema aevic_platform revoke execute on functions from public;

-- Original identities reference their existing credential row; standalone accounts
-- have their own credentials and never fabricate a public team.
create table aevic_platform.accounts (
 id bigint generated by default as identity(start with 1000000000000) primary key,
 original_team_id bigint unique references public.teams on delete restrict,
 email text unique, password_hash text, reset_token text,
 captain_name text not null default '', captain_contact text not null default '',
 email_verified_at timestamptz, created_at timestamptz not null default now(),
 check((original_team_id is not null and email is null and password_hash is null and reset_token is null)
  or (original_team_id is null and email is not null and password_hash is not null)),
 check(email is null or email=lower(btrim(email)))
);
insert into aevic_platform.accounts(id,original_team_id) select id,id from public.teams;
select setval(pg_get_serial_sequence('aevic_platform.accounts','id'),greatest(1000000000000,coalesce((select max(id)+1 from aevic_platform.accounts),1000000000000)),false);
alter table aevic_platform.accounts enable row level security;
revoke all on aevic_platform.accounts from public,anon,authenticated;
create view aevic_platform.account_identity as
 select a.id,a.original_team_id,coalesce(t.email,a.email) as email,coalesce(t.password_hash,a.password_hash) as password_hash,
 case when a.original_team_id is null then a.reset_token else t.reset_token end as reset_token,
 coalesce(t.captain_name,a.captain_name) as captain_name,coalesce(t.captain_contact,a.captain_contact) as captain_contact,
 t.team_name,coalesce(t.status,'active') as status,a.email_verified_at,coalesce(t.created_at,a.created_at) as created_at
 from aevic_platform.accounts a left join public.teams t on t.id=a.original_team_id;
revoke all on aevic_platform.account_identity from public,anon,authenticated;

create table aevic_platform.admin_accounts (
 id uuid primary key default gen_random_uuid(), email text not null unique,
 first_name text not null default '', last_name text not null default '', phone text, email_verified_at timestamptz,
 password_hash text, role text not null check(role in ('super-admin','tournament-manager','result-operator','support-moderator')),
 active boolean not null default true, reset_digest text, reset_expires_at timestamptz,
 created_at timestamptz not null default now(), check(email=lower(btrim(email)))
);
create table aevic_platform.team_details (
 team_id bigint primary key references public.teams(id) on delete restrict,
 description text not null default '' check(length(description)<=3000), tag text check(length(tag)<=12),
 banner_url text, banner_alt text, country text, founded_at date,
 legacy_history_incomplete boolean not null default true,
 social_links jsonb not null default '{}' check(jsonb_typeof(social_links)='object'),
 email_verified_at timestamptz, archived_at timestamptz, updated_at timestamptz not null default now()
);
create table aevic_platform.sessions (
 id uuid primary key default gen_random_uuid(), token_digest text not null unique,
 team_id bigint references aevic_platform.accounts(id) on delete restrict,
 admin_id uuid references aevic_platform.admin_accounts on delete restrict,
 device text not null default 'Browser', created_at timestamptz not null default now(), last_active_at timestamptz not null default now(),
 expires_at timestamptz not null, revoked_at timestamptz,
 check((team_id is not null)::int+(admin_id is not null)::int=1)
);
create index platform_sessions_team on aevic_platform.sessions(team_id,expires_at);
create index platform_sessions_admin on aevic_platform.sessions(admin_id,expires_at);
create table aevic_platform.email_verifications (
 team_id bigint primary key references aevic_platform.accounts(id) on delete restrict,
 token_digest text not null unique, expires_at timestamptz not null, created_at timestamptz not null default now(), consumed_at timestamptz
);
create table aevic_platform.tournament_registrations (
 id uuid primary key default gen_random_uuid(), tournament_id uuid not null references aevic.tournaments on delete restrict,
 team_id bigint not null references public.teams(id) on delete restrict,
 status text not null default 'pending' check(status in ('pending','confirmed','waitlisted','withdrawn','rejected')),
 slot_number integer check(slot_number>0), roster_lock_at timestamptz not null,
 roster jsonb not null check(jsonb_typeof(roster)='array'), reason text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(tournament_id,team_id), unique(tournament_id,slot_number)
);
create index platform_registrations_team on aevic_platform.tournament_registrations(team_id,created_at desc);
create table aevic_platform.check_ins (
 tournament_id uuid not null, team_id bigint not null, checked_in_at timestamptz not null default now(),
 primary key(tournament_id,team_id),
 foreign key(tournament_id,team_id) references aevic_platform.tournament_registrations(tournament_id,team_id) on delete restrict
);
create index platform_checkins_team on aevic_platform.check_ins(team_id);
create table aevic_platform.team_match_results (
 id uuid primary key default gen_random_uuid(), match_id uuid not null, tournament_id uuid not null, team_id bigint not null,
 placement integer not null check(placement between 1 and 100), finishes integer not null check(finishes between 0 and 400),
 placement_points numeric not null check(placement_points>=0), finish_points numeric not null check(finish_points>=0), penalties numeric not null default 0 check(penalties>=0),
 total_points numeric generated always as (placement_points+finish_points-penalties) stored,
 published boolean not null default false, version integer not null default 1 check(version>0), notes text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 foreign key(match_id,tournament_id) references aevic.matches(id,tournament_id) on delete restrict,
 foreign key(tournament_id,team_id) references aevic_platform.tournament_registrations(tournament_id,team_id) on delete restrict,
 unique(match_id,team_id)
);
create index platform_results_team on aevic_platform.team_match_results(team_id,tournament_id);
create index platform_results_tournament on aevic_platform.team_match_results(tournament_id,team_id);
create table aevic_platform.result_versions (
 id uuid primary key default gen_random_uuid(), result_id uuid not null references aevic_platform.team_match_results on delete restrict,
 version integer not null, result jsonb not null, reason text not null, actor_id uuid not null references aevic_platform.admin_accounts on delete restrict,
 created_at timestamptz not null default now(), unique(result_id,version)
);
create index platform_versions_actor on aevic_platform.result_versions(actor_id);
create table aevic_platform.notifications (
 id uuid primary key default gen_random_uuid(), recipient_id bigint not null references aevic_platform.accounts(id) on delete restrict,
 title text not null, body text not null, severity text not null default 'info' check(severity in ('info','success','warning','critical')),
 event_type text not null default 'system', action_href text, read_at timestamptz, created_at timestamptz not null default now()
);
create index platform_notifications_recipient on aevic_platform.notifications(recipient_id,created_at desc,id);
create table aevic_platform.notification_preferences (
 user_id bigint primary key references aevic_platform.accounts(id) on delete restrict, preferences jsonb not null default '{}'
);
create table aevic_platform.messages (
 id uuid primary key default gen_random_uuid(), team_id bigint references public.teams(id) on delete restrict,
 author_id uuid not null references aevic_platform.admin_accounts on delete restrict,
 title text not null, body text not null, severity text not null default 'info' check(severity in ('info','success','warning','critical')),
 event_type text not null default 'admin-message', action_href text, created_at timestamptz not null default now()
);
create index platform_messages_team on aevic_platform.messages(team_id,created_at desc);
create index platform_messages_author on aevic_platform.messages(author_id);
create table aevic_platform.message_reads (
 message_id uuid not null references aevic_platform.messages(id) on delete restrict,
 account_id bigint not null references aevic_platform.accounts(id) on delete restrict,
 read_at timestamptz not null default now(), primary key(message_id,account_id)
);
create index platform_message_reads_account on aevic_platform.message_reads(account_id);
create table aevic_platform.support_tickets (
 id uuid primary key default gen_random_uuid(), user_id bigint not null references aevic_platform.accounts(id) on delete restrict,
 category text not null check(category in ('account','registration','roster','tournament','results','technical','other')),
 subject text not null check(length(subject) between 3 and 200), description text not null check(length(description) between 10 and 6000),
 status text not null default 'open' check(status in ('open','waiting-for-user','under-review','resolved','closed')),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index platform_tickets_user on aevic_platform.support_tickets(user_id,created_at desc);
create table aevic_platform.support_replies (
 id uuid primary key default gen_random_uuid(), ticket_id uuid not null references aevic_platform.support_tickets on delete restrict,
 author text not null check(author in ('user','support')), body text not null check(length(body) between 1 and 6000),
 created_at timestamptz not null default now()
);
create index platform_replies_ticket on aevic_platform.support_replies(ticket_id,created_at,id);
create table aevic_platform.support_attachments (
 id uuid primary key default gen_random_uuid(), ticket_id uuid not null references aevic_platform.support_tickets on delete restrict,
 file_name text not null check(length(file_name) between 1 and 200), mime_type text not null check(mime_type='image/webp'),
 bytes bytea not null check(octet_length(bytes) between 1 and 4000000), digest text not null,
 created_at timestamptz not null default now(), unique(ticket_id,digest)
);
create index platform_support_attachments_ticket on aevic_platform.support_attachments(ticket_id,created_at,id);
create table aevic_platform.follows (
 user_id bigint not null references aevic_platform.accounts(id) on delete restrict,
 team_id bigint not null references public.teams(id) on delete restrict, created_at timestamptz not null default now(), primary key(user_id,team_id)
);
create index platform_follows_team on aevic_platform.follows(team_id);
create table aevic_platform.disputes (
 id uuid primary key default gen_random_uuid(), team_id bigint not null, tournament_id uuid not null, match_id uuid not null,
 issue_type text not null check(issue_type in ('placement','kills','penalty','missing-result','other')), description text not null check(length(description) between 10 and 6000),
 status text not null default 'pending' check(status in ('pending','under-review','resolved','rejected')),
 deadline_at timestamptz not null, admin_note text, resolved_at timestamptz, created_at timestamptz not null default now(),
 foreign key(match_id,tournament_id) references aevic.matches(id,tournament_id) on delete restrict,
 foreign key(tournament_id,team_id) references aevic_platform.tournament_registrations(tournament_id,team_id) on delete restrict
);
create index platform_disputes_match on aevic_platform.disputes(match_id);
create index platform_disputes_team on aevic_platform.disputes(team_id,tournament_id);
create index platform_disputes_tournament on aevic_platform.disputes(tournament_id,team_id);
create table aevic_platform.roster_change_requests (
 id uuid primary key default gen_random_uuid(), team_id bigint not null references public.teams(id) on delete restrict,
 tournament_id uuid references aevic.tournaments on delete restrict, outgoing_player_id text not null,
 incoming_ign text not null check(length(incoming_ign) between 2 and 40), incoming_pubg_id text not null check(incoming_pubg_id ~ '^[0-9]{5,20}$'),
 incoming_role text not null check(incoming_role in ('captain','starter','substitute')), reason text not null,
 status text not null default 'pending' check(status in ('pending','under-review','approved','rejected')), admin_note text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index platform_roster_team on aevic_platform.roster_change_requests(team_id,created_at desc);
create index platform_roster_tournament on aevic_platform.roster_change_requests(tournament_id);
create table aevic_platform.player_details (
 team_id bigint not null references public.teams(id) on delete restrict, slot integer not null check(slot between 1 and 5),
 pubg_id text unique check(pubg_id ~ '^[0-9]{5,20}$'), role text check(role in ('captain','starter','substitute')), verified_at timestamptz, primary key(team_id,slot)
);
create table aevic_platform.featured_achievements (
 team_id bigint not null references public.teams(id) on delete restrict, achievement_id text not null,
 position integer not null check(position between 1 and 3), primary key(team_id,achievement_id), unique(team_id,position)
);
create table aevic_platform.organization_teams (
 organization_id uuid not null references aevic.organizations on delete restrict,
 team_id bigint not null unique references public.teams(id) on delete restrict, created_at timestamptz not null default now(), primary key(organization_id,team_id)
);
create table aevic_platform.verification_requests (
 id uuid primary key default gen_random_uuid(), team_id bigint not null references public.teams(id) on delete restrict,
 representative_name text not null, official_socials jsonb not null default '{}', notes text not null,
 status text not null default 'PENDING' check(status in ('PENDING','APPROVED','REJECTED','REVOKED')),
 safe_reason text, reviewed_at timestamptz, reviewed_by uuid references aevic_platform.admin_accounts on delete restrict,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index platform_verification_team on aevic_platform.verification_requests(team_id,created_at desc);
create unique index platform_verification_active on aevic_platform.verification_requests(team_id) where status in ('PENDING','APPROVED');
create table aevic_platform.audit_events (
 id uuid primary key default gen_random_uuid(), actor_id text not null, action text not null, entity_type text not null, entity_id text,
 metadata jsonb not null default '{}', created_at timestamptz not null default now()
);
create index platform_audit_created on aevic_platform.audit_events(created_at desc,id);
create table aevic_platform.idempotency (
 actor_id text not null, key text not null, action text not null, payload_digest text not null, result jsonb not null,
 created_at timestamptz not null default now(), primary key(actor_id,key)
);
create table aevic_platform.settings (
 key text primary key, value jsonb not null, updated_at timestamptz not null default now()
);
-- This private schema is reachable only through the authenticated server gateway.
-- No client role receives USAGE or table grants; RLS is an additional deny-all layer.
do $$ declare t record; begin
 for t in select tablename from pg_tables where schemaname='aevic_platform' loop
  execute format('alter table aevic_platform.%I enable row level security',t.tablename);
  execute format('revoke all on aevic_platform.%I from public, anon, authenticated',t.tablename);
 end loop;
end $$;
create table aevic_platform.media (
 id uuid primary key default gen_random_uuid(), team_id bigint not null references public.teams(id) on delete restrict,
 dispute_id uuid references aevic_platform.disputes on delete restrict, file_name text not null,
 asset_type text not null check(asset_type in ('logo','banner','player-photo','evidence')),
 mime_type text not null check(mime_type in ('image/png','image/jpeg','image/webp')),
 bytes bytea not null check(octet_length(bytes)<=4000000), created_at timestamptz not null default now()
);
create index platform_media_team on aevic_platform.media(team_id);
create index platform_media_dispute on aevic_platform.media(dispute_id);
alter table aevic_platform.media enable row level security;
revoke all on aevic_platform.media from public, anon, authenticated;
create table aevic_platform.account_requests (
 id uuid primary key default gen_random_uuid(),team_id bigint references aevic_platform.accounts(id) on delete restrict,
 admin_id uuid references aevic_platform.admin_accounts on delete restrict,
 check((team_id is null)<>(admin_id is null)),
 kind text not null check(kind in ('export','deletion')),status text not null default 'pending' check(status in ('pending','completed','rejected')),
 created_at timestamptz not null default now()
);
create index platform_account_requests_admin on aevic_platform.account_requests(admin_id,created_at desc);
create index platform_account_requests_team on aevic_platform.account_requests(team_id,created_at desc);
alter table aevic_platform.account_requests enable row level security;
revoke all on aevic_platform.account_requests from public,anon,authenticated;
create table aevic_platform.sanctions (
 id uuid primary key default gen_random_uuid(),team_id bigint not null references public.teams(id) on delete restrict,
 reason text not null,previous_status text not null,expires_at timestamptz,revoked_at timestamptz,actor_id uuid not null references aevic_platform.admin_accounts on delete restrict,
 created_at timestamptz not null default now()
);
create index platform_sanctions_team on aevic_platform.sanctions(team_id,expires_at);
create index platform_sanctions_actor on aevic_platform.sanctions(actor_id);
alter table aevic_platform.sanctions enable row level security;
revoke all on aevic_platform.sanctions from public,anon,authenticated;

-- Immutable standings at each publication/correction, never rebuilt from edited scores.
create table aevic_platform.leaderboard_snapshots (
 id uuid primary key default gen_random_uuid(),
 tournament_id uuid not null references aevic.tournaments on delete restrict,
 match_id uuid not null references aevic.matches on delete restrict,
 reason text not null check(reason in ('publication','correction')),
 standings jsonb not null check(jsonb_typeof(standings)='array'),
 published_at timestamptz not null default clock_timestamp()
);
create index platform_snapshots_tournament on aevic_platform.leaderboard_snapshots(tournament_id,published_at,id);
create index platform_snapshots_match on aevic_platform.leaderboard_snapshots(match_id);
alter table aevic_platform.leaderboard_snapshots enable row level security;
revoke all on aevic_platform.leaderboard_snapshots from public,anon,authenticated;

create table aevic_platform.mfa_factors (
 actor_key text primary key,
 team_id bigint unique references aevic_platform.accounts(id) on delete restrict,
 admin_id uuid unique references aevic_platform.admin_accounts on delete restrict,
 secret_ciphertext text not null,
 setup_id uuid not null default gen_random_uuid(),setup_expires_at timestamptz not null,
 enabled_at timestamptz,last_step bigint not null default -1,
 recovery_digests text[] not null default '{}',
 check(num_nonnulls(team_id,admin_id)=1),
 check(actor_key=case when team_id is not null then 'team:'||team_id::text else 'admin:'||admin_id::text end)
);
alter table aevic_platform.mfa_factors enable row level security;
revoke all on aevic_platform.mfa_factors from public,anon,authenticated;
alter table aevic_platform.sessions add column mfa_verified_at timestamptz;

create table aevic_platform.player_claims (
 id uuid primary key default gen_random_uuid(),pubg_id text not null check(pubg_id ~ '^[0-9]{5,20}$'),
 claimant_id bigint not null references aevic_platform.accounts(id) on delete restrict,
 method text not null check(method in ('ACCOUNT_MATCH','PUBG_IDENTITY','ADMIN_REVIEW')),
 status text not null default 'PENDING' check(status in ('PENDING','APPROVED','REJECTED')),
 safe_reason text,reviewed_by uuid references aevic_platform.admin_accounts on delete restrict,
 created_at timestamptz not null default now(),reviewed_at timestamptz
);
create unique index platform_player_claim_pending on aevic_platform.player_claims(pubg_id,claimant_id) where status='PENDING';
create unique index platform_player_claim_owner on aevic_platform.player_claims(pubg_id) where status='APPROVED';
create index platform_player_claim_account on aevic_platform.player_claims(claimant_id);
create index platform_player_claim_reviewer on aevic_platform.player_claims(reviewed_by);
alter table aevic_platform.player_claims enable row level security;
revoke all on aevic_platform.player_claims from public,anon,authenticated;

-- Organization authority refers to existing captain accounts, never synthetic auth users.
create table aevic_platform.organization_members (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references aevic.organizations on delete restrict,
 account_id bigint not null references aevic_platform.accounts on delete restrict, role text not null check(role in ('OWNER','MANAGER','MEMBER')),
 created_at timestamptz not null default now(), unique(organization_id,account_id)
);
create unique index platform_organization_owner on aevic_platform.organization_members(organization_id) where role='OWNER';
create index platform_organization_member_account on aevic_platform.organization_members(account_id);
alter table aevic_platform.organization_members enable row level security;
revoke all on aevic_platform.organization_members from public,anon,authenticated;
create table aevic_platform.organization_invitations (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references aevic.organizations on delete restrict,
 target_team_id bigint references public.teams on delete restrict,
 recipient_id bigint not null references aevic_platform.accounts on delete restrict, kind text not null check(kind in ('ORGANIZATION_MEMBER','ORGANIZATION_TEAM')),
 role text check(role in ('MANAGER','MEMBER')), status text not null default 'PENDING' check(status in ('PENDING','ACCEPTED','REJECTED','EXPIRED','CANCELLED')),
 created_at timestamptz not null default now(), expires_at timestamptz not null default now()+interval '7 days', responded_at timestamptz,
 check((kind='ORGANIZATION_MEMBER' and role is not null and target_team_id is null) or (kind='ORGANIZATION_TEAM' and role is null and target_team_id is not null))
);
create index platform_org_invitation_target on aevic_platform.organization_invitations(target_team_id);
create index platform_org_invitation_recipient on aevic_platform.organization_invitations(recipient_id,created_at desc);
create unique index platform_org_member_invitation_pending on aevic_platform.organization_invitations(organization_id,recipient_id) where status='PENDING' and kind='ORGANIZATION_MEMBER';
create unique index platform_org_team_invitation_pending on aevic_platform.organization_invitations(organization_id,target_team_id) where status='PENDING' and kind='ORGANIZATION_TEAM';
alter table aevic_platform.organization_invitations enable row level security;
revoke all on aevic_platform.organization_invitations from public,anon,authenticated;

create table aevic_platform.team_authority (
 id uuid primary key default gen_random_uuid(),team_id bigint not null references public.teams on delete restrict,
 account_id bigint not null references aevic_platform.accounts on delete restrict,
 role text not null check(role in ('OWNER','CAPTAIN','MANAGER','CO_CAPTAIN','PLAYER','SUBSTITUTE')),
 created_at timestamptz not null default now(),unique(team_id,account_id)
);
create unique index platform_team_authority_owner on aevic_platform.team_authority(team_id) where role='OWNER';
create index platform_team_authority_account on aevic_platform.team_authority(account_id);
alter table aevic_platform.team_authority enable row level security;
revoke all on aevic_platform.team_authority from public,anon,authenticated;
insert into aevic_platform.team_authority(team_id,account_id,role) select id,id,'OWNER' from public.teams;
create table aevic_platform.team_invitations (
 id uuid primary key default gen_random_uuid(),team_id bigint not null references public.teams on delete restrict,
 recipient_id bigint not null references aevic_platform.accounts on delete restrict,role text not null check(role in ('CAPTAIN','MANAGER','CO_CAPTAIN','PLAYER','SUBSTITUTE')),
 status text not null default 'PENDING' check(status in ('PENDING','ACCEPTED','REJECTED','CANCELLED','EXPIRED')),
 created_at timestamptz not null default now(),expires_at timestamptz not null default now()+interval '7 days',responded_at timestamptz
);
create unique index platform_team_invitation_pending on aevic_platform.team_invitations(team_id,recipient_id) where status='PENDING';
create index platform_team_invitation_recipient on aevic_platform.team_invitations(recipient_id,created_at desc);
alter table aevic_platform.team_invitations enable row level security;
revoke all on aevic_platform.team_invitations from public,anon,authenticated;

create table aevic_platform.legacy_claims (
 id uuid primary key default gen_random_uuid(),team_id bigint not null references public.teams on delete restrict,
 claimant_id bigint not null references aevic_platform.accounts on delete restrict,
 status text not null default 'pending' check(status in ('pending','approved','rejected','consumed')),
 version integer not null default 1,token_digest text,expires_at timestamptz,
 evidence_id uuid references aevic_platform.support_tickets on delete restrict,
 reviewer_id uuid references aevic_platform.admin_accounts on delete restrict,
 created_at timestamptz not null default now(),reviewed_at timestamptz,consumed_at timestamptz,
 check((token_digest is null)=(expires_at is null))
);
create unique index platform_legacy_claim_open on aevic_platform.legacy_claims(team_id,claimant_id) where status in ('pending','approved');
create unique index platform_legacy_claim_consumed on aevic_platform.legacy_claims(team_id) where status='consumed';
create index platform_legacy_claim_claimant on aevic_platform.legacy_claims(claimant_id,created_at desc);
create index platform_legacy_claim_evidence on aevic_platform.legacy_claims(evidence_id);
create index platform_legacy_claim_reviewer on aevic_platform.legacy_claims(reviewer_id);
alter table aevic_platform.legacy_claims enable row level security;
revoke all on aevic_platform.legacy_claims from public,anon,authenticated;
